### ISSUE TITLE
Guidance on Customizing Layout after Render (aka incremental/dynamic layout)

### ISSUE THREAD

**Issue by amcdnl** [kieler/elkjs#100]
I'm looking for guidance on how to use ELKJS in combination with a custom drag positioning.

I'm the author of https://reaflow.dev which uses ELKJS under the hood for its layout engine. One feature I would like to add is the ability for a user to drag a node to a new position and it stick there while when adding new nodes the rest of the layout stays the same. 

I realize this is outside the scope of this project but would love to get the communities ideas on what the best way might be to accomplish this and keep all the power of elk too.

Thanks!

**Comment by uruuru** [comment]
As you already state yourself, while this is being requested/desired regularly, it's out of scope and not well-suited for ELK layered. 

For the record, some issues that discuss parts of this topic: elk#315 elk#355 elk#627.

**Comment by amcdnl** [comment]
@uruuru - Thanks for the feedback! I had not seen those links so thats helpful.

Absolutely - I wasn't expecting the library to implement this feature - I was just curious if anyone had any tips of how to get started / what to avoid / etc.

**Comment by uruuru** [comment]
Yes. I'll leave the issue open for discussions. We're always interested in the ways how others approach layout adjustments. After all, it may be inspiring for either adjustments in ELK or for a future layout algorithm specifically designed for this problem.

**Comment by uruuru** [comment]
I'll close the issue itself. I've added it to the main readme for reference.
