### ISSUE TITLE
How can i preserve the order of nodes in a layer?

### ISSUE THREAD

**Issue by SumayyaZiyad** [kieler/elkjs#102]
The node order of layers seem to be changing based on the number of nodes. How can i prevent this from happening? I am using elkjs on typescript and below are the options I have enabled. ` const graph = {
        id: "root",
        layoutOptions: { 
            'elk.algorithm': 'layered',
            'elk.direction': 'DOWN',
            'crossingMinimization.strategy': 'INTERACTIVE'
        },
        children: retrievedMap[0],
        edges: retrievedMap[1]
    };
` Each node in my childrens array have a nodeId, height, and width.

**Comment by SumayyaZiyad** [comment]
`layoutOptions: { 
            'elk.algorithm': 'layered',
            'elk.direction': 'DOWN',
            'elk.layered.crossingMinimization.semiInteractive': 'true'
        },`

^ along with setting a position for each node worked

**Comment by caravinden** [comment]
@SumayyaZiyad  how you used position option for node. Sample config would be really helpful

**Comment by SumayyaZiyad** [comment]
@caravinden When setting the other properties for each node, you can set the position in the layout option as below.
```id: array[i].nodeID,
            width: 150,
            height: 50,
            label: array[i].value,
            layoutOptions: { 
                'elk.position': '('+i+', 0)'
            },
``` 

i there is an integer of mine that increases based on priority.

**Comment by brunaschneiders** [comment]
Hi, everyone! 

Is it possible to do something like this, but using the "mrtree" algorithm layout?

> @caravinden When setting the other properties for each node, you can set the position in the layout option as below.
> 
> ```
>             width: 150,
>             height: 50,
>             label: array[i].value,
>             layoutOptions: { 
>                 'elk.position': '('+i+', 0)'
>             },
> ```
> 
> i there is an integer of mine that increases based on priority.

**Comment by SumayyaZiyad** [comment]
@brunaschneiders I tried out different options with MrTree Algo, but couldnt find a solution :/

**Comment by uruuru** [comment]
@brunaschneiders afaik MrTree doesn't include such functionality. 

Hints:
* the `layered` part of the layout option id `elk.layered.crossingMinimization.semiInteractive` tells you that the option is specific to the layered algorithm. 
* options supported by MrTree can be found [here](https://www.eclipse.org/elk/reference/algorithms/org-eclipse-elk-mrtree.html).

**Comment by dwjohnston** [comment]
@sumayya

> @caravinden When setting the other properties for each node, you can set the position in the layout option as below.
> 
> ```
>             width: 150,
>             height: 50,
>             label: array[i].value,
>             layoutOptions: { 
>                 'elk.position': '('+i+', 0)'
>             },
> ```
> 
> i there is an integer of mine that increases based on priority.

I can't see that this solution works: 

https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGAOQF4DmKSk6ACwC2beG0JEApkknQ2WMLghtJeANYA6aJBkBjWg1GIAIhQDqAOWyKIy1ZonTZG+imiSACoV2Shk+ugaAGYEAG68AMroSASQXALoAKLQXJKMRiF4jJJKAL44ELoCkHjQMvTwANpKYKww8Aj0AIzWAO4wgvAAzAAMCgKScQndPWD5NXVwiPQATG0dAvAArH1gA0PoIwoSZJQ0dEwsNRAI9hpUKIz8BwgNABRNCj0AlAg1uWMFtpMN9F3z0E6YF6-UG8U2wNWNR25GoBkOtWOiDOFyu8NuJzuqxeb1sY1yuAAul9ZKlmGBqnifsiWgpGGQkD5yZVpi0wMSwOgCEhUuhmdM5uzPhMoFNTnM6QymVVWQh2QouTzJHyZY1-kKCRBCSBckA
