### ISSUE TITLE
Best port detection option in elkjs

### ISSUE THREAD

**Issue by caravinden** [kieler/elkjs#104]
Do we have any configuration to find best suitable port in a node to connect

I am Implementing bpmn diagram using elkjs. Node to gateway edges has been connected through ports.[North,East, South,West]. Currently Node to port connecting as configured manually. 

Instead of manually connect through the port. It would be really help full to place Node to node connection like [ n1 - n2 ]. And best suitable port in n2 can be find by elkjs. @uruuru  @khoshrou
<img width="596" alt="bpmn" src="https://user-images.githubusercontent.com/5152392/100729055-4e127e80-33ee-11eb-88d8-79a8a5ea11f6.PNG">

**Comment by caravinden** [comment]
- [ ]

**Comment by uruuru** [comment]
It depends on the use case what _best suitable_ is.

In your case I'd assume that you'd want to have at most one edge to each side (if possible)? That, I'm afraid, elkjs doesn't support. 

Given a left-to-right layout and no ports, incoming edges will connect on the west side of a node, outgoing edges on the east. The northern and southern side of a node won't be used.

**Comment by caravinden** [comment]
Thanks @uruuru for your response. The issue which i have is , How to connect node to port [Cardinal Points](https://en.wikipedia.org/wiki/Cardinal_direction)  in gateway or [decision](https://en.wikipedia.org/wiki/Flowchart). I can able to achieve node to node connection as you mentioned above[ EAST to WEST].  

It would be really helpful if you can suggest whether we can achieve the same using below config

- [Switch side](http://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=ports%2FallowNonFlowPortsToSwitchSides)
- [Vertical / Horizontal ordering ](http://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=user-hints%2Flayered%2FverticalOrder)

elkjs config json below:-
{
  "id": "root",
  "layoutOptions": {
    "elk.algorithm": "layered",
    "elk.layered.feedbackEdges": true,
    "elk.hierarchyHandling": "SEPARATE_CHILDREN",
    "elk.alignment": "RIGHT",
    "elk.direction": "RIGHT",
    "elk.aspectRatio": 10,
    "elk.edgeRouting": "ORTHOGONAL",
    "elk.layered.nodePlacement.bk.fixedAlignment": "BALANCED",
    "elk.layered.allowNonFlowPortsToSwitchSides": true,
    "elk.spacing.edgeNode": 30,
    "elk.spacing.nodeNode": 10,
    "partitioning.activate": true,
    "nodeFlexibility": "NODE_SIZE"
  },
  "children": [
    {
      "id": "n1",
      "width": 10,
      "height": 0,
      "type": "start"
    },
    {
      "id": "n2",
      "width": 70,
      "height": 50,
      "type": "activity"
    },
    {
      "id": "n3",
      "width": 30,
      "height": 30,
      "type": "gateway",
      "ports": [
        {
          "id": "P1",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "NORTH",
            "port.index": "1",
            "allowNonFlowPortsToSwitchSides": true
          }
        },
        {
          "id": "P2",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "EAST",
            "port.index": "2",
            "allowNonFlowPortsToSwitchSides": true
          }
        },
        {
          "id": "P3",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "SOUTH",
            "port.index": "3",
            "allowNonFlowPortsToSwitchSides": true
          }
        },
        {
          "id": "P4",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "WEST",
            "port.index": "4",
            "allowNonFlowPortsToSwitchSides": true
          }
        }
      ],
      "properties": {
        "portConstraints": "FIXED_ORDER",
        "portAlignment": "CENTER"
      }
    },
    {
      "id": "n4",
      "width": 70,
      "height": 50,
      "type": "activity"
    },
    {
      "id": "n5",
      "width": 70,
      "height": 50,
      "type": "activity",
      "ports": [
        {
          "id": "P17",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "NORTH",
            "port.index": "1"
          }
        },
        {
          "id": "P18",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "SOUTH",
            "port.index": "2"
          }
        },
        {
          "id": "P19",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "EAST",
            "port.index": "3"
          }
        },
        {
          "id": "P20",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "WEST",
            "port.index": "4"
          }
        }
      ],
      "properties": {
        "portConstraints": "FIXED_SIDE",
        "portAlignment": "CENTER"
      }
    },
    {
      "id": "n6",
      "width": 70,
      "height": 50,
      "type": "activity"
    },
    {
      "id": "n7",
      "width": 70,
      "height": 50,
      "type": "activity"
    },
    {
      "id": "n8",
      "width": 30,
      "height": 30,
      "type": "gateway",
      "ports": [
        {
          "id": "P5",
          "width": 4,
          "height": 4,
          "properties": {
            "port.side": "NORTH",
            "port.index": "1"
          }
        },
        {
          "id": "P6",
          "width": 4,
          "height": 4,
          "properties": {
            "port.side": "SOUTH",
            "port.index": "2"
          }
        },
        {
          "id": "P7",
          "width": 4,
          "height": 4,
          "properties": {
            "port.side": "EAST",
            "port.index": "3"
          }
        },
        {
          "id": "P8",
          "width": 4,
          "height": 4,
          "properties": {
            "port.side": "WEST",
            "port.index": "4"
          }
        }
      ],
      "properties": {
        "portConstraints": "FIXED_ORDER",
        "portAlignment": "CENTER"
      }
    },
    {
      "id": "n9",
      "width": 70,
      "height": 50,
      "type": "activity"
    },
    {
      "id": "n10",
      "width": 10,
      "height": 10,
      "type": "end"
    },
    {
      "id": "n11",
      "width": 70,
      "height": 50,
      "type": "activity"
    },
    {
      "id": "n12",
      "width": 30,
      "height": 30,
      "type": "gateway",
      "ports": [
        {
          "id": "P9",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "NORTH",
            "port.index": "1"
          }
        },
        {
          "id": "P10",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "SOUTH",
            "port.index": "2"
          }
        },
        {
          "id": "P11",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "EAST",
            "port.index": "3"
          }
        },
        {
          "id": "P12",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "WEST",
            "port.index": "4"
          }
        }
      ],
      "properties": {
        "portConstraints": "FIXED_SIDE",
        "portAlignment": "CENTER"
      }
    },
    {
      "id": "n13",
      "width": 70,
      "height": 50,
      "type": "activity",
      "ports": [
        {
          "id": "P13",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "NORTH",
            "port.index": "1"
          }
        },
        {
          "id": "P14",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "SOUTH",
            "port.index": "2"
          }
        },
        {
          "id": "P15",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "EAST",
            "port.index": "3"
          }
        },
        {
          "id": "P16",
          "width": 5,
          "height": 5,
          "properties": {
            "port.side": "WEST",
            "port.index": "4"
          }
        }
      ],
      "properties": {
        "portConstraints": "FIXED_SIDE",
        "portAlignment": "CENTER"
      }
    }
  ],
  "edges": [
    {
      "id": "e1",
      "sources": [
        "n1"
      ],
      "targets": [
        "n2"
      ]
    },
    {
      "id": "e2",
      "sources": [
        "n2"
      ],
      "targets": [
        "P4"
      ]
    },
    {
      "id": "e15",
      "sources": [
        "P1"
      ],
      "targets": [
        "n4"
      ]
    },
    {
      "id": "e16",
      "sources": [
        "P2"
      ],
      "targets": [
        "n5"
      ]
    },
    {
      "id": "e17",
      "sources": [
        "P3"
      ],
      "targets": [
        "n6"
      ]
    },
    {
      "id": "e6",
      "sources": [
        "n4"
      ],
      "targets": [
        "n7"
      ]
    },
    {
      "id": "e7",
      "sources": [
        "n7"
      ],
      "targets": [
        "n10"
      ]
    },
    {
      "id": "e8",
      "sources": [
        "n5"
      ],
      "targets": [
        "n10"
      ]
    },
    {
      "id": "e9",
      "sources": [
        "n6"
      ],
      "targets": [
        "P8"
      ]
    },
    {
      "id": "e10",
      "sources": [
        "P5"
      ],
      "targets": [
        "n9"
      ]
    },
    {
      "id": "e11",
      "sources": [
        "P6"
      ],
      "targets": [
        "n11"
      ]
    },
    {
      "id": "e12",
      "sources": [
        "n9"
      ],
      "targets": [
        "P9"
      ]
    },
    {
      "id": "e13",
      "sources": [
        "P10"
      ],
      "targets": [
        "P20"
      ]
    },
    {
      "id": "e14",
      "sources": [
        "P11"
      ],
      "targets": [
        "n13"
      ]
    },
    {
      "id": "e161",
      "sources": [
        "P13"
      ],
      "targets": [
        "P17"
      ]
    }
  ]
}

**Comment by uruuru** [comment]
As said above, there's no option to automatically distribute ports across all four node sides. 

To elaborate on the `allowNonFlowPortsToSwitchSides` option: if you specified a port to be either `NORTH` or `SOUTH`, alongside `FIXED_SIDE` port consttraints, the option allows the algorithm to automatically choose between north and south in order to _decrease the number of edge crossings_.
