### ISSUE TITLE
Layout option for ELKJS to accommodate the connected graph in a particular frame based on screen size to avoid horizontal and vertical scrolling

### ISSUE THREAD

**Issue by rashmishukla04** [kieler/elkjs#106]
I have use this layout option for graph creation using elkjs Algorithm.
layoutOptions:{
elk.algorithm :layered,
elk.zoomToFit: true,
elk.interactiveLayout: true;
elk.spacing.nodeNode :window.outerHeight/25.8,
elk.spacing.edgeEdge:20,
elk.layered.spacing.nodeNodebetweenLayers: window.outerWidth*.04
}
As per my current requirements ,I need to accommodate the connected graph in a particular frame based on screen size to avoid horizontal and vertical scrolling(Responsive screen also).
Please suggest any possible layout options that will resolve my concern. I tried to use aspect ratio but it didn't works for me.
 @uruuru

**Comment by rashmishukla04** [comment]
I have use this layout option for graph creation using elkjs Algorithm.
layoutOptions:{
elk.algorithm :layered,
elk.zoomToFit: true,
elk.interactiveLayout: true;
elk.spacing.nodeNode :window.outerHeight/25.8,
elk.spacing.edgeEdge:20,
elk.layered.spacing.nodeNodebetweenLayers: window.outerWidth*.04
}
As per my current requirements ,I need to accommodate the connected graph in a particular frame based on screen size to avoid horizontal and vertical scrolling(Responsive screen also).
Please suggest any possible layout options that will resolve my concern. I tried to use aspect ratio but it didn't works for me.
 @uruuru

**Comment by uruuru** [comment]
Most users do this by scaling their rendered drawing to fit the available screen. 

There are a number of layout options that _may_ influence the aspect ratio of a resulting drawing. However, often times this depends on the concrete instance's structure and cannot make any guarantees w.r.t. the exact number of used pixels.
