### ISSUE TITLE
Getting only straight edges

### ISSUE THREAD

**Issue by andreash** [kieler/elkjs#107]
Hi everbody - 

I played around with elkjs and one of the graph examples (ci_router_ComplexRouter.json). As a result, I am only getting straight lines as edges - each edge has only one section. Anybody experience this before? I call the layouter like this:

```javascript
const graph = require("./complex_router.js");
const elk = new ELK({defaultLayoutOptions:{
    'elk.edgeRouting': 'ORTHOGONAL',
    'elk.algorithm': 'elk.layered'
}})

elk.layout(graph)
    .then(g => {
        // ... do something with the result ;
    })
    .catch(err => {
        console.error(err);
    })
```
No change whether I put in our leave out the layout options ...
Any help is greatly appreciated.

Best,
Andreas

**Comment by uruuru** [comment]
Did you check the `bendPoints` of the section? It's normal for layered's output to only provide a single section.

**Comment by andreash** [comment]
I knew I missed something. Thanks!
