### ISSUE TITLE
Add nodes to a layout

### ISSUE THREAD

**Issue by andreash** [kieler/elkjs#108]
Hi - I have usecase to add nodes to an already existing layout (laid out by "layered" algorithm). If more nodes are added by some means, it would be great if - as a first step - the position of the existing nodes could be kept in place in order for the user to recognize the graph. Is this possible? I played around with "fixed" and "layered" a bit, but I am not sure it is possible. Best regards, Andreas

**Comment by uruuru** [comment]
There's very little support in this direction. You can have a look at the _user hints_ section of the [ELK Live Examples](https://rtsys.informatik.uni-kiel.de/elklive/examples.html). Other than that, it's frequently requested but not well supported, see #100.

**Comment by andreash** [comment]
Thanks for the quick answer! I'll actually come around with another question :).
