### ISSUE TITLE
Partition value ignored if node has no links

### ISSUE THREAD

**Issue by mdbaehre** [kieler/elkjs#110]
When I activate partitioning and have included a partition value for each node - but include a node with no connections the node is  positioned in the left most partition instead of the partition with other nodes of the same partition value.  If I add a connection between the node and any other node then the node is properly positioned in its associated partition.  Is this the expected behavior?  I would have thought that a node is placed in its appropriate partition regardless of whether it has any connections to it.

**Comment by uruuru** [comment]
You probably have to deactivate `separateConnectedComponents`: 

```
algorithm: layered
partitioning.activate: true
separateConnectedComponents: false

node n1 {
    partitioning.partition: 1
}
node n2 {
    partitioning.partition: 2
}
node n3 {
    partitioning.partition: 3
}
```
