### ISSUE TITLE
Approximating Class diagrams

### ISSUE THREAD

**Issue by dfreeman06** [kieler/elkjs#111]
Not sure if I should open this ticket on the https://github.com/eclipse/elk or here. 
But i am ultimately using attempting to use elkjs to approximate a typical class diagram and was able to come up with this in the elkt editor using the latest snapshot version. 

```
algorithm: layered
elk.hierarchyHandling: INCLUDE_CHILDREN

node class{
    // layout [size: 300,60]
    algorithm: rectpacking
    expandNodes: true
    elk.spacing.nodeNode:0
    elk.hierarchyHandling: INCLUDE_CHILDREN
    elk.padding: "[]"

    aspectRatio: 0.000001
        
    node c1 {
        nodeLabels.placement: "INSIDE V_CENTER H_LEFT"
        nodeSize.constraints: NODE_LABELS
        label "Properties"{
            layout [size: 62, 15]
            nodeLabels.placement: "INSIDE V_TOP H_CENTER"
            }
        label "x=1" {layout [size: 23, 15]}
        label "x=2" {layout [size: 23, 15]}
        label "x=3" {layout [size: 23, 15]}
    }
    node c2 {
        nodeSize.constraints: NODE_LABELS
        nodeLabels.placement: "INSIDE V_TOP H_LEFT"
        label "Methods"{
            layout [size: 62, 15]
            nodeLabels.placement: "INSIDE V_TOP H_CENTER"
        
        }
        label " "  // dummy space
        label "get(arg1)" {layout [size: 55, 15]}
        label "set(key, value)" {layout [size: 82, 15]}
    }

    node n3{
        nodeSize.constraints: NODE_LABELS
        nodeLabels.placement: "INSIDE V_TOP H_CENTER"
        label "Internal Diagram"{layout [size: 100,15]}
        node n6{layout [size: 50,15]
            port pw1 { ^port.side: SOUTH }
        }
        node n7{layout [size: 50,15]
            port pw1 { ^port.side: SOUTH }
        }
        edge n6.pw1 -> n7.pw1
        
    }
    
    port top
}
node external {
    layout [size: 60,40]
    nodeLabels.placement: "INSIDE V_CENTER H_CENTER"
    label "external" {layout [size: 50,15]}
}
edge class.top -> external
```

Which produces:
![image](https://user-images.githubusercontent.com/6493354/102512351-ee57dc80-4057-11eb-98d3-90c6cbcd169e.png)

The issue I have is going into the JSON world. When I convert the elkt to json for use in the live json editor there is a parsing error `cannot read property f of null`. Minified errors are the most readable. Also trying to layout the above in version `0.7.0` yields a poor diagram but no parsing error. 

It looks like the elk versions are different between the two editors which hopefully resolve the discrepancy but wanted to raise the question to be sure.

**Comment by uruuru** [comment]
Regarding class diagram layout in general, also see eclipse/elk#670.

Regarding debugging minified code: there's a non-minified version that should provide somewhat better names, see the debugging section of the readme (if you want to try elk-live locally). 

Regarding version discrepancies: yes, the latest version of ELK is closer to the master branch's head. We recently had a couple of issues that have been fixed after 0.7.0.

**Comment by dfreeman06** [comment]
Thanks @uruuru, running the non-minified worker locally has helped with debugging some of the expected layoutOptions.

**Comment by uruuru** [comment]
Good. Anything noticeable worth sharing?

**Comment by dfreeman06** [comment]
There wasn't anything too specific but it was another useful piece in understanding some of the interactions between different settings. 

![image](https://user-images.githubusercontent.com/6493354/105606618-7e302b00-5d68-11eb-9f27-f205cfab2467.png)


<details>
<summary>elk json</summary>
{"id": "root", "children": [{"id": "93a094ec-1f02-4387-86d4-5efbde162d18", "children": [{"id": "583fb78a-aaa0-461e-bfea-989776a95856", "children": [], "labels": [{"id": "d818efbc-e783-4b9f-8517-a3dd2e1ff270", "text": "Vehicle", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 39.328121185302734}, {"id": "a985d3b3-7a40-464f-afd8-85b5283679d7", "text": "\\u00abblock\\u00bb", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 41.906246185302734}], "layoutOptions": {"org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN", "org.eclipse.elk.padding": "[top=0.0,bottom=0.0,left=0.0,right=0.0]", "org.eclipse.elk.spacing.nodeNode": "0.0", "org.eclipse.elk.edge.edgeNode": "0.0", "org.eclipse.elk.aspectRatio": "100.0", "org.eclipse.elk.expandNodes": "true", "org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE", "org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.spacing.componentComponent": "0.0", "org.eclipse.elk.nodeSize.minimum": "(220, 20)"}}, {"id": "68d84143-d597-43cd-812d-e4c544d093d4", "children": [{"id": "9e65c6d5-f205-44db-a78f-addc8ce96573", "children": [{"id": "b7298b2b-8dea-4166-a46d-ce1402906ab1", "children": [], "height": 0.0, "labels": [{"id": "618e199f-e848-432a-8dbc-ca9b445bb311", "text": "start engine", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 62.656246185302734}], "layoutOptions": {"org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE"}, "width": 0.0}, {"id": "52d09682-aebf-4cc5-b09e-0b62cf0e5327", "children": [], "height": 0.0, "labels": [{"id": "82e293ff-d6e7-46b4-9849-cbc010abf75c", "text": "drive", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 27.0}], "layoutOptions": {"org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE"}, "width": 0.0}, {"id": "e5ec11ee-5c07-479d-9515-9fa007a3a762", "children": [], "height": 0.0, "labels": [{"id": "30b371ac-f23c-4a93-a435-34802fd7a211", "text": "park", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 25.0625}], "layoutOptions": {"org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE"}, "width": 0.0}], "edges": [{"id": "61c148d4-190e-4666-ad14-03f4c5d5d6a3", "sources": ["b7298b2b-8dea-4166-a46d-ce1402906ab1"], "targets": ["52d09682-aebf-4cc5-b09e-0b62cf0e5327"]}, {"id": "cda1ea8f-7253-4271-9fd1-dd3496205e3c", "sources": ["52d09682-aebf-4cc5-b09e-0b62cf0e5327"], "targets": ["e5ec11ee-5c07-479d-9515-9fa007a3a762"]}], "labels": [], "layoutOptions": {"org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.nodeSize.minimum": "(80, 20)"}}], "labels": [{"id": "d6df7847-defd-48cc-9d4e-13ec036c37a2", "text": "Behavior", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_TOP INSIDE"}, "width": 47.609371185302734}, {"id": "457530c6-f875-44ff-b877-88bef903bdcd", "text": " ", "height": 0.0, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_LEFT V_CENTER INSIDE"}, "width": 0.0}], "layoutOptions": {"org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN", "org.eclipse.elk.padding": "[top=0.0,bottom=0.0,left=0.0,right=0.0]", "org.eclipse.elk.spacing.nodeNode": "0.0", "org.eclipse.elk.edge.edgeNode": "0.0", "org.eclipse.elk.aspectRatio": "100.0", "org.eclipse.elk.expandNodes": "true", "org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE", "org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.spacing.componentComponent": "0.0", "org.eclipse.elk.nodeSize.minimum": "(220, 20)"}}], "labels": [], "layoutOptions": {"org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN", "org.eclipse.elk.padding": "[top=0.0,bottom=0.0,left=0.0,right=0.0]", "org.eclipse.elk.spacing.nodeNode": "0.0", "org.eclipse.elk.edge.edgeNode": "0.0", "org.eclipse.elk.aspectRatio": "100.0", "org.eclipse.elk.expandNodes": "true", "org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE", "org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.spacing.componentComponent": "0.0"}}, {"id": "9306a0b1-caf6-4ff9-8a9a-3d7b6074cf45", "children": [{"id": "10e28850-df81-4d30-8d02-65d1e450164c", "children": [], "labels": [{"id": "5591364c-dfd6-4395-ac65-f9b8b77e6637", "text": "Wheel", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 34.124996185302734}, {"id": "1a445bde-e1ac-4217-a93d-67bee5ec4863", "text": "\\u00abblock\\u00bb", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 41.906246185302734}], "layoutOptions": {"org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN", "org.eclipse.elk.padding": "[top=0.0,bottom=0.0,left=0.0,right=0.0]", "org.eclipse.elk.spacing.nodeNode": "0.0", "org.eclipse.elk.edge.edgeNode": "0.0", "org.eclipse.elk.aspectRatio": "100.0", "org.eclipse.elk.expandNodes": "true", "org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE", "org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.spacing.componentComponent": "0.0", "org.eclipse.elk.nodeSize.minimum": "(180, 20)"}}, {"id": "224b984a-6749-4b3f-8646-2728c5db9e9c", "children": [], "labels": [{"id": "8ab2af23-6f4b-4f0f-bae0-c67bb7a7eb61", "text": "properties", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_TOP INSIDE"}, "width": 53.328125}, {"id": "fa0dc4ef-cd08-4bf6-8d72-3b654b00feff", "text": "- radius: float", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_LEFT V_CENTER INSIDE"}, "width": 69.640625}], "layoutOptions": {"org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN", "org.eclipse.elk.padding": "[top=0.0,bottom=0.0,left=0.0,right=0.0]", "org.eclipse.elk.spacing.nodeNode": "0.0", "org.eclipse.elk.edge.edgeNode": "0.0", "org.eclipse.elk.aspectRatio": "100.0", "org.eclipse.elk.expandNodes": "true", "org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE", "org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.spacing.componentComponent": "0.0", "org.eclipse.elk.nodeSize.minimum": "(180, 20)"}}], "labels": [], "layoutOptions": {"org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN", "org.eclipse.elk.padding": "[top=0.0,bottom=0.0,left=0.0,right=0.0]", "org.eclipse.elk.spacing.nodeNode": "0.0", "org.eclipse.elk.edge.edgeNode": "0.0", "org.eclipse.elk.aspectRatio": "100.0", "org.eclipse.elk.expandNodes": "true", "org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE", "org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.spacing.componentComponent": "0.0"}}, {"id": "5669a675-4e8f-41db-924c-7e71ce69b90d", "children": [{"id": "7423cdad-bcea-413f-9dd0-3babb45d7357", "children": [], "labels": [{"id": "e966f74f-f2ba-4eb9-a090-01900cf60776", "text": "Break", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 31.921875}, {"id": "1bee74d0-5dd2-4026-a0c9-a70c3999514c", "text": "\\u00abblock\\u00bb", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 41.906246185302734}], "layoutOptions": {"org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN", "org.eclipse.elk.padding": "[top=0.0,bottom=0.0,left=0.0,right=0.0]", "org.eclipse.elk.spacing.nodeNode": "0.0", "org.eclipse.elk.edge.edgeNode": "0.0", "org.eclipse.elk.aspectRatio": "100.0", "org.eclipse.elk.expandNodes": "true", "org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE", "org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.spacing.componentComponent": "0.0", "org.eclipse.elk.nodeSize.minimum": "(80, 20)"}}], "labels": [], "layoutOptions": {"org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN", "org.eclipse.elk.padding": "[top=0.0,bottom=0.0,left=0.0,right=0.0]", "org.eclipse.elk.spacing.nodeNode": "0.0", "org.eclipse.elk.edge.edgeNode": "0.0", "org.eclipse.elk.aspectRatio": "100.0", "org.eclipse.elk.expandNodes": "true", "org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE", "org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.spacing.componentComponent": "0.0"}}, {"id": "8e0eff5a-95f6-4142-86ea-3e472233bba1", "children": [{"id": "3f83e205-2e41-48b6-9a9d-07b038d8ccd2", "children": [], "labels": [{"id": "821bbc70-9b33-4224-8395-e59f4b55ef46", "text": "Engine", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 37.109375}, {"id": "7dbd4687-9ca3-4aed-bc31-abab0d49d8ae", "text": "\\u00abblock\\u00bb", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 41.906246185302734}], "layoutOptions": {"org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN", "org.eclipse.elk.padding": "[top=0.0,bottom=0.0,left=0.0,right=0.0]", "org.eclipse.elk.spacing.nodeNode": "0.0", "org.eclipse.elk.edge.edgeNode": "0.0", "org.eclipse.elk.aspectRatio": "100.0", "org.eclipse.elk.expandNodes": "true", "org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE", "org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.spacing.componentComponent": "0.0", "org.eclipse.elk.nodeSize.minimum": "(180, 20)"}}], "labels": [], "layoutOptions": {"org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN", "org.eclipse.elk.padding": "[top=0.0,bottom=0.0,left=0.0,right=0.0]", "org.eclipse.elk.spacing.nodeNode": "0.0", "org.eclipse.elk.edge.edgeNode": "0.0", "org.eclipse.elk.aspectRatio": "100.0", "org.eclipse.elk.expandNodes": "true", "org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE", "org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.spacing.componentComponent": "0.0"}}, {"id": "467abbe6-3999-4551-8673-ee3e9c36ed21", "children": [{"id": "7d42971b-dde5-462e-a6ec-a93e45517cd2", "children": [], "labels": [{"id": "38802c14-7935-4172-aa1c-3ddb756ccb56", "text": "Tire", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 21.375}, {"id": "d3dacafb-d88c-4d87-9ece-86c13adc6ee2", "text": "\\u00abblock\\u00bb", "height": 13.65625, "labels": [], "layoutOptions": {"org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE"}, "width": 41.906246185302734}], "layoutOptions": {"org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN", "org.eclipse.elk.padding": "[top=0.0,bottom=0.0,left=0.0,right=0.0]", "org.eclipse.elk.spacing.nodeNode": "0.0", "org.eclipse.elk.edge.edgeNode": "0.0", "org.eclipse.elk.aspectRatio": "100.0", "org.eclipse.elk.expandNodes": "true", "org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE", "org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.spacing.componentComponent": "0.0", "org.eclipse.elk.nodeSize.minimum": "(80, 20)"}}], "labels": [], "layoutOptions": {"org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN", "org.eclipse.elk.padding": "[top=0.0,bottom=0.0,left=0.0,right=0.0]", "org.eclipse.elk.spacing.nodeNode": "0.0", "org.eclipse.elk.edge.edgeNode": "0.0", "org.eclipse.elk.aspectRatio": "100.0", "org.eclipse.elk.expandNodes": "true", "org.eclipse.elk.nodeLabels.placement": "H_CENTER V_CENTER INSIDE", "org.eclipse.elk.nodeSize.constraints": "NODE_LABELS PORTS PORT_LABELS MINIMUM_SIZE", "org.eclipse.elk.spacing.componentComponent": "0.0"}}, {"id": "4fa3cdd9-9e28-4de5-841d-642209f7d634", "labels": []}], "edges": [{"id": "32f183fa-e07d-45e4-b4da-fae6241cc3ea", "sources": ["93a094ec-1f02-4387-86d4-5efbde162d18"], "targets": ["9306a0b1-caf6-4ff9-8a9a-3d7b6074cf45"]}, {"id": "96be54cd-eed5-47ce-a011-eed4dff2845a", "sources": ["93a094ec-1f02-4387-86d4-5efbde162d18"], "targets": ["8e0eff5a-95f6-4142-86ea-3e472233bba1"]}, {"id": "c830087a-5c37-4d47-96a0-f057f58d7d18", "sources": ["9306a0b1-caf6-4ff9-8a9a-3d7b6074cf45"], "targets": ["5669a675-4e8f-41db-924c-7e71ce69b90d"]}, {"id": "ac7cd656-e128-4744-a1b6-d0d6b4a782b9", "sources": ["9306a0b1-caf6-4ff9-8a9a-3d7b6074cf45"], "targets": ["467abbe6-3999-4551-8673-ee3e9c36ed21"]}], "layoutOptions": {"org.eclipse.elk.direction": "RIGHT", "org.eclipse.elk.hierarchyHandling": "INCLUDE_CHILDREN"}, "labels": [{"id": "139802404279792", "text": ""}]}

</details>
