### ISSUE TITLE
In Hierarchical layout 'INCLUDE_CHILDREN', edges not placed properly

### ISSUE THREAD

**Issue by Parul100** [kieler/elkjs#112]
I am trying to draw a lineage diagram using elk.js and d3. Using the following layout:
id: 'root',
layoutOptions: {
	'elk.algorithm': 'layered’,
	'elk.direction': 'RIGHT’,
	'elk.hierarchyHandling': 'INCLUDE_CHILDREN’
},
children: graph.nodes,
edges: graph.edges

The result through the above layout is in below image:
![image](https://user-images.githubusercontent.com/76549607/103268053-d7f73c80-49d8-11eb-9520-60df46603aea.png)
 
**Issue:**
When connecting child edges, I want all the child nodes inside parent nodes to be at a fixed position. i.e. in straight line. Elk is moving the node as per the edges as shown in the above image.
Below is the image to show the expected result:
![image](https://user-images.githubusercontent.com/76549607/103268164-1260d980-49d9-11eb-9577-4c9702c749fd.png)

**Comment by uruuru** [comment]
Do I understand correctly, that you want all inner nodes within a parent to have the same (global) x coordinate?

Which version are you using? There was an issue in 0.6.0 that would explain the behavior you see: change the layout version in [this example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAjHsFAMYJYASwAdgSDA2OgJIByAwgDIBVACIBRAPo9aHPkIBKIrkQYQCONAwCMAbyJo96lWpgbd+5arQwATEQC+Sw+qtod+gxZgBmU3vNGALHZEhGBqmgB0xmgAtAB8TpH+QA) to 0.6.0.

**Comment by Parul100** [comment]
Now, I am using latest version of elkjs -0.7.0
import ELK from 'elkjs/lib/elk-api';
const elk = new ELK({
workerUrl: './elk-worker-min.js'
})
Its giving error as below:
Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Worker': () => { } could not be cloned.
Error: Failed to execute 'postMessage' on 'Worker': () => { } could not be cloned.
<img width="944" alt="Error" src="https://user-images.githubusercontent.com/76549607/103345504-94273480-4ab7-11eb-9573-530166ee5971.PNG">

**Comment by uruuru** [comment]
Latest should be 0.7.1. Anyway, I haven't seen this before. 

I'm not familiar with the `ZoneAwarePromise` that occurs in your stacktrace. Apart from that the worker threads have been exchanged between 0.6.x and 0.7.x, see [comment here](https://github.com/kieler/elkjs/releases/tag/0.7.0).

Maybe it's connected to the combination?

**Comment by Parul100** [comment]
Thanks for the solution. That issue was resolved.
Now, I am facing a different issue when I am trying to draw edge from 3rd level of one node to 3rd level of other node, the edges fall short.
<img width="138" alt="111" src="https://user-images.githubusercontent.com/76549607/104169694-f708bc00-5425-11eb-9f96-0672109bfd6e.PNG">

Is there any elk spacing property for portEdge that could solve this issue?

**Comment by uruuru** [comment]
I believe you refer to the (almost invisible on my screen) yellow edge? 

It's hard to tell without a (minimal) example but in general edges should not stop in the middle of nowhere.

**Comment by markobilanovic** [comment]
@Parul100 
Have you managed to set children nodes to fixed position and to have edges connecting from one child node to another (that have different parent nodes) ?
I am currently trying to create such diagram but if I use combination of 'layered' and 'fixed' algorithm I get an error:

`Error: org.eclipse.elk.core.UnsupportedGraphException: The source or the target of edge ElkEdge "7" ElkNode "P1" (12,12 | 70,30) -> ElkNode "P11" (0,0 | 70,30) could not be found. This usually happens when an edge connects a node laid out by ELK Layered to a node in another level of hierarchy laid out by either another instance of ELK Layered or another layout algorithm alltogether. The former can be solved by setting the hierarchyHandling option to INCLUDE_CHILDREN.`

is there any workaround for this?

**Comment by uruuru** [comment]
@markobilanovic edges with different parents are not supported when mixing layout algorithms. They are in fact only supported by `layered`. 
A workaround is to use [_hierarchical ports_](https://www.eclipse.org/elk/documentation/tooldevelopers/graphdatastructure.html).
