### ISSUE TITLE
vertical order

### ISSUE THREAD

**Issue by ahoyahoy** [kieler/elkjs#114]
Hello,
I can't figure out how to set a fixed order for nodes that are in the same partition (partition 2).
With each reloads the order of the 3 middle nodes changes.
I need to keep "Query /" all the way up.
Thanks

[demo link](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAM44AOwUwcOAwhAHaM4DGtBDS5TOjcJdHCgBXHGgD0EtIhgk0ctMHYjQILDITiCOAGbARIOGgBuoMaUqsYjMADpWEbr35ceLfugCMABh9FKKDh4GCYbe2Vgs1ohURxLZXC7RggdADlUnAAhHDgAdxw+ABlsPEE0X38SKyTCMBwMnXQAZiqa2zs6hsyc-MLGEtwocoAWNsSOroBRAnrvSWkWExgkNEc0HUw0BOtJ2ZwZ+t6C4tLh9ABWBbhgAg1gEhg0RhhWInfWKAgSR9sAWRsKxgAC8aKFGHYyEgYABJfh4SIwEw4WIWIhSB7kNhwABKYIg6B8di8CzQAHlGOo0LpoGhyPgyPx8Yw6SIoDwyCQiCkdGgAIoAVSmOIAmmgAN5ENDSjDYCAiYwAbTQj2BKLQACYNT4ADSai4ANjQAF0pTKeEEGIwSMJgDYBOgAGIwgAaUwAIgB9AAKZIAymbpYFgsEmOgNYHZQAjHAgNAAIj5YigGgk8feMrp0GMNhJkszmcwWHlSqzj1DjEJeoAHD4TZHMwA9C1wSEwJpoADqUz9ABUGzKbDoAB6EyMAX0jLYUjA1EoH0qLJbQyo5ITDaF1FS8c9NBZlzezbY73b7E6n2ZnzXn+8XcoVK7L68rm71XhGI3rt7Qh6Cx-Vp79pmk6ZtONifvmt5Lg+q7fM+VYVAA7Eae63r+raPCePZATKk4XkEaAlnmC6ysWMFPhWCG1l+aEtv+6BTAAgmewH4cYJZzpB+7QaWa6Ua+267iR6H0WgTEsbhbGEQq15cQWPGPnx4IIe+n6ofuImYeq4k4dKIHmpeJYQSRCmweWykCV4yE0RpdFaQxzG6Wgk54Ty4iCsKIqcZGpkqiC6paluXgGnW6lZpaTA2tQ9rlM6bper6AagVQIYWRGhbADGcaJsmqYgHIcDplJuY3lB968XB-FbtRYVNnZ7YAdhJFDjgo6aueUlEaV3HlYplUWdVoXCfVHY6eermZPyQqirJPm9cqqoBdqb4hTZ4VwFaUV2vwsWuh6Pr+lOKXwe1GVZQmSZ4KmjxgIwRWgZeJVyRlZEVeZG6DWtdVHvZXZNd+LVtc0HUPQRXXPTKvlKR9NZDd+mkNQ5El6UQeHolIGB6MYWloAAFMGz4VAAlO8bloAA4rk3WkcuC3+eGy0VFqa0tpttoxU6e0JYdyVBCdXhzed8aU4VkZSTCaTUy9tMURZlR6nDtE-YjaBpGSOK9gAEuNpOTd63zGHJvmLQzQXM2FrORezO2c-FB1Jeax38QLZ2xgm+s2ummbi5LEN3q9fXvS+8ubl9B4jeqasa9rrGdQqxHflD-Uw2gq21eHyujY5OvcpN7o0MA1PG-TmqMzuQmgxtVvRTbaBxftiVHXzzuC278b5zcXsyj7UuQ-NssbiHiu2Znkfq1rIMGWD8e9-7MvQy+W5p8No9I05LnvJvGOwGACDYw1eMExWaDNCTue8n8mRxkb-cm5qfh6lqanShjiFoNQBAANYiGgABUJ9zgALylxGGxNmNcHR1y5vbJuqUNzA1dtlS+mx7pT2MBLWeNNyIL28A-UO6dpQIw7FHCesdK7STgAnMqAczInTNhXJWf5fpjVYmjMmWQYBBAQN6TArBxA3xoX5NU4Y8E7mrCaF+0hPwf0-hof+zQgFM2rGA6u21IH1y9H6GE7opiwJOggvuQsOFBB4coHAqCgyXgweKH8Ed0AkM1s5d4aNN5dCmp5OwXUAC0AA+NAyDYx2AlkQNxHlRSeIVHOXx-ir5BLSCE-Y7jwklmvNEgJIA4kJPqEkkUES4CfjSbE4JoTppeTySSQpmxMklM8s0cpaBKmBOCVk8Q6T6nROMYgUxfDMktJyXYEq0SRbVMSWE3JNgol+I9q2YpozSkagGYwCpfiO7AF6W46Z7S-FtNmdk1ZWyYlVIlkAA)

**Comment by uruuru** [comment]
Maybe the example on [semi-interactive crossing minimization](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=user-hints%2Flayered%2FverticalOrder) helps?
