### ISSUE TITLE
Issues Upgrading from v0.6.2 to v0.7.1

### ISSUE THREAD

**Issue by JHERR1112** [kieler/elkjs#115]
Hi,

I have upgraded the elk.js package from version 0.6.2 to 0.7.1 with no changes in my code and I am now getting the following error: 
**ERROR Error: Uncaught (In promise): ReferenceError: ReferenceError: g is not defined**

I switched to debugger mode to see if I could get more context into why I was receiving this error and then received the following error: **ERROR Error: Uncaught (In promise): ReferenceError: _xblockexpression is not defined**

This did not offer me any insight to why I 'm receiving this error and I have not made any changes to the code or the incoming data.  Any idea why I am getting this error and how to resolve this issue?

Thank you in advance

**Comment by uruuru** [comment]
Thanks for reporting this. 

Sounds similar to #96. Could you have a look if the points mentioned there help?
