### ISSUE TITLE
How to change Edge Label text orientation and space between the label and the edge in ELK Json?

### ISSUE THREAD

**Issue by com-nvidia-yohuang** [kieler/elkjs#117]
I did not find layoutOptions to control the orientation for edge labels. Besides, it seems layoutOptions mentioned in https://www.eclipse.org/elk/reference/options/org-eclipse-elk-edgeLabels-placement.html has no impact on the rendering.

e.g.,

layoutOptions: {
  "elk.edgeLabels.inline": true   // no difference when set to false
}

I doubt whether elkjs supports the same functionality as eclipse ELK.

thanks!

**Comment by uruuru** [comment]
It's not clear from you description but as specified in the _Applies To:_ row of the table in your link, you have to set the option for the label (not the overall graph). 

Apart from that, there's no option to change the actual _orientation_, e.g. rotate a label or have the letters stacked vertically. 

elkjs has the same capabilities as Java-based ELK.

**Comment by com-nvidia-yohuang** [comment]
Thanks. I am using elkjs with sprotty, and am able to tune the edge label position/orientation with sprotty vnode postprocessor.
