### ISSUE TITLE
[question] Individual Spacing

### ISSUE THREAD

**Issue by amcdnl** [kieler/elkjs#123]
In the docs there is a section for individual spacing ( https://dagobertgans.github.io/docgen/_pages/org-eclipse-elk-spacing-individualOverride ) however its not clear how to implement it.

Take the following graph, how would I make the first edge shorter than all the other edges?

![image](https://user-images.githubusercontent.com/227909/107513097-bc558900-6b75-11eb-81b0-4ab45234338e.png)

I was trying something like:

```ts
{
   children: [
       {
             id: 'blah',
            layoutOptions: {
                'elk.spacing.individual.spacing': '50'
            }
       }
   ]
}
```

but that doesn't seem to work. Thanks in advanced.

**Comment by uruuru** [comment]
Please try not do use the "dagobertgans" documentation. It's a student's old test environment and is not updated. Docs are [here](https://www.eclipse.org/elk/reference.html).

Apart from the fact that the concept of individual spacings is poorly documented at this point, it is not neccessarily implemented for every option and at times hard to configure. 


Consider this example:
```
algorithm: layered

node parent1 {
    spacing.nodeNodeBetweenLayers: 40

    node n1 {
        spacing.individual: "spacing.nodeNodeBetweenLayers: 10"
    }
    node n2 {
        spacing.individual: "spacing.nodeNodeBetweenLayers: 10"
    }
    node n3

    edge n1 -> n2
    edge n2 -> n3
}

node parent2 {
    aspectRatio: 2
    spacing.nodeNode: 40
    separateConnectedComponents: false
    node n4 {
        spacing.individual: "spacing.nodeNode: 10"
    }
    node n5 {
        spacing.individual: "spacing.nodeNode: 10"
    }

    node n6
}
```
![image](https://user-images.githubusercontent.com/7552459/107566830-a089cb80-6be5-11eb-9225-401d0db010aa.png)

Conceptually, in both cases the distance between a pair of nodes should be reduced to `10` instead of `40`. It has to be configured for both involved nodes (as internally the max will be chosen). However, it only works for the vertical separation, not the horizontal one. Why? Likely because it hasn't been incorporated at that part of the code. 

Further note, that due to the underlying methodology it's not possible to specify the desired length of edges but only separation between underlying _layers_. As such, as soon as another (potentially wider) node ends up in the first layer of your diagram, you can likely tweak the individual spacing values as much as you want - the result won't be what you desire.

**Comment by amcdnl** [comment]
@uruuru - Got it - the needing to apply it to both nodes is what caused me the issue. 

In this case this would work as expected because I do want all first nodes to have a shorter length. In this diagram, I want the edges coming from the + to all next nodes to be shorter:

![image](https://user-images.githubusercontent.com/227909/107568678-5852b500-6bb5-11eb-9b20-9c025eac3470.png)

In that example, what would the actual JSON input look like as it would be represented here? https://rtsys.informatik.uni-kiel.de/elklive/json.html

**Comment by uruuru** [comment]
You can convert elkt<->json here (doesn't work always but often :)): https://rtsys.informatik.uni-kiel.de/elklive/conversion.html

But as mentioned, the case you want doesn't work as individual spacings are not evaluated. For reference:

https://github.com/eclipse/elk/blob/cbbf20836426ee6c0e83ef876fd6a880f2cae6f5/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/OrthogonalEdgeRouter.java#L216-L217

https://github.com/eclipse/elk/blob/cbbf20836426ee6c0e83ef876fd6a880f2cae6f5/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p5edges/OrthogonalEdgeRouter.java#L279

```
{
  "id": "n0",
  "children": [
    {
      "id": "parent1",
      "children": [
        {
          "id": "n1",
          "layoutOptions": {},
          "individualSpacings": {
            "spacing.nodeNodeBetweenLayers": "10.0"
          }
        },
        {
          "id": "n2",
          "layoutOptions": {},
          "individualSpacings": {
            "spacing.nodeNodeBetweenLayers": "10.0"
          }
        },
        {
          "id": "n3"
        }
      ],
      "layoutOptions": {
        "spacing.nodeNodeBetweenLayers": "40.0"
      },
      "edges": [
        {
          "id": "e0",
          "sources": [
            "n1"
          ],
          "targets": [
            "n2"
          ]
        },
        {
          "id": "e1",
          "sources": [
            "n2"
          ],
          "targets": [
            "n3"
          ]
        }
      ]
    }
  ]
}
```

**Comment by moklick** [comment]
I am also struggling with different spacing between layers. It seems that it is not possible to define a individual spacing for a layer. This is my elk config: 

```js 
{
  id: "root",
  layoutOptions: {
    'algorithm': 'layered',
    'elk.layered.nodePlacement.strategy': 'SIMPLE',
    'spacing.nodeNodeBetweenLayers': 100,
    'elk.direction': 'DOWN'
  },
  children: [
    { id: "n1", width: 30, height: 30, individualSpacings: { 'spacing.nodeNodeBetweenLayers': 10 }},
    { id: "n2", width: 30, height: 30, individualSpacings: { 'spacing.nodeNodeBetweenLayers': 10 }},
    { id: "n3", width: 30, height: 30, individualSpacings: { 'spacing.nodeNodeBetweenLayers': 10 }},
    { id: "n4", width: 30, height: 30},
    { id: "n5", width: 30, height: 30}
  ],
  edges: [
    { id: "e1", sources: [ "n1" ], targets: [ "n2" ] },
    { id: "e2", sources: [ "n1" ], targets: [ "n3" ] },
    { id: "e3", sources: [ "n2" ], targets: [ "n4" ] },
    { id: "e4", sources: [ "n2" ], targets: [ "n5" ] }
  ]
}
```

it produces this graph:

<img width="306" alt="Screenshot 2021-02-10 at 22 00 48" src="https://user-images.githubusercontent.com/2857535/107571618-720eef00-6beb-11eb-8888-40e25c4fb383.png">

When I understand it correctly the spacing between n1 -> n2, n1 -> n3 should be 10 but it is 100 (the parents `nodeNodeBetweenLayers` value). 

You can find the ELK live demo [here](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAOQF4DmKSk6ABYBbdvHaEiAUyRTo7HGzDspeANYA6STLkb6KaFIAKhAMZThU+ug2N0SAuinciY5QGUAkgFkjAGQBRBVwORioCU0h6bj0DKQA5OIAhKXQAdykrP2IZRjcARgAGQsU2FXUNaEhZU1oGN3YAEQoAdXj2XABfUtNBSDxoWXp4AG0QsGAoOER6fOwwNJgheABmErBBKUhuQXRV9aiqgDcYUi53cMjo5gnlMIiomP1DRMMU9Mz6bOkkPPgisCdbrjSYweAIegAJnmi2gyzAaywGy2Oz2CIO9GOp3Ol0eN0m7HuVyecVeUneGSyOV+BUKgOBSlB0whKxhS0E+yRm22u05UExkBO0DOeAuD2uLDuuOisReyVSlK+1L+YABQNKECZ4PoABY2XCOeiuSjeeiGWwtTMAKz6+GI5E8tFrTq4AC6pTk3CkNzGjKm4KkcyRjDISHMPpmczA7rA6AISC96AjEOh0cBGtuYMQUmhwdD4dGkYQ0aRcYTqWT9FZafNmv92dZedIYe9hZTxZjZcTlb1NYzloQUj1TZbldTnfj3bb9BtNbdIE6QA)

**Comment by uruuru** [comment]
@moklick from a first look, yes, that seems to be the case I mention above.
