### ISSUE TITLE
Node layering strategies - Are there examples/demos?

### ISSUE THREAD

**Issue by Vadorequest** [kieler/elkjs#124]
I stumbled upon https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-layering-strategy.html and I understand there are several strategies available:

- NETWORK_SIMPLEX
- LONGEST_PATH
- COFFMAN_GRAHAM (@AdvancedPropertyValue)
- INTERACTIVE (@AdvancedPropertyValue)
- STRETCH_WIDTH (@ExperimentalPropertyValue)
- MIN_WIDTH (@ExperimentalPropertyValue)

Are there any example/demo to make sense of them? (Also, if there is, would be great to add a link to it from the documentation page!)

**Comment by uruuru** [comment]
To my knowledge, there aren't. Some details can usually be found in the [class's javadoc](https://github.com/eclipse/elk/tree/master/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/p2layers). 

Feel free to play around with the options and [propose an example](https://github.com/eclipse/elk-models/tree/master/examples).
