### ISSUE TITLE
Multi-edge converging issue

### ISSUE THREAD

**Issue by caravinden** [kieler/elkjs#125]
I have a scenario which contain multiple edge connecting between the nodes. With my current implementation, Its difficult to identify the starting and ending of the edge due to directional flows. Please find the screenshot below. 
Image contain rigid line that what we are getting currently. I will be expecting something similar to dashed line. @uruuru 

Is there any way to differentiate  the edge and uniquely identify the  direction? Any help really appreciated
![image](https://user-images.githubusercontent.com/5152392/108017056-fe7d3f80-7039-11eb-9969-7be03c1a9a9e.png)

**Comment by uruuru** [comment]
Did you set `mergeEdges: true`? Or do you use a single port per node that you attach the edges to? 

If you do neither of these two points, the edges should be routed in a distinguishable fashion.
