### ISSUE TITLE
Interactive layering strategy - demos, examples?

### ISSUE THREAD

**Issue by kapilkaisare** [kieler/elkjs#126]
Is there a demo or an example of how I might use elkjs using an interactive layering strategy? I am trying to add nodes incrementally to a graph and and am unable to figure out how I might do so.

**Comment by uruuru** [comment]
See the example on [horizontal ordering](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=user-hints%2Flayered%2FhorizontalOrder) and maybe the other examples in the _user-hints_ section.
