### ISSUE TITLE
How to influence label and edge positioning based on font-size and padding?

### ISSUE THREAD

**Issue by gfox1984** [kieler/elkjs#128]
I am planning to apply padding around my labels as well as using a custom font-size to render them with this style:

![image](https://user-images.githubusercontent.com/14998184/112446477-8862ab80-8d50-11eb-81fc-bb6d5fe0461e.png).

How can I influence Elk to take into account the bigger font-size and padding when laying out the edges and labels?

**Comment by uruuru** [comment]
ELK does not know about font size and style. Thus, you'd have to figure out the dimensions yourself, add padding values and specify that as the width and height of the label you pass to the layouter.

**Comment by gfox1984** [comment]
Thanks I'll place with the width of the labels then.

Just out of curiosity, what part of the algorithm estimates the size of text? Is there any variable exposed to control that?

**Comment by uruuru** [comment]
Nothing in elk is able to estimate text size. You'll have to consult whatever you use for rendering :).

**Comment by gfox1984** [comment]
OK, I was under the impression that Elk was producing longer edges as I was feeding it longer labels, so somehow it must know than 10 chars is shorter than 100 chars ^^

**Comment by uruuru** [comment]
For the layouter itself that definitely shouldn't be the case. 

In case you looked at the layouts of the elkt version of elk live, there the rendering part actually estimates the text dimensions using browser facilities. 

I'll close this issue. Feel free to comment further if anything is unclear.

**Comment by gfox1984** [comment]
Thanks that makes perfect sense now 👍

**Comment by Jona898** [comment]
If you work with SVG you can use [SVGGraphicsElement.getBBox()](https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement/getBBox) on any Element to get it's bounding Box.
