### ISSUE TITLE
Optimize Graph Space Utilization

### ISSUE THREAD

**Issue by JHERR1112** [kieler/elkjs#132]
So I was wondering if there is any way to optimize graph space utilization.  

![elk-space-usage-optimization](https://user-images.githubusercontent.com/50001362/115329804-7b22bc00-a158-11eb-81ff-74e705e6d838.jpg)

As you see above, I'm rendering a graph, but I would like it to stay within the bounds represented by the red box.  I've seen similar issues raised in the past, but there was no concrete solution at the time.  Was wondering if anything has changed? I tried using `aspectRatio`, but it really doesn't seem to change the behavior of the graph's layout.  Attaching my graph's layout options for reference below

![elk-config](https://user-images.githubusercontent.com/50001362/115330264-4ebb6f80-a159-11eb-9972-4002e2049b01.jpg)
.  Not sure if I'm using correctly, or if any of my other configurations are causing some sort of conflict.

**Comment by uruuru** [comment]
In the general case, it's rather hard to enforce a layout of a certain aspect ratio and dimension. Hence, applying a scaling factor during rendering, i.e. making everything smaller, is usually the way to go.
