### ISSUE TITLE
Incorrect edge label placement for parent nodes

### ISSUE THREAD

**Issue by slushy-chivalry** [kieler/elkjs#138]
Given the following graph

```
{
  "id": "/root",
  "layoutOptions": {
    "elk.algorithm": "layered",
    "elk.direction": "RIGHT",
    "elk.hierarchyHandling": "INCLUDE_CHILDREN",
    "elk.core.options.EdgeRouting": "ORTHOGONAL",
    "elk.padding": "[top=25,left=25,bottom=25,right=25]"
  },
  "children": [
    {
      "id": "Hello",
      "layoutOptions": {
        "elk.padding": "[top=50,left=50,bottom=50,right=50]",
        "elk.nodeLabels.placement": "[H_LEFT, V_TOP, INSIDE]",
        "elk.hierarchyHandling": "INCLUDE_CHILDREN"
      },
      "labels": [
        {
          "text": "Hello",
          "height": 22,
          "width": 49
        }
      ],
      "height": 1,
      "width": 1,
      "kind": "group",
      "children": [
        {
          "id": "Test3",
          "layoutOptions": {
            "elk.nodeLabels.placement": "[H_CENTER, V_BOTTOM, OUTSIDE]",
            "elk.hierarchyHandling": "INCLUDE_CHILDREN"
          },
          "labels": [
            {
              "text": "Test3",
              "height": 22,
              "width": 49
            }
          ],
          "width": 129,
          "height": 52
        },
        {
          "id": "Test4",
          "layoutOptions": {
            "elk.nodeLabels.placement": "[H_CENTER, V_BOTTOM, OUTSIDE]",
            "elk.hierarchyHandling": "INCLUDE_CHILDREN"
          },
          "labels": [
            {
              "text": "Test4",
              "height": 22,
              "width": 49
            }
          ],
          "width": 129,
          "height": 52
        }
      ]
    },
    {
      "id": "Test1",
      "layoutOptions": {
        "elk.nodeLabels.placement": "[H_CENTER, V_BOTTOM, OUTSIDE]",
        "elk.hierarchyHandling": "INCLUDE_CHILDREN"
      },
      "labels": [
        {
          "text": "Test1",
          "height": 22,
          "width": 49
        }
      ],
      "width": 129,
      "height": 52
    },
    {
      "id": "Test2",
      "layoutOptions": {
        "elk.nodeLabels.placement": "[H_CENTER, V_BOTTOM, OUTSIDE]",
        "elk.hierarchyHandling": "INCLUDE_CHILDREN"
      },
      "labels": [
        {
          "text": "Test2",
          "height": 22,
          "width": 49
        }
      ],
      "width": 129,
      "height": 52
    }
  ],
  "edges": [
    {
      "id": "Test1/Test2",
      "labels": [
        {
          "text": "Check",
          "layoutOptions": {
            "elk.edgeLabels.placement": "CENTER"
          },
          "height": 22,
          "width": 49
        }
      ],
      "sources": [
        "Test1"
      ],
      "targets": [
        "Test2"
      ]
    },
    {
      "id": "Test3/Test4",
      "labels": [
        {
          "text": "Check",
          "layoutOptions": {
            "elk.edgeLabels.placement": "CENTER"
          },
          "height": 22,
          "width": 49
        }
      ],
      "sources": [
        "Test3"
      ],
      "targets": [
        "Test4"
      ]
    }
  ]
}
```

Notice how the layout algorithm produces strange edge / edge label placement for edges that are inside inner nodes with children

![image](https://user-images.githubusercontent.com/52050643/122712215-90d46080-d231-11eb-8bc3-e9d73cfc6e14.png)

I've used http://rtsys.informatik.uni-kiel.de/elklive/json.html to validate the errors. Strangely enough, when using elkjs directly, the edge labels are ignored completely (remain at (0,0)). What could be the problem here? Thanks!

**Comment by uruuru** [comment]
The `Check` edge has to be placed into a different containment, [like so](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGBECWAmkC4oHoBOB7dAXSAacUANgIYCe6ArlgPIAOW06AdgM6JigQSQCmhA1gDpihAObpU0LAAsAtu0glSPVD3j4uUPkNjRVAYwbMFAJQCSAcQASAFTwFu2wdOgriqfdNJXiTWIWgmUQUzADkAYQAZAFUAEQBRAH1wqzNI2JN40PtNXgFBfQkeQXR6RlZBeNhRHhNKBiCFahMbK2oLalCAQUicrjyhWmJYXUakSABtLFKAXgAmAFZcQh4AMyx5pYAjbGnZTdxJUWkNxYBdSAIAXw0oT2hCWFUmdgmHDnfuOAUrPkJ0Pq5JT1OhGVjsTiafpOIYjQLBcZTWYLAAMyzWG1RuB2WD2MyxRxO+JRF1uUK0+SY6FgPEixC2fBYgloJH0PFkPCYOERVkSkXiADEbLgwAA1RI2agABRFYQAymYEqTPtD8i43B4vD4-AExlAwlE4kkUmkMllLuSbirFPTGa8VRBIeTuFgeAAPblQX6Ef6A52QaQ8aDHT1zOZk-0AdzgMnYABYAJwOsBXFVnCPcQPBk7sACMGag0dgsaQ+et-EC8HGogwFFofu490ez3tzo+ba+VagNh4LCwAGYG1CbeQqKDymwkE6OwNBFSaXSGYQmSziGyOVyFBNeeEsjZ4iYReKAELUGySgCyIuo0RsCqVQ-Js-VqHcnm8vn88JCERiCWSqTpJk2TJhAVodkQtrLq2EHtrBLrup6kA9n2g4Fm2AZBiG7BhuhUYxtI8ZJvBqYQemoGFgReZzAmeGZlhOZIAsczJuBzrTk+3zjChWBxo+-TAmOZTMJOcEQbO860lBK6suynJIduyR7geR6JKe57UFeYA3neirxMq8HPq4r6ah+OrfuMBp-sagFmiBEFsRhJBLqJbzwRxM6uh6Cg8XxdHDlm2FILhFG5EWJZgImoUphR5HieFhGljR-mYdmnrMaxaYitaag1K5yYeTAXbIb2A7IL5Q42i5MHkh5uReUh4SBvo-D8dwgk0MJ4JTtFs65VJLnMrJG6NcpJgWh2jn+oFjFgCF8VUUgUVtqRUJxcOLCUB4vY1cOPGDll1pYO4NRYPlGEVWm7yrZoZzXRGhVcd2pW5pVHXjiJELJhJ1IDYyQ1rnJm48kpoT7oeYpqWel7Xre976fxRkau+2pfnqkBWUaAGmsBE2aFN7XSbtmh1f0DU+S9bVQDNobhhRkAJURmXkutYWLWAubJdaNPsBl+MPdaT0lX2cxvWQIJdaJpM-Qu0kA+u8lbjuY2qepMPaXDekGf6Tgvm+WqfrqCL6r+WMmkB5oqgTkHVUgbnsfT5PcaVospTzwV0wtxaJZFxHOjdXCs-0jNJbR3MMelLH8wQ628NUO12+8j3FTxublS7Yu22A9u1Y7iEKE1PAtVTI4S2CUu9U4-WLv9q4K8DUC7mDB54-7bsRzhnsziHvvM2tBaQJtFDbed-qp63EBBy6J08GdxP9DxotXfjMcgFcQA). 

Details are here: [_Edge Containment_](https://www.eclipse.org/elk/documentation/tooldevelopers/graphdatastructure.html).
