### ISSUE TITLE
Non-optimal edge routing

### ISSUE THREAD

**Issue by BjBe82** [kieler/elkjs#139]
Is there a way to avoid the "non-optimal" edge routing as shown below?

![grafik](https://user-images.githubusercontent.com/61700870/122887787-84d7c400-d341-11eb-9906-9a4100bf67a0.png)

or

![grafik](https://user-images.githubusercontent.com/61700870/122887979-afc21800-d341-11eb-9d74-920f2f049b4e.png)

Example Data for https://rtsys.informatik.uni-kiel.de/elklive/json.html to reproduce this:

[ELK JSON.zip](https://github.com/kieler/elkjs/files/6692448/ELK.JSON.zip)

**Comment by spoenemann** [comment]
Thanks for the examples! Please submit these to https://github.com/eclipse/elk/issues as that's where the actual algorithms are implemented. This repository just provides a translation to JS.

**Comment by BjBe82** [comment]
Thanks for the response I created an Issue here: https://github.com/eclipse/elk/issues/766
