### ISSUE TITLE
How does wrapping work?

### ISSUE THREAD

**Issue by alexandercrichton** [kieler/elkjs#140]
Hi

Thanks for all the work on this project. However, as others have pointed out, the API is practically impenetrable. I'd really appreciate any guidance on how to get wrapping to work. I'm trying to get a layered graph to auto-fit into an aspect ratio. At least, I think that's what I need.

I would have thought that a layout like this:
![image](https://user-images.githubusercontent.com/3139645/122924795-7fae5f80-d3a9-11eb-80d2-da8489f204cd.png)

Would try to fit inside the aspect ratio (which is just a 1:1 box in this case), e.g. something like this:
![image](https://user-images.githubusercontent.com/3139645/122925073-d3b94400-d3a9-11eb-98af-9cf5fa24f877.png)

[Here's the example model](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUDiANYB0BM+AxnDBAHboAiA8gOoByRwAzgAcc9AErAGEdAEYiAdyjBBgmEzAV+cRXBxgs6ALIBVADIAVAJIB9AKKsA4jfmLlq9bQCucBmo1aJuvpoAIKirEQRTBAEOGhMslExcQBMRImxTADMadEZACw5SUwArIUZAGxlcQDsVUwAHHUAnBGEYBnSaAC0AHwpJATtcZ29cdltHd19TAUTw1NxpXPxC0yVyyPTtRurjTujTE1AA)

If that's not what wrapping does then please let me know. If there's some other way to achieve something along those lines I'd love to hear it.

I've looked extensively in this repo and the elk repo for guidance. I found some related issues but haven't managed to get it working for my case
https://github.com/kieler/elkjs/issues/10
https://github.com/kieler/elkjs/issues/12
https://github.com/eclipse/elk/issues/123

Thanks in advance

**Comment by uruuru** [comment]
Wrapping is actually for the opposite case: very elongated graphs. 

In your case you could try [coffman graham layering](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUDiANYB0BM+AxnDBAHboAiA8gOoByRwAzgAcc9AErAGEdAEYimXLCZgK-OFAk4wWdAGF2AMX0BZAILcA+gHFRJgBImjc7HhhKKtCADNPSYE0vqCMBIFPJ4AEIQAK5MBOgATERJTBAEOGhMsilpGYnZ6UwAzET5GQAsJakFAKyVOUwAbHUFAOzNGQAc7UwAnEmEYAXSaAC0AHy5JASDGcPjGcUDQ6MTTBVLsysZtRuZW41TM3vzTG27c6td5-s9QA).
![image](https://user-images.githubusercontent.com/7552459/125839369-df219008-8cd0-44c2-ac9e-e7a364f3f282.png)

**Comment by alexandercrichton** [comment]
Thanks @uruuru. 

Here's a more concrete example of what I'm talking about. Notice the nodes in group 3 how they're staggered
![image](https://user-images.githubusercontent.com/3139645/125872779-8fdcb4d2-dfb4-45e4-b65e-38f2db2c600f.png)

I did have a look at coffman graham, but it doesn't quite fit the requirements. Here I've tried it out:
![image](https://user-images.githubusercontent.com/3139645/125873359-8f0a3ef0-b6f0-41a4-a806-0badcc22ec6b.png)

The first group of four looks great, but not the second group. Maybe if you can 
1. Apply the strategy within a group of nodes, so that nodes from other groups aren't pushed onto different levels, and
2. Ensure the nodes are ordered such that they're staggered consistently
then it would probably do it. But, I suspect that's either not possible, or maybe as involved as just laying things out manually.

Thanks again!

**Comment by uruuru** [comment]
You could have a look at [user-hint examples](http://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=user-hints%2Flayered%2FverticalOrder). 

But at a certain point you're likely here:
> or maybe as involved as just laying things out manually.
