### ISSUE TITLE
Disabling feedback edges when using INCLUDE_CHILDREN hierarchy handling 

### ISSUE THREAD

**Issue by mdbaehre** [kieler/elkjs#146]
Is there a way to disable feedback edges for cross-hierarchy edges when using INCLUDE_CHILDREN hierarchy handling?  I have sets of child nodes that I have grouped by assigning them to a parent node.  The edges among the child nodes within a single parent are routed directly between the nodes (feedback = false) but edges between children of different parents are always routed around the child nodes with inputs on the left and outputs on the right (e.g. feedback = true).  I've tried setting the feedbackEdges layout option to false for each parent node - that hasn't fixed it.

**Comment by uruuru** [comment]
Could you share a screenshot?

**Comment by mdbaehre** [comment]
![GroupedNodesExample](https://user-images.githubusercontent.com/47833105/132952503-9002833b-c122-47c0-a2b9-65ce03524dae.JPG)
The code is:
node ungrouped {
    algorithm: layered
    nodeLabels.placement: "INSIDE V_TOP H_CENTER"
    label "Ungrouped"
    node n1 {label "1"}
    node n2 { label "2" }
    node n3 { label "3" }
    edge n1 -> n2
    edge n2 -> n1
    edge n1 -> n3
    edge n3 -> n1
}
node grouped {
    algorithm: layered
    feedbackEdges: false
    edgeRouting: ORTHOGONAL
    hierarchyHandling: INCLUDE_CHILDREN
    nodeLabels.placement: "INSIDE V_TOP H_CENTER"
    partitioning.activate: true
    label "Grouped"
    node group1 {
         partitioning.partition: 1
        label "Group1"
        node n1 {label "1"}
    }
    node group2 {
        partitioning.partition: 2
        label "Group2"
        node n2 {label "2" }
        node n3 {label "3" }        
    }
    edge grouped.group1.n1 -> grouped.group2.n2
    edge grouped.group1.n1 -> grouped.group2.n3
    edge grouped.group2.n2 -> grouped.group1.n1
    edge grouped.group2.n3 -> grouped.group1.n1
}

I would like the edges in the "Grouped container" to be routed like those in the "Ungrouped" container

**Comment by uruuru** [comment]
You could try to connect the edges via ports and assign the ports to the a fixed side via port constraints. I'm not sure if it works, in particular if it works as you desire for more than this example graph. 

A word on why the algorithm behaves as you observe: When you introduce the "group" nodes, you introduce hierarchical sub-graphs, which are laid out without knowledge of the surrounding context. I.e. when the _side_ an edge is assigned to is selected, it is unknown where this edge will eventually route to. And the default behavior usually is to place incoming edges on the western side of a node and outgoing edges on the eastern side.

**Comment by uruuru** [comment]
I'll close this. Feel free to reopen if you want to follow up.

**Comment by daviskirk** [comment]
I'd also be interested in finding a solution for this.  Is there an option to change the algorithm so it considers everything "in the same context"?  I would also accept worse node placement within the groups if the edges were more direct?
