### ISSUE TITLE
False positive validation error 

### ISSUE THREAD

**Issue by emil14** [kieler/elkjs#151]
Suppose you have node `n1` with the port `p1` and node `n2` with the same port `p1`

As it turns out it's impossible! You have to rename `p1` to something like `n1_p1` and `n2_p2`

Error found in 0.7.1 version

**Comment by emil14** [comment]
Here's a quick way to check if required port actually exists - my data was passing it so exception is a bug
```js
  console.log(
    edges.every(edge => {
      const f = nodes
        .find(node => node.id == edge.from)
        .ports.some(port => port.id == edge.fromPort)

      const t = nodes
        .find(node => node.id == edge.to)
        .ports.some(port => port.id == edge.toPort)

      return f && t
    })
  )
```

**Comment by uruuru** [comment]
I'm not sure if I understand you correctly. Are you saying that an error reported by mistake?

In the `elkt` format it's actually fine to have multiple ports with the same identifier as it uses node containment as scope. In the json format there's sort of a global scope, which makes it necessary that port id's are globally unique.

**Comment by emil14** [comment]
> Are you saying that an error reported by mistake?

Yes i do

> In the elkt format it's actually fine to have multiple ports with the same identifier as it uses node containment as scope. In the json format there's sort of a global scope, which makes it necessary that port id's are globally unique.

So... You saying it's not a bug? As a user I don't see a reason for such behavior :)

**Comment by uruuru** [comment]
In the [format's description](https://www.eclipse.org/elk/documentation/tooldevelopers/graphdatastructure/jsonformat.html) it states that 

> All elements, except labels, must have an id that _uniquely_ identifies them [...]

I tend to agree that it may feel unnecessary from a user's perspective. However, iirc some parts of the implementation rely on the uniqueness at this point.
