### ISSUE TITLE
Is there any reason this library cannot update to EPL 2.0?

### ISSUE THREAD

**Issue by vinitasher** [kieler/elkjs#155]
We want to use this library for our enterprise application and we were suggested to ask for the library to update to EPL2.0. Is this something which can be done easily? 

We have a PR open https://github.com/kieler/elkjs/pull/154. Let me know if there is anything else that needs to be done to update the license. 

I am not a legal expert by any means.

**Comment by uruuru** [comment]
License migrated in #156.
