### ISSUE TITLE
Composite 'layered' strategy throws errors on cross-hierarchy edges.

### ISSUE THREAD

**Issue by alexei-tilikin** [kieler/elkjs#159]
Hi,

I'm reproducing a strange behavior when trying to use different `layoutOptions` configurations on a root graph vs. subgraphs.
Using `elkjs@0.7.1` as a bundle from npm.

I defined a graph with cross-hierarchy edges.
If I provide `defaultLayoutOptions` to ELK constructor, or just set `layoutOptions` on any subgraph, it throws the following error:
```
elk.bundled.js:6253 Uncaught (in promise) Error: org.eclipse.elk.core.UnsupportedGraphException: The source or the target of edge ElkEdge "node_1:node_4:cky8rorac000o3f7wfxc5mxsg" ElkNode "node_1" (0,0 | 150,123) -> ElkNode "node_4" (0,0 | 150,123) could not be found. This usually happens when an edge connects a node laid out by ELK Layered to a node in another level of hierarchy laid out by either another instance of ELK Layered or another layout algorithm alltogether. The former can be solved by setting the hierarchyHandling option to INCLUDE_CHILDREN.
```
"node_1:node_4:cky8rorac000o3f7wfxc5mxsg" is a cross hierarchy edge: "node_1" belongs to the root graph, while "node_4" sits under "group_2"

The option `hierarchyHandling` is set to `INCLUDE_CHILDREN` as advised in the error message.

The same graph works fine if I set `layoutOptions` **only** on the root graph, and don't set any `defaultLayoutOptions`, meaning all subgraphs share the exact same layout configuration (or so I think).

Here's the input graph (with the `layoutOptions` I tried using also as `defaultLayoutOptions` or subgraph `layoutOptions`).

```
{
  "id": "root",
  "children": [
    {
      "id": "node_1",
      "width": 150,
      "height": 123
    },
    {
      "id": "node_3",
      "width": 150,
      "height": 123
    },
    {
      "id": "node_6",
      "width": 150,
      "height": 123
    },
    {
      "id": "node_8",
      "width": 150,
      "height": 123
    },
    {
      "id": "center_1",
      "width": 150,
      "height": 123
    },
    {
      "id": "center_2",
      "width": 150,
      "height": 123
    },
    {
      "id": "group_2",
      "width": 150,
      "height": 123,
      "children": [
        {
          "id": "node_4",
          "width": 150,
          "height": 123
        },
        {
          "id": "node_5",
          "width": 150,
          "height": 123
        },
        {
          "id": "node_9",
          "width": 150,
          "height": 123
        }
      ]
    }
  ],
  "edges": [
    {
      "id": "center_1:node_1:cky8rorac000l3f7wc6rtrwd0",
      "sources": [
        "center_1"
      ],
      "targets": [
        "node_1"
      ]
    },
    {
      "id": "center_1:node_3:cky8rorac000n3f7wta0wtnoj",
      "sources": [
        "center_1"
      ],
      "targets": [
        "node_3"
      ]
    },
    {
      "id": "node_1:node_4:cky8rorac000o3f7wfxc5mxsg",
      "sources": [
        "node_1"
      ],
      "targets": [
        "node_4"
      ]
    },
    {
      "id": "node_3:node_6:cky8rorac000p3f7w5ky9vbxz",
      "sources": [
        "node_3"
      ],
      "targets": [
        "node_6"
      ]
    },
    {
      "id": "node_4:node_5:cky8rorac000s3f7www9rvj8z",
      "sources": [
        "node_4"
      ],
      "targets": [
        "node_5"
      ]
    },
    {
      "id": "node_5:node_8:cky8rorac000t3f7wgxfrebua",
      "sources": [
        "node_5"
      ],
      "targets": [
        "node_8"
      ]
    },
    {
      "id": "node_8:node_4:cky8rorac000u3f7wz6ik3flz",
      "sources": [
        "node_8"
      ],
      "targets": [
        "node_4"
      ]
    },
    {
      "id": "node_6:node_9:cky8rorac000v3f7wax3lhzp0",
      "sources": [
        "node_6"
      ],
      "targets": [
        "node_9"
      ]
    }
  ],
  "layoutOptions": {
    "elk.algorithm": "layered",
    "hierarchyHandling": "INCLUDE_CHILDREN",
    "elk.direction": "DOWN",
    "elk.spacing.nodeNode": 10,
    "spacing.edgeEdge": 3,
    "spacing.edgeEdgeBetweenLayers": 10,
    "elk.layered.layering.strategy": "NETWORK_SIMPLEX",
    "edgeRouting": "ORTHOGONAL",
    "elk.layered.crossingMinimization.semiInteractive": true
  }
}
```

Another thing is that this exact configuration does work as expected with `elkjs@0.6.1`.

Thanks in advance!

**Comment by uruuru** [comment]
The different behavior between 0.6.1 and 0.7.x may be due to several fixes to the handling of hierarchy which, iirc, also changed some logic that previously accepted invalidly configured graphs without throwing an exception. Fixes are listed at the bottom of the [release notes page](https://www.eclipse.org/elk/downloads/releasenotes/release-0.7.0.html).

Regarding the issue itself (without checking the graph itself), I would expect it to work if you set `INCLUDE_CHILDREN` for the root node directly. I think you say that works. In that case you should still be able to arbitrarily set _other layout options_, be it via the `defaultLayoutOptions` or on the nodes themselves. 

The `defaultLayoutOptions` are set explicitly for each node. Hence, if you add `INCLUDE_CHILDREN` to them, every node in the graph will be assigned this option value. I'm not sure if this is a problem in the sense that for each node a "new hierarchical layout" should be stated.

**Comment by alexei-tilikin** [comment]
Hi @uruuru,
Thank you for your response!
Your note on improved input validations between 0.6.1 and 0.7.1 helped me to spot the problem in my configuration.
In the odes, I was setting the option `elk.algorithm: layered` which was already set in the root graph options.
This one triggered the exception.

If I remove just that line from the node options, everything else seems to work as expected.
In that way there's no limitation in functionality, each node can have separate layoutOptions.

Closing this issue as "resolved".
