### ISSUE TITLE
Add support for individual spacing in layered algorithm

### ISSUE THREAD

**Issue by gfox1984** [kieler/elkjs#170]
I would like to be able to control the individual spacing between certain nodes when using the layered algorithm.

As mentioned in these two elkjs issues, this is not implemented:
https://github.com/kieler/elkjs/issues/89
https://github.com/kieler/elkjs/issues/123

Is there any plan for supporting this feature? Eg:

```javascript
{
  id: "root",
  layoutOptions: {
    'algorithm': 'layered',
    'elk.layered.nodePlacement.strategy': 'SIMPLE',
    'spacing.nodeNodeBetweenLayers': 100,
    'elk.direction': 'DOWN'
  },
  children: [
    { id: "n1", width: 30, height: 30, individualSpacings: { 'spacing.nodeNodeBetweenLayers': 10 }},
    { id: "n2", width: 30, height: 30, individualSpacings: { 'spacing.nodeNodeBetweenLayers': 10 }},
    { id: "n3", width: 30, height: 30, individualSpacings: { 'spacing.nodeNodeBetweenLayers': 10 }},
    { id: "n4", width: 30, height: 30},
    { id: "n5", width: 30, height: 30}
  ],
  edges: [
    { id: "e1", sources: [ "n1" ], targets: [ "n2" ] },
    { id: "e2", sources: [ "n1" ], targets: [ "n3" ] },
    { id: "e3", sources: [ "n2" ], targets: [ "n4" ] },
    { id: "e4", sources: [ "n2" ], targets: [ "n5" ] }
  ]
}
```

**Comment by soerendomroes** [comment]
I suggest you create a ticket for this directly in ELK maybe with a sketch how you want the drawing to look like.

It might be possible to easily implement that for nodeNodeBetweenLayers spacing but to do this for all spacings is quite complicated.

**Comment by gfox1984** [comment]
woops that was the intention! I created in in the wrong repo. Will re-log. Sorry about that
