### ISSUE TITLE
Node Positions Differ Compared to ELKJS Demos

### ISSUE THREAD

**Issue by RomanoViolet** [kieler/elkjs#171]
I am attempting to redraw [this example](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABBkJYCYFxgOQCcD2qAuiA05IQBsBDAT1QFcMB5ABwylQDsBnBYMPffRAUwIGsAdEQIBzVMigYAFgFtECRMRI9kPGDg5cuvAYOlRVRZAGNpJABJFGMAlEaiFYAEQBJAHIBhADIBVACIAogD6nhau3v4ASoHuzrja+AD0SS58QjBQaib0TM5wzv5UAOpxCYkQzumCyqrqgsw0RCb2ooLqojzuqDA8AEI8GADuPDyM3qSqzPkAjAAMc+UVVXq1ajCCjD08AArEJjyyYxiCAEZCAGZQAB7qAIJ2ooxHjBj5zn133ndegf7OnESAF8lpAzFACDA1IwEABtQH4UAVCCwRSMGY4BFcIawGQIAAscwAHKDtNIeFBRNIMAgAJwkrH4ZQUah0BgsNiMnRbXoTU58ZiCGj7Q7HJyIDwAZVcQTAADVggAVKg7MAWUKxRWBKKY5GQRA0CQYPkCoUil5YRRSmWBXV6sApRA8niSqAALx4ghMTGYGGQRHsGGY4vcVCCwW+fUC3klYB2VCiitj8cTEbuUZjYAAsh5XFnfFngtKAFq20mJJ3bV0ewSoNk+8VBABid183kVwRz7jzBaLrlLYE8VCzO18WuCOzu-n8HgA4na9VyICCl2BiPyCKwwLD2BgeNcaUhPKhZIbGMcwHdEGAgQBdcv4Q3IINw1cQJH2lHwJBPjDBABMC72jiMB4mA8wPok5KUtSCAQW++q-g0sA8OKxSBJKipAXqBpGrWyC9MgTjwZ+EAYCQNA8Fa7ijlhkHaOuAqvqRkAfixZH7oeuHPgB2GkdBVKHvMCH4ECIlgLeCErp+bH2qiP5GsEADMfEVCBYEkfxFKCXBizidxJzMCh4qBHcmGqRWSESIRxF6Sx5GUYoVBjrRFkMUQG5bvC7FgLJ9mcYov7KW5yICbB4FzOJy7iZJn7SfafnIvJBnBBi9HYri0i6el+BhUJdmkQZyG9GhGF0fpVkEaotk5ZADlUUgHiubVhAeUx25Rb5nUcQegWKWl3VgHlumdWJLGxfa8V6olFTJUF+Ihfg6lZRFLVDdp4WaZ+RVGSViimeZa1FdZ1XZeJ9VOS5Y6LZAjGbsx7Ezfae69QpPELWtuUbflo0xVJq4TdoU1cE9X5ooB6XLXB9LpcNYAAGxKeld1ebuAVHieZ4Xn0153ulv5eQhoNcHNikAKw3RAUOreJcNbfaO3GYo6GHRVeEnURZ32RRDUSjR11rSjD0scTFQvVxQUU59kB05FPljaRgPIgrFRK6JkHE8ljAqZDmUIEpMz4rD30IAA7Ebq5C9uaOvYgx6nkwF6eLj96rgTwvIqL0Dfil8OU2A1P03qstHUhu2oczZX+8dVWczT3OOY1-PlSxVveY9g3i31PF+9LECy7941SbVXtg29f6m-7gcFZ+Ids8+xUR0gLMp4VlU2VzpEXUnzXiWnnWl1wWfl8Eld5+tME-fLf1xQDXIq5ArvaB0PCExUKRgCvYDiKvYAXGgshgIwRBHDAYC-mAMpgBgqBHyf6jn0al-+Fy7DJTwaVgMwFCmKvcIpSpe819jCdBfNuFKFMgHf3IL-YIzo0SfwwCAwYcDtjg1xhrMA78IZfx-gcLyKUFpAKQcgUBBCgp+ygXgngqDegIM0CQ0BtDeba1xliJWQIgA) in a custom frontend. 

**What I have Done So Far**

In my typescript implementation, specified the graph as in the example above, and then:

```ts
 elk.layout(new_graph).then((data) => {
      this.data = data;
      // other stuff
    });
```
However, I see that the positions of Nodes "Box B" and "Box C" are exchanged in `data` in my implementation compared to the [reference](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABBkJYCYFxgOQCcD2qAuiA05IQBsBDAT1QFcMB5ABwylQDsBnBYMPffRAUwIGsAdEQIBzVMigYAFgFtECRMRI9kPGDg5cuvAYOlRVRZAGNpJABJFGMAlEaiFYAEQBJAHIBhADIBVACIAogD6nhau3v4ASoHuzrja+AD0SS58QjBQaib0TM5wzv5UAOpxCYkQzumCyqrqgsw0RCb2ooLqojzuqDA8AEI8GADuPDyM3qSqzPkAjAAMc+UVVXq1ajCCjD08AArEJjyyYxiCAEZCAGZQAB7qAIJ2ooxHjBj5zn133ndegf7OnESAF8lpAzFACDA1IwEABtQH4UAVCCwRSMGY4BFcIawGQIAAscwAHKDtNIeFBRNIMAgAJwkrH4ZQUah0BgsNiMnRbXoTU58ZiCGj7Q7HJyIDwAZVcQTAADVggAVKg7MAWUKxRWBKKY5GQRA0CQYPkCoUil5YRRSmWBXV6sApRA8niSqAALx4ghMTGYGGQRHsGGY4vcVCCwW+fUC3klYB2VCiitj8cTEbuUZjYAAsh5XFnfFngtKAFq20mJJ3bV0ewSoNk+8VBABid183kVwRz7jzBaLrlLYE8VCzO18WuCOzu-n8HgA4na9VyICCl2BiPyCKwwLD2BgeNcaUhPKhZIbGMcwHdEGAgQBdcv4Q3IINw1cQJH2lHwJBPjDBABMC72jiMB4mA8wPok5KUtSCAQW++q-g0sA8OKxSBJKipAXqBpGrWyC9MgTjwZ+EAYCQNA8Fa7ijlhkHaOuAqvqRkAfixZH7oeuHPgB2GkdBVKHvMCH4ECIlgLeCErp+bH2qiP5GsEADMfEVCBYEkfxFKCXBizidxJzMCh4qBHcmGqRWSESIRxF6Sx5GUYoVBjrRFkMUQG5bvC7FgLJ9mcYov7KW5yICbB4FzOJy7iZJn7SfafnIvJBnBBi9HYri0i6el+BhUJdmkQZyG9GhGF0fpVkEaotk5ZADlUUgHiubVhAeUx25Rb5nUcQegWKWl3VgHlumdWJLGxfa8V6olFTJUF+Ihfg6lZRFLVDdp4WaZ+RVGSViimeZa1FdZ1XZeJ9VOS5Y6LZAjGbsx7Ezfae69QpPELWtuUbflo0xVJq4TdoU1cE9X5ooB6XLXB9LpcNYAAGxKeld1ebuAVHieZ4Xn0153ulv5eQhoNcHNikAKw3RAUOreJcNbfaO3GYo6GHRVeEnURZ32RRDUSjR11rSjD0scTFQvVxQUU59kB05FPljaRgPIgrFRK6JkHE8ljAqZDmUIEpMz4rD30IAA7Ebq5C9uaOvYgx6nkwF6eLj96rgTwvIqL0Dfil8OU2A1P03qstHUhu2oczZX+8dVWczT3OOY1-PlSxVveY9g3i31PF+9LECy7941SbVXtg29f6m-7gcFZ+Ids8+xUR0gLMp4VlU2VzpEXUnzXiWnnWl1wWfl8Eld5+tME-fLf1xQDXIq5ArvaB0PCExUKRgCvYDiKvYAXGgshgIwRBHDAYC-mAMpgBgqBHyf6jn0al-+Fy7DJTwaVgMwFCmKvcIpSpe819jCdBfNuFKFMgHf3IL-YIzo0SfwwCAwYcDtjg1xhrMA78IZfx-gcLyKUFpAKQcgUBBCgp+ygXgngqDegIM0CQ0BtDeba1xliJWQIgA). Specifically, in my implementation, the y coordinate of the "Box B"  is greater than the y-coordinate of "Box C", which places "Box B" below "Box C". 

![image](https://user-images.githubusercontent.com/19875252/170728906-0e2ae2db-39bd-4a20-b452-d30ee4e9f829.png)

I am attempting to redraw "Box C" and "Box B" based on the location calculated by elkjs. 

I noticed that the [elkjs demo figure has](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABBkJYCYFxgOQCcD2qAuiA05IQBsBDAT1QFcMB5ABwylQDsBnBYMPffRAUwIGsAdEQIBzVMigYAFgFtECRMRI9kPGDg5cuvAYOlRVRZAGNpJABJFGMAlEaiFYAEQBJAHIBhADIBVACIAogD6nhau3v4ASoHuzrja+AD0SS58QjBQaib0TM5wzv5UAOpxCYkQzumCyqrqgsw0RCb2ooLqojzuqDA8AEI8GADuPDyM3qSqzPkAjAAMc+UVVXq1ajCCjD08AArEJjyyYxiCAEZCAGZQAB7qAIJ2ooxHjBj5zn133ndegf7OnESAF8lpAzFACDA1IwEABtQH4UAVCCwRSMGY4BFcIawGQIAAscwAHKDtNIeFBRNIMAgAJwkrH4ZQUah0BgsNiMnRbXoTU58ZiCGj7Q7HJyIDwAZVcQTAADVggAVKg7MAWUKxRWBKKY5GQRA0CQYPkCoUil5YRRSmWBXV6sApRA8niSqAALx4ghMTGYGGQRHsGGY4vcVCCwW+fUC3klYB2VCiitj8cTEbuUZjYAAsh5XFnfFngtKAFq20mJJ3bV0ewSoNk+8VBABid183kVwRz7jzBaLrlLYE8VCzO18WuCOzu-n8HgA4na9VyICCl2BiPyCKwwLD2BgeNcaUhPKhZIbGMcwHdEGAgQBdcv4Q3IINw1cQJH2lHwJBPjDBABMC72jiMB4mA8wPok5KUtSCAQW++q-g0sA8OKxSBJKipAXqBpGrWyC9MgTjwZ+EAYCQNA8Fa7ijlhkHaOuAqvqRkAfixZH7oeuHPgB2GkdBVKHvMCH4ECIlgLeCErp+bH2qiP5GsEADMfEVCBYEkfxFKCXBizidxJzMCh4qBHcmGqRWSESIRxF6Sx5GUYoVBjrRFkMUQG5bvC7FgLJ9mcYov7KW5yICbB4FzOJy7iZJn7SfafnIvJBnBBi9HYri0i6el+BhUJdmkQZyG9GhGF0fpVkEaotk5ZADlUUgHiubVhAeUx25Rb5nUcQegWKWl3VgHlumdWJLGxfa8V6olFTJUF+Ihfg6lZRFLVDdp4WaZ+RVGSViimeZa1FdZ1XZeJ9VOS5Y6LZAjGbsx7Ezfae69QpPELWtuUbflo0xVJq4TdoU1cE9X5ooB6XLXB9LpcNYAAGxKeld1ebuAVHieZ4Xn0153ulv5eQhoNcHNikAKw3RAUOreJcNbfaO3GYo6GHRVeEnURZ32RRDUSjR11rSjD0scTFQvVxQUU59kB05FPljaRgPIgrFRK6JkHE8ljAqZDmUIEpMz4rD30IAA7Ebq5C9uaOvYgx6nkwF6eLj96rgTwvIqL0Dfil8OU2A1P03qstHUhu2oczZX+8dVWczT3OOY1-PlSxVveY9g3i31PF+9LECy7941SbVXtg29f6m-7gcFZ+Ids8+xUR0gLMp4VlU2VzpEXUnzXiWnnWl1wWfl8Eld5+tME-fLf1xQDXIq5ArvaB0PCExUKRgCvYDiKvYAXGgshgIwRBHDAYC-mAMpgBgqBHyf6jn0al-+Fy7DJTwaVgMwFCmKvcIpSpe819jCdBfNuFKFMgHf3IL-YIzo0SfwwCAwYcDtjg1xhrMA78IZfx-gcLyKUFpAKQcgUBBCgp+ygXgngqDegIM0CQ0BtDeba1xliJWQIgA)  a mystical "translate" instruction:
![image](https://user-images.githubusercontent.com/19875252/170729583-4d23a70d-16f2-4cae-906f-64accb9b9f5d.png)

I notice [here](https://github.com/kieler/elkjs/issues/88#issuecomment-670711892) that there is a `$H` being provided by `elkjs`. I cannot find what `$H` means. Could this be something that is missing?

![image](https://user-images.githubusercontent.com/19875252/170733463-1e96fc37-1db2-4542-a7dc-5f0038fae432.png)

Where am I going wrong?

**Comment by soerendomroes** [comment]
[This example ](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABBkJYCYFxgOQCcD2qAuiA05IQBsBDAT1QFcMB5ABwylQDsBnBYMPffRAUwIGsAdEQIBzVMigYAFgFtECRMRI9kPGDg5cuvAYOlRVRZAGNpJABJFGMAlEaiFYAEQBJAHIBhADIBVACIAogD6nhau3v4ASoHuzrja+AD0SS58QjBQaib0TM5wzv5UAOpxCYkQzumCyqrqgsw0RCb2ooLqojzuqDA8AEI8GADuPDyM3qSqzPkAjAAMc+UVVXq1ajCCjD08AArEJjyyYxiCAEZCAGZQAB7qAIJ2ooxHjBj5zn133ndegf7OnESAF8lpAzFACDA1IwEABtQH4UAVCCwRSMGY4BFcIawGQIAAscwAHKDtNIeFBRNIMAgAJwkrH4ZQUah0BgsNiMnRbXoTU58ZiCGj7Q7HJyIDwAZVcQTAADVggAVKg7MAWUKxRWBKKY5GQRA0CQYPkCoUil5YRRSmWBXV6sApRA8niSqAALx4ghMTGYGGQRHsGGY4vcVCCwW+fUC3klYB2VCiitj8cTEbuUZjYAAsh5XFnfFngtKAFq20mJJ3bV0ewSoNk+8VBABid183kVwRz7jzBaLrlLYE8VCzO18WuCOzu-n8HgA4na9VyICCl2BiPyCKwwLD2BgeNcaUhPKhZIbGMcwHdEGAgQBdcv4Q3IINw1cQJH2lHwJBPjDBABMC72jiMB4mA8wPok5KUtSCAQW++q-g0sA8OKxSBJKipAXqBpGrWyC9MgTjwZ+EAYCQNA8Fa7ijlhkHaOuAqvqRkAfixZH7oeuHPgB2GkdBVKHvMCH4ECIlgLeCErp+bH2qiP5GsEADMfEVCBYEkfxFKCXBizidxJzMCh4qBHcmGqRWSESIRxF6Sx5GUYoVBjrRFkMUQG5bvC7FgLJ9mcYov7KW5yICbB4FzOJy7iZJn7SfafnIvJBnBBi9HYri0i6el+BhUJdmkQZyG9GhGF0fpVkEaotk5ZADlUUgHiubVhAeUx25Rb5nUcQegWKWl3VgHlumdWJLGxfa8V6olFTJUF+Ihfg6lZRFLVDdp4WaZ+RVGSViimeZa1FdZ1XZeJ9VOS5Y6LZAjGbsx7Ezfae69QpPELWtuUbflo0xVJq4TdoU1cE9X5ooB6XLXB9LpcNYAAGxKeld1ebuAVHieZ4Xn0153ulv5eQhoNcHNikAKw3RAUOreJcNbfaO3GYo6GHRVeEnURZ32RRDUSjR11rSjD0scTFQvVxQUU59kB05FPljaRgPIgrFRK6JkHE8ljAqZDmUIEpMz4rD30IAA7Ebq5C9uaOvYgx6nkwF6eLj96rgTwvIqL0Dfil8OU2A1P03qstHUhu2oczZX+8dVWczT3OOY1-PlSxVveY9g3i31PF+9LECy7941SbVXtg29f6m-7gcFZ+Ids8+xUR0gLMp4VlU2VzpEXUnzXiWnnWl1wWfl8Eld5+tME-fLf1xQDXIq5ArvaB0PCExUKRgCvYDiKvYAXGgshgIwRBHDAYC-mAMpgBgqBHyf6jn0al-+Fy7DJTwaVgMwFCmKvcIpSpe819jCdBfNuFKFMgHf3IL-YIzo0SfwwCAwYcDtjg1xhrMA78IZfx-gcLyKUFpAKQcgUBBCgp+ygXgngqDegIM0CQ0BtDeba1xliJWQIgA) seems to be drawn incorrectly. It should look like [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBCD28AuAoMAbY8QEslQFsAuGdMATwFMRKATFKHasEAYynIAkwA7W9HD2AkAkgDkAwgBkAqgBEAogH0JnEVLkAlBWJQBnCGFaDgAOjrBKY+LUoAhSkgDulSjykVqekgEYADH4oPDaUAApkrJQEbkimAEYA1qYAZjgAHnQAggLAPNE8SCR2mVKZkgpyQSEwPD4wAN4oAJBk5PAArkgwANowejgAXpQkACx+ABwANDAAnOMwALrNwbYecZToeqYQEVExJABE3ZwqOgAqCprTAGpKZwDyodPiAMoiigsHzRDYSGsbWx2Rj2BUO3Ve7wUn2WIReg0opngECQOHgPG8MCOigAYpkZFIzkoALLiEREmREpRvABaCmmEnuRNCMguSlCmTkcnEAHFoS0wOt0JiJPACD8eDEYJkvk0fiAunKkEoAEwNZr8tqdHp9eG+PzTfyLdVkQWYxUqg5qprW1odLq9H79FFokj6mB+HVDV0Gj1La0AX2agdlvxg5oAzFaNXbtf0vTB-D6jTaBRszb8lOHLY1rdGtQ74E7UTxve7PcN3Um-U1g8HFWGM3Uc3n7eW9VXjamhQdzT5s+qW9rHXhi6WPXGK27DdXa99Q+aRlHbfm2wmp77O6aexmRv3c8vW8PnSXK2WJ6Xp+rZ4GVpQaqqcwfY7qE3NpgA2SN+k1pg4isVopKdgyvW5oAKxLhQMa9Oea4dimW7gXuKaaoehYji6p7ji+67JjWQYoDe1Q8JGj5QSusHhj4IzTAA7Iu35dsKoripKEggfOGbvpBqHPvGiZrnhP7dua77IYOBZFphbrYfGuEzgRIbyg28pKLRPHQauAmXghv7mrR4lPpJGEnjJq7yVeBGBhYd6UD4JC1NsGaRgAtAAfPeTmqWBKA2TAlDKg5PheUqi7uTU4YhUo74oEAA).

Can you add screenshots what drawing you are expecting and what the drawing currently looks like? I am unsure what your problem is. Are "Box B" and "Box C" drawn in the wrong order? Is some position wrong?

**Comment by RomanoViolet** [comment]
Thanks, @soerendomroes . 

My core question is: _does the y-axis point up or down? The convention in web-graphics is that y-axis points downwards. _

[This example](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGBECWAmkC4oCcD2qAukA04oBsBDAT1QFcMB5ABw2lQDsBnRMUCCSJ6wgY2gYBzAHQBTWINEA5VLFEAhURgDuo0QwAyJUchZJIARgAMR4UZx5OhfINTJoGABYBbVpCLEd4ixygAzaAAPcQBBfGhBBmd1LH15EI0QqQBhAFEAER8OSEdoHUJkXkdiAAlCBlhwoTcASRSNAFV01IB9ZJKajXSAJVSpSDwAX1xOIuh8WGR1VgBtSzZ5zjg3BgMs30hlOCdWACYTEd8oR1EIx1iwAHZdw42PcipaemZWdiPOBllRLQAjUXwmMJqEReKJogwLpA6gBlGrNMAANRaABVKAAFMAlNp9ZGpbrrI6Qah2DC-f6A4F8MExWpSWHNAkbT5yaHQABeomEqCejD0UGaADEQg0NMiWgBZOo1cUNcUtWEALVSYGSlHFaIauJaaJC6XSdQA4gN3sNFgRCH8AbMzRA3u9OBhRIFIclUM5iQwYmAQozCYFWMYjLd7ZBiKwAKzB96bbaOVhBm3ZE5nC5GRODM0AXSjUGJyAwfLm9oWxaW8H0eYwLV2vo2W1gOyQxhzG2TgnOAYTpdzJOETDgojcAHVUtDkbXspWucg5MhOy3shhiNRB-o6hrxwvOERLYXE747d2oI7nW5K9WJ9G2x2m12j5x-U2DFvCWGkHf7zGG3H3-uOBnu2zP9IEfMAAFpm2At8wAAFhg4QADYkOQlCUJg9MF0PaNlgrEkWgAZkvKB60bMBIO7HJTnbC5yNLIle37OQ3FSEIxyI+j82nWd52ApcVzcShNQ3did3Ja17ywuiT0hc9CJfVsqJvMiPyPEDWAg+TsmglSKJIn8wDTe8ANLICKNA-YdNfVg4MQ1C7KQ9Di1NYtJI2HCe3zFo1hfL9SNo4tKJTHiKKnRjVygEc2J8qc7G428fL48KoSkYSfNEq0kCLI9XJDaSzzw7y-wUoL4qK7JQIMZ8ys4bTNM4PT4zK4zi1MujQIgyyNmggxLmEfD+oGwbBt2DDExyst8s8mD2Ia0qKOvGjOsnBiB2Y1jN2AmKZx0YKpOXJLBORVLgPSvcJOq48nRkvDprq45FMWu61KQDSLtDeMntmgymr-VqAvMg4oIDXqhtBgaRqcrMc0gAASEo9kuS5ofMm4zXepAYIADmEcNdmQ65EaMAxMd2fDHP-YNJJgcsoAYGtoa+izoYW1gEIMYQ4JMIxdjggwYKMBDdkjNHTvE+1xsu099Fdd1GC9eR2NApaao+4CvuV+6Su+yH3j+5b8zO8XgPcjiq3DGbY12gKWbmujQtW-RIo2kLe1inbbYCxLaWOijRcysqJY2PLcM882npt5Snvaqr7xVp9Pst38jN+nzo419GwCF4Rri5gxdn2S4jHwvPw3TKG0bhvYAE5LOe2CYPw6HuqMcmIGcjgqZNhg5LRxnAavB7WGuaG-bALL3glyBg6gGWPS9ZJFdVijarVxODJ8iPDPtZqOD1zhK0NifjZp02WgQi3vytkMI-8kN7aYx3R2du3Xe2ucPdy-bvc1ESLTE-3zqx0ltdTy59w6Dw-mZdSMdY4ZwgjAz86sfqAVTtA9O3UQZg1BhDbemFj6TSrJcC+fl0433TvfJKTt2JbTipHXiX81wpR-mlP+GUx4BzetPU+RDwFa1vlAl6CDVLdSEbpNeW9uw711qgwR6DrLwXsvZVuRwpFgD3lASuSBdhV2FtGUCcFG5o26jgtueBWqQHEJIQ+JZCQm1EIVaMTByCFFENYjYsljRHHUVPAokgCxi2jOec25dHHONBC0ZkSVVi+h8cgPxESvgrHpmjJgoheB0F5AEo4k87EGBaEwcwPkmAYAKBgNEqABAXEDlAcy+FUafmglXbGBgq6DSrg3BCmMYJVz-O3AK6hYDlMqa8MqdcG6GIaQGMm2cLJE3zkYQuxcTG4OAn8CoQyIRuKNkAuu-V6mwMac01pA12n4U6d0pqmlqkPlYHsp63Vpk5xMHnAuRc87IJMj5AQvA3QCEENCRwhB+IhyrD3CiDxbB-IBUCpKQTPEmizPMPpNi3In1EMk0JZAXFbP3jdeFu9oYlLiUoHFHkqznxCYSJxWLwmRJWA4wkRL4l0v0N3GJqT0nPFJTktFux8mFOAsU0pGyqmjNqfs5eQ9TCYwQlzAWxh8LhgMOGBCvSfIDJFSMz8+j+qaQztMrBoM1WrI1RUzZWSXJvVAnct60FC7CBlXKtmRclUqsuRwnZ1q6n3NufBQ1Q0PktS+QwH5zgoWAuBWSlot1gIQrNf8iNsK8IUp1l4pFZjDiw3hk2CZNSl5QBXvVNeCFwy6M1tRYGvVOYmB5jBPmAshYgEGEAA) seems to suggest that y-axis points up. 

Specifically, 

1. Component B (id: n2) has       "x": 443, "y": 104
2. Component C (id: n3) has       "x": 443, "y": 12

Based on this Component C should be above Component B, but it is drawn the other way around. 

For reference, my frontend draws this:

![image](https://user-images.githubusercontent.com/19875252/171491140-b2f162f4-ea1d-4860-a04a-aae3afeb660d.png)

**Comment by soerendomroes** [comment]
The y-axis points downwards. In your example, the x and y coordinates are not used. Automatic layout is done and this reorders B and C to reduce the number of crossings.

Do you want to constrain the position of B and C?

**Comment by RomanoViolet** [comment]
> In your example, the x and y coordinates are not used. A

I assume that you meant "The drawing part of [this example](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGBECWAmkC4oCcD2qAukA04oBsBDAT1QFcMB5ABw2lQDsBnRMUCCSJ6wgY2gYBzAHQBTWINEA5VLFEAhURgDuo0QwAyJUchZJIARgAMR4UZx5OhfINTJoGABYBbVpCLEd4ixygAzaAAPcQBBfGhBBmd1LH15EI0QqQBhAFEAER8OSEdoHUJkXkdiAAlCBlhwoTcASRSNAFV01IB9ZJKajXSAJVSpSDwAX1xOIuh8WGR1VgBtSzZ5zjg3BgMs30hlOCdWACYTEd8oR1EIx1iwAHZdw42PcipaemZWdiPOBllRLQAjUXwmMJqEReKJogwLpA6gBlGrNMAANRaABVKAAFMAlNp9ZGpbrrI6Qah2DC-f6A4F8MExWpSWHNAkbT5yaHQABeomEqCejD0UGaADEQg0NMiWgBZOo1cUNcUtWEALVSYGSlHFaIauJaaJC6XSdQA4gN3sNFgRCH8AbMzRA3u9OBhRIFIclUM5iQwYmAQozCYFWMYjLd7ZBiKwAKzB96bbaOVhBm3ZE5nC5GRODM0AXSjUGJyAwfLm9oWxaW8H0eYwLV2vo2W1gOyQxhzG2TgnOAYTpdzJOETDgojcAHVUtDkbXspWucg5MhOy3shhiNRB-o6hrxwvOERLYXE747d2oI7nW5K9WJ9G2x2m12j5x-U2DFvCWGkHf7zGG3H3-uOBnu2zP9IEfMAAFpm2At8wAAFhg4QADYkOQlCUJg9MF0PaNlgrEkWgAZkvKB60bMBIO7HJTnbC5yNLIle37OQ3FSEIxyI+j82nWd52ApcVzcShNQ3did3Ja17ywuiT0hc9CJfVsqJvMiPyPEDWAg+TsmglSKJIn8wDTe8ANLICKNA-YdNfVg4MQ1C7KQ9Di1NYtJI2HCe3zFo1hfL9SNo4tKJTHiKKnRjVygEc2J8qc7G428fL48KoSkYSfNEq0kCLI9XJDaSzzw7y-wUoL4qK7JQIMZ8ys4bTNM4PT4zK4zi1MujQIgyyNmggxLmEfD+oGwbBt2DDExyst8s8mD2Ia0qKOvGjOsnBiB2Y1jN2AmKZx0YKpOXJLBORVLgPSvcJOq48nRkvDprq45FMWu61KQDSLtDeMntmgymr-VqAvMg4oIDXqhtBgaRqcrMc0gAASEo9kuS5ofMm4zXepAYIADmEcNdmQ65EaMAxMd2fDHP-YNJJgcsoAYGtoa+izoYW1gEIMYQ4JMIxdjggwYKMBDdkjNHTvE+1xsu099Fdd1GC9eR2NApaao+4CvuV+6Su+yH3j+5b8zO8XgPcjiq3DGbY12gKWbmujQtW-RIo2kLe1inbbYCxLaWOijRcysqJY2PLcM882npt5Snvaqr7xVp9Pst38jN+nzo419GwCF4Rri5gxdn2S4jHwvPw3TKG0bhvYAE5LOe2CYPw6HuqMcmIGcjgqZNhg5LRxnAavB7WGuaG-bALL3glyBg6gGWPS9ZJFdVijarVxODJ8iPDPtZqOD1zhK0NifjZp02WgQi3vytkMI-8kN7aYx3R2du3Xe2ucPdy-bvc1ESLTE-3zqx0ltdTy59w6Dw-mZdSMdY4ZwgjAz86sfqAVTtA9O3UQZg1BhDbemFj6TSrJcC+fl0433TvfJKTt2JbTipHXiX81wpR-mlP+GUx4BzetPU+RDwFa1vlAl6CDVLdSEbpNeW9uw711qgwR6DrLwXsvZVuRwpFgD3lASuSBdhV2FtGUCcFG5o26jgtueBWqQHEJIQ+JZCQm1EIVaMTByCFFENYjYsljRHHUVPAokgCxi2jOec25dHHONBC0ZkSVVi+h8cgPxESvgrHpmjJgoheB0F5AEo4k87EGBaEwcwPkmAYAKBgNEqABAXEDlAcy+FUafmglXbGBgq6DSrg3BCmMYJVz-O3AK6hYDlMqa8MqdcG6GIaQGMm2cLJE3zkYQuxcTG4OAn8CoQyIRuKNkAuu-V6mwMac01pA12n4U6d0pqmlqkPlYHsp63Vpk5xMHnAuRc87IJMj5AQvA3QCEENCRwhB+IhyrD3CiDxbB-IBUCpKQTPEmizPMPpNi3In1EMk0JZAXFbP3jdeFu9oYlLiUoHFHkqznxCYSJxWLwmRJWA4wkRL4l0v0N3GJqT0nPFJTktFux8mFOAsU0pGyqmjNqfs5eQ9TCYwQlzAWxh8LhgMOGBCvSfIDJFSMz8+j+qaQztMrBoM1WrI1RUzZWSXJvVAnct60FC7CBlXKtmRclUqsuRwnZ1q6n3NufBQ1Q0PktS+QwH5zgoWAuBWSlot1gIQrNf8iNsK8IUp1l4pFZjDiw3hk2CZNSl5QBXvVNeCFwy6M1tRYGvVOYmB5jBPmAshYgEGEAA) does not use the computed x,y coordinates". 

> Automatic layout is done and this reorders B and C to reduce the number of crossings.

From what I understand, the elkjs computes a layout, which I understood means that I elkjs will tell me where to place each box (here, "Component A, .. Component C") on the page. 

> Do you want to constrain the position of B and C?

Yes, I want minimal edge crossings.  That is why I thought I could use elkjs to compute the layouts of rectangles and edges for me.  

The questions are now:

1. Am I correct in using elkjs for its capability to compute the location of rectangles and edges so that I can draw these where elkjs tells me to?
2. If I cannot use elkjs for laying out my graphical elements, then I would appreciate any suggestions, e.g., any other library.

**Comment by soerendomroes** [comment]
Many other tools use elkjs so why shouldn't you able to do that. I do, however, not know what your custom frontend does differently to create the drawing above.
I noticed that the port order is different from the example. port_2 is above port_1. Maybe that is a hind to the problem.

**Comment by RomanoViolet** [comment]
> Automatic layout is done and this reorders B and C to reduce the number of crossings.
May I please know where this algorithm is, and how do I get it? From the discussion in this thread so far, I reckon that it is outside of elkjs. 

> I noticed that the port order is different from the example. port_2 is above port_1. Maybe that is a hind to the problem.
Correct. I will correct it. However, I was focussing on the components ("rectangles") so far, so my question is related to relative positions of Rectangles "Component" B and C.

**Comment by RomanoViolet** [comment]
I had to sort the port order as suggested by elkjs before drawing. Fixed this issue. 
Many thanks, @soerendomroes
