### ISSUE TITLE
Last ELKNode is offset unexpectedly

### ISSUE THREAD

**Issue by david-novicki** [kieler/elkjs#172]
I am unsure why when I create this simple graph that the last node seems to have an offset lower than the rest. This seems to only occur when I pass in edges connecting directly to ports. Am I missing something here or is this a bug?

Behavior:
![Screen Shot 2022-06-02 at 3 47 56 PM](https://user-images.githubusercontent.com/10945176/171753465-d37ec530-e09c-416d-a7ec-c72751a119fd.png)

Graph source:
```json
{
  id: "root",
  layoutOptions: { 'algorithm': 'layered' },
  children: [
    {
      id: "n1",
      width: 30,
      height: 30,
      ports: [
        { id: "n1:w" },
        { id: "n1:e" }
      ]
    },
    {
      id: "n2",
      width: 30,
      height: 30,
      ports: [
        { id: "n2:w" },
        { id: "n2:e" }
      ]
    },
    {
      id: "n3",
      width: 30,
      height: 30,
      ports: [
        { id: "n3:w" },
        { id: "n3:e" }
      ]
    }
  ],
  edges: [
    { id: "e1", sources: [ "n1:e" ], targets: [ "n2:w" ] },
    { id: "e2", sources: [ "n2:e" ], targets: [ "n3:w" ] },
  ]
}
```

**Comment by soerendomroes** [comment]
The second port in n3 has a size, as seen [here](http://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBCD28AuAoMAbY8QEslQFsAuGdMATwFMRKATFAO3lspgYEYYBvFASDPLwArkhgBtGAGccAL0okAzAAYANDGUwAunwjZRHAPoB3HXrbsDlFAF9GzVgwBM3PgOGiJ0uYtXqlW0xB9R2NA4MsbOxY2BRd+CndxKVl5PzUNbV5dIJjQrLMGBQjbOmBWSnYSDgA6Q1YAWgA+NkdakJNS8scq1qdLGCaY2qKTIA).

**Comment by david-novicki** [comment]
@soerendomroes Thanks, did not realize the port would switch sides if it was given a direction.
