### ISSUE TITLE
Current version clarification

### ISSUE THREAD

**Issue by Andarist** [kieler/elkjs#180]
The current `package.json` implies that there is a 0.9.0 version:
https://github.com/kieler/elkjs/blob/1abb7167ecf7ddd133a62353427b17f81f8835f0/package.json#L3
but no such version has been released yet:
https://www.npmjs.com/package/elkjs?activeTab=versions

**Comment by soerendomroes** [comment]
Yes, 0.9.0 refers to the next version.

**Comment by Andarist** [comment]
Roger that, although I think that the usual expectation in the npm ecosystem is to only bump the version in `package.json` just before making a release.
