### ISSUE TITLE
Define the position of the parent node

### ISSUE THREAD

**Issue by LeungChunChiu** [kieler/elkjs#182]
I'm trying to create a graph with **react-flow**, and to define the positions of the nodes I'm using **elkjs**. My node group has one and only one top-level node, and I want the position of the top-most parent to be the same every time I call `elk.layout`

Below is my existing elk configuration
```jsx
const elk = new Elk({
  "defaultLayoutOptions": {
    "elk.algorithm": "layered",
    "elk.direction": "DOWN",
    "elk.layered.nodePlacement.bk.fixedAlignment": "BALANCED",
    "elk.layered.layering.strategy": "INTERACTIVE",
  }
});
const nodeWidth = 300;
const nodeHeight = 200;
const newGraph = await elk.layout({
  id: "root",
  children: nodes.map((item) => ({
    ...item,
    width: nodeWidth,
    height: nodeHeight
  })),
  edges: edges
});
```

What could be the problem here? Thanks!

**Comment by soerendomroes** [comment]
The position of the root node should be defined by its margin, if this is what you are asking for.

Can you please recreate your model in the [elk-live json](https://rtsys.informatik.uni-kiel.de/elklive/json.html) editor or [elkt editor](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html)?
