### ISSUE TITLE
Tag 0.8

### ISSUE THREAD

**Issue by domoritz** [kieler/elkjs#184]
0.8 seems to be out (https://www.npmjs.com/package/elkjs) but I don't see any release notes. Can you add them?

**Comment by soerendomroes** [comment]
https://www.eclipse.org/elk/downloads.html
The elkjs 0.8.1/2 releases correspond to the ELK 0.8.0/1 releases.

**Comment by domoritz** [comment]
Ah, great. Thanks for pointing me to the changelog.
