### ISSUE TITLE
How to keep parent node position while new child node appended.

### ISSUE THREAD

**Issue by fanmingfei** [kieler/elkjs#187]
Origin Graph.
2 is top of 3
<img width="423" alt="image" src="https://user-images.githubusercontent.com/4632277/190100657-57e99b7b-36c9-414a-ac92-151514c40a2e.png">

Add a child, I wanna get: 
2 is top of 3
<img width="479" alt="image" src="https://user-images.githubusercontent.com/4632277/190101944-1299a2af-fc9c-4488-a87c-4a3780befa76.png">

But, I got:
2 is bottom of 3
<img width="444" alt="image" src="https://user-images.githubusercontent.com/4632277/190100902-a8557166-1095-4246-a3f4-4bbbc6de752e.png">

How can I keep origin graph node position, like image 2. ? thx

**Comment by soerendomroes** [comment]
Have you tried to use the conderModelOrder.strategy property? If your input graph is sufficiently ordered as suggested by your state names it should solve your problem. Do you want to always enforce the constrain n2 is above n3 or only if it is optimal regarding edge crossings?

**Comment by fanmingfei** [comment]
I tried to use the `conderModelOrder.strategy`, but not work. I need the order suggestion not by name.
My nodes are added one by one, and I run layout while node added. if the exist node position cannot be made consistent, it will make users confused.

**Comment by soerendomroes** [comment]
Are you using elkjs 0.8.2?
If you are try to set the following options:
https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-crossingMinimization-forceNodeModelOrder.html
and https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-considerModelOrder-strategy.html
to NODES_EDGES. It makes sure that the vertical position of your nodes does not change, given that the input model is ordered correctly. If you have problems with that order you could either try to use constraints or a fixed port order, but these follow roughly the same ideas. Either you have to control the position via pseudo positions that you have to calculate, calculate and constrain the port order, or directly influence the model by the order in your input model.
Either way specific node positions will change (although you could enable interactive Layout, which will mask that until a reload is required and needs layout post and pre processing) and you will only be able to constrain relative positions. The small movement is usually animated to make it easier to follow these changes.

Maybe you could elaborate on your workflow. As I understand it you are writing a textual graph and want to make sure that node order does not change if new nodes are added. I also assume that a new node that is added textually before an old node should also be added before the old node in the graphical representation .

**Comment by fanmingfei** [comment]
There is the demo for my question.
https://codesandbox.io/s/elkjs-demo-forked-fn165y?file=/src/index.js
Click button1 to show g1 graph.
Click button2 to show g2 graph.

**Comment by soerendomroes** [comment]
You are using elkjs 0.7.X. Try to set considerModelOrder instead of considerModelOrder.strategy

**Comment by fanmingfei** [comment]
I updated to 0.8.2.

**Comment by rpelorosso-sv** [comment]
@soerendomroes did you ever find a solution to this?

**Comment by soerendomroes** [comment]
> @soerendomroes did you ever find a solution to this

Yes, my solutions mentioned above should work. If they do not work for you please specify your problem.
