### ISSUE TITLE
Keep the node in the same position when its parent edge is deleted

### ISSUE THREAD

**Issue by im-amir** [kieler/elkjs#188]
Currently, when a parent edge is deleted, that child node jumps to the top. Is there any way we can keep the node in the same position?
Current behavior:
https://www.awesomescreenshot.com/video/11235492?key=46cb841a697d83c0dd7454612b1c537b

Expected behavior: 
The separate node should not move to the top.

**Comment by soerendomroes** [comment]
For future tickets an image with your problem and your desired output would be nice.

As far as I understand your question you have to set an ordering strategy for separate connected components.

**Comment by im-amir** [comment]
@soerendomroes I added a video in the description for more eloboration.
I might be dumb in understanding the elk documentation, but can you please guide me on which ordering strategy would work for me and,
Is this the correct way of using it?
`layoutOptions={{
   "org.eclipse.elk.layered.considerModelOrder.components": 
   "org.eclipse.elk.alg.layered.components.ComponentOrderingStrategy.NONE" // (also tried "NONE")
}}`
Btw, I tried all 3 strategies (NONE, INSIDE_PORT_SIDE_GROUPS, FORCE_MODEL_ORDER) in the above format. None of them brings any change to the UI.

**Comment by soerendomroes** [comment]
I suspect it would work like [this](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=user-hints%2Finteractive-constraints%2FinteractiveLayeredLayout_hierarchy_pseudo_positions) by setting pseudo positions for all nodes.
