### ISSUE TITLE
Is it possible to use InteractiveLayeredGraphVisitor?

### ISSUE THREAD

**Issue by kasbah** [kieler/elkjs#190]
I was looking at [InteractiveLayeredGraphVisitor](https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/InteractiveLayeredGraphVisitor.java) and wanted to try it out especially the [LAYER_CHOICE_CONSTRAINT](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-layering-layerChoiceConstraint.html) setting. The docs on that mention using `DiagramLayoutEngine` for that. Is it possible to use this with Elkjs or do you have to use the Java ELK at the moment?

**Comment by soerendomroes** [comment]
It is not possible using elkjs. You need the Java Version.

**Comment by kasbah** [comment]
Ok, thanks for the answer.
