### ISSUE TITLE
Align edges at the same height for "branches" with different number of nodes

### ISSUE THREAD

**Issue by giorgosera** [kieler/elkjs#192]
I'm using react-flow and dagre for layouting but I'd like to switch to elkjs to position my nodes. 

Now I managed to create the following layout

<img width="946" alt="image" src="https://user-images.githubusercontent.com/752207/196290444-aa501dc8-2862-4257-8690-93da52d0ec68.png">

As you can see the edge of the rightmost branch doesn't fold (don't know if this is the right term) at the same height as the other branches. I'm guessing the reason is because the leftmost branch has 2 nodes but the rightmost (and middle one) just one.

I want to achieve something like this

<img width="693" alt="image" src="https://user-images.githubusercontent.com/752207/196290744-109e14ef-fea5-47d6-bc15-bc507e3e9d8e.png">

Would this be somehow possible with Elkjs? I'm a bit lost as I am not sure where to start to implement this so if someone can point me to some documentation or examples it'd be amazing. 

Thanks!

**Comment by soerendomroes** [comment]
The default layering strategy begins from the sinks and does therefore put nodes in the last possible layer. A layering strategy that does it the other way around will be added in ELK 0.9.0.
Currently, I can only think of partition (and interactive layout which might be too complicated for this) to solve this [like this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUDiANYB0BM+AxnDBAHboAiA8gOoByRtzAZxgE8AWQgiQ7KCKgUBcKMDg4wWdN3asAogGUA+gEFurfdtYBxPWgD0NtMxBY0AM2hoADvgE4mcZYxMngCuHhA+AkSYuLBMYPKKyqrqaNzaACqc7ABKANL6ugCSogAKADLaABq29qw4LsDBIHBooJCwiEgANA6IeA5MOAJoAO4QTQSeUBLBtDhofWgCwEjz0eNwRB7AUAwMzDBxFMD0MABuSeiKwThEREwS80wAjGgA3kRoX547e4GH8W2u3ggXQz0+30wACNSGgAEQvOFEAC+JAIYCerwAtAA+NBMABMaIx+OxeKYAGY7g8RPiCe8IV8gX8DkdmSDmOgid8MMAYSB4YSkTyUcSnvTcfiACz3R74ikMnns-ZMAEUZWgtDcyF82EIilI1GEEmUtCSpgAVlltKYUsVOv5gqlhrF0rN5Kt1qeFvtX2hesthqAA).

**Comment by giorgosera** [comment]
Thanks @soerendomroes. I will try the partitioning idea which seems promising. 
 
I noticed that when I use the mrtree algorithm it does what I want but the nodes are not centered. [Here's the link](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGLhAOQF4DmKSkdAAsAth3gcRSdEgCmsjrgC+OCAGMhkPNDn1YAbXYQwrGPAT0AjNjAB3GMPgBmAAxYwQ2ZB5D0zt-gEAEayeBIATBxgKkYQpnCI9OE29tCOYK7unt6+-tGqxnFQCRZOKQ5C-llePn4ZLvmxJsXm9AAs5WmV9dU5da6NhUVmiQCsnemZHjW59YND8a0AbBPdU9m1eTFDzSMWAOyrVdN9W7gAugWy0DyyzGCGhYuIstbujGRIanfw+onWYEuYHQBCQt3Q9z+FmSgPmwxKsmS70+30hiRhQJBYNkEN+iTKsO2xmeCFkZWRpC+Pwe+IQgPcWPBaIsHUJBXh5lkHQpVOZSTpmNBTLxFnGbKMJNk4x5qJF-PpwKFOL5K3FTxaLxWMupUPaAoZStxNIOArhuwRh21fLFguxRt1hzVxI1pIAHDYPpTZcb6KrbcKfY7ztELiAlEA) for the online editor. I tried to change the alignment to CENTER but I saw in another issue that alignment is not supported for mrtree. 

Any other idea how this can work with mrtree?

**Comment by soerendomroes** [comment]
Your graph is not a tree. Therefore I do not expect that MrTree can solve this. Maybe if I find time to implement a bachelor thesis on MrTree that was done a while ago.

**Comment by giorgosera** [comment]
Yeah you are right! Thanks for the helpful pointers. I think the partitioning idea would be the best solution until the new version arrives. 

Quick question: Can [this graph](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGLhAOQF4DmKSkdAAsAth3gdCRAKZJp0DjgidpeANYA6aJDkBjWg3FgOAEQoB1AHKL2x3Q0YxZAWRTRVFJO6QbG6JATo0jxERhyWFCYAogDKAPoAgpYmcVEmAOKxNsrGUrKQ9Dy+-oHBoRKWUQAq5hQASgDScTEAks4ACgAyUQAa2cocVARItAb0BUUE+pAAbqVG-qTSuAC+SmC6QpB40HL0sADathCsMPAI9ACM2GAA7jDC8ADMAAxYYELSkDxC6M9v+AIACNVMwwAdWEEAB5-YxXDgrAC6YDWxzApzgiHoACYbvdoI8wK93p9vr9-u9CCC8GCIWBobCODiEYjKcQyJQaHQmCxjEMRoJuRMNPzRtyjJcURBUTkTlBMRcnniHkIKR8vj9YcTAdTaZDpDCJPQniy2SRyNQxmDWINhmKGMLRYLDPBsVLpeschjzvQACzKgmqokA0matVU0HwOkMo2+02A82cq2820CsaOu3O+hGJ5SmWy71YgCsAcJ2tD5ODbN1Uf1hrhRfjUg5lu51r5mfThRFnfFrvd+a98p9ADZS0HyxrK9qIzTa-SDYz6COm+yLVyHCmnV2itu+2A3SsPWjCxcAOzjtUVrUA2d6hf1plnlnS3Cs3DyHjSWm2U-Sa7vIwZBILo35Rli1xgKy9LDF+6C0liuJQSinrosOiDSLigHAaBCEXEh0HoLB0jweBioIMhg5oWcGFKthpAgWB4JYkqUHvERSBwXhfoUciVF-v69GMdxBHscRpHMRcJaUahf4lkJuFkTivFiZxJHcWOMm-uhCDSGOClMQcWL+mxMFqRJRnnrxKHaTRukXgZ3HSYR4ncReWlDnZ0gABw3EBDGKZJy4qWZXFKe5fFviAKxAA) be center aligned like in the mrtree example?

**Comment by giorgosera** [comment]
Nvm found the answer to my question using `'org.eclipse.elk.layered.nodePlacement.bk.fixedAlignment': 'BALANCED'`.

**Comment by Sharmil001** [comment]
@giorgosera, can you share solution? I am getting same issue.
