### ISSUE TITLE
Add inbuilt bounding box for subflows instead of manually specify width and height in styles 

### ISSUE THREAD

**Issue by Prasy12** [kieler/elkjs#193]
Current scenario:
User needs to specify the width and height of the bounding parent box to get that beautiful subflow boxes. 
![image](https://user-images.githubusercontent.com/54540812/196361711-b3d2c25a-b332-4389-87d3-379af0aaeb13.png)
This becomes hard when we have dynamic number of nodes inside a subflow and manually adding these styles will not be feasible. 

Expectation:
Add the subflow box without specifying the style property. If it is a subflow automatically add the box shown below based on number of nodes 
![image](https://user-images.githubusercontent.com/54540812/196362144-2a65e108-ad8a-4a2f-b183-bbe6e075b995.png)

**Comment by soerendomroes** [comment]
Can you recreate your problem in elklive? I tried to [reproduce it in elklive ](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGAOQF4DmKSk6ACwC2beG0JEApkknQ2YAL44IAYwGQ80GfXgBtXBFYx4CegEZsYAO4xB8AMwAGLGAGTIXAegfOwajVqSOmD6EGFgRnCI5gD6Fi420HZgTi5uHl4+SgZhkSaxAEyWicmpru6e3imOCjkAutnhedFFCbYCPmkVmdWKyrlQUab2xe2d5RlVToq4df2yXJLMITnNCJLxYIxkSCpLetEWYHNg6ARIi+jLui0Ix32rgyaSrVs7e9eHdydnF5JXB2G3xmEDqIAUQA)but failed to see your point. (elklive may be shortly unavailable today but not for long).

**Comment by RAFA3L** [comment]
Just need to apply the width and height values generated by elkjs when prepare the data for reactflow [examples](https://github.com/wbkd/react-flow/issues/5)

**Comment by Prasy12** [comment]
@RAFA3L Can you provide an example sandbox for this? Still not able to get this done
