### ISSUE TITLE
How to space parallel edges going into the same target node port

### ISSUE THREAD

**Issue by giorgosera** [kieler/elkjs#194]
Hi everyone! I have a graph which at some point needs to represent a conditional branch like the screenshot below. 

<img width="427" alt="image" src="https://user-images.githubusercontent.com/752207/197240583-c628ad57-8dc7-490c-974b-6d4dfa76be2c.png">

It works perfectly when the branches have nodes on them. However, if I delete those nodes the edges get squeezed together and they look like the following screenshot

<img width="353" alt="image" src="https://user-images.githubusercontent.com/752207/197240318-74f875c4-aca8-4205-a2c1-89283767cf76.png">

Possible solutions I've tried:
-  tried to add some invisible nodes as padding in case no nodes exist on the branches (it works but it requires some extra effort)
- tried to add labels with a certain width and height to force the edges to seperate (didn't work)
- tried some of the layout options like `elk.spacing.edgeEdge`

Is there a layout option or another method to make this happpen? 

Thanks

**Comment by soerendomroes** [comment]
Please recreate your layout problem in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html).

**Comment by giorgosera** [comment]
I recreated the problem in elklive but it works perfectly there. [Here it is](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMBLhAOQCmeA1gHQE8AcxRJI6ABYBbDvA5jh-LgGM8kKoy7K+-QkS5Iu0DjgiceA6JCMraDOWA4ARCgHUAcqfZPLe4obG-gbi9EqM6EgE6FzCRI4cAJIeACoAogBKAIIAwimJAGpp3ua+usbCXBlktGEJFBkpABIUAOIUHlkAMiXm3Lr6gdD8pPT0qlyMjARIRABCXPTQVCiQ9OiMCZGkXL0WAwFGw4xUBCprShVcHijQXAvoAO5ci12Hm-IAzAAMe2UCgyO-Hoty4AAVCCouNJFuh+AAjAQAM0gAA9jFl1MJ6DD1gk5t0sh4cmlnH9+gDDkEVEQ1PcjAReBd+BEojE4glnGkwc0APoAMUSGQAyilyX41owYFxhTwkV00JpBHZIAA3aK7eTbXZmPoqBhSu5IACyoLwFCQRpZkQ1HPkHgoXOFvKJzl5pNaaWF5K0pzZXByDHGdmMgekK3G6w+TiRQi04t0JzOzJBdxudwSAA5frr9gIk+cwspoJU0iXNU5sxxcABfXUqSSQPDQIz0eAAbR8rBg8AQ9AAjNgwI8YFJ4D8sGBJFxIMJJOhx98wHWu1A4Ih6AAmIcj6BjsATqczucLg9LlcQAC6uquzDAndK3fXCC4g8njDISChd-bG8HYGvMB0BmSoNg7DdtwAydCHhHgf2AGJUVPDgun7Dga0vZdczAJ9ey4bd30-b9wL7f9AOApBQJ-CCECg-ACFgvB4MQ5Cuk3dDMJrXBLxAGsgA). 

However, in my code I have the same configuration (AFAICT) but the edges have zero spacing between them. 

Unless, there is something special about elklive I'm guessing the problem is somewhere in my code!

**Comment by soerendomroes** [comment]
I usually use KLighD for styling my diagrams and updating them. For me this looks like a problem with the diagram updating that somehow needs to place a label and/or a dangling edge. Maybe something similar happens in your framework.

**Comment by giorgosera** [comment]
Well actually it was indeed an issue in my code.  I'm using React flow and by accident I was giving those two edges the same id so the library was probably placing the edges on top of each other.

It's not an elkjs issue so I'll close this and apologies for wasting your time. Thanks for helping though, I really appreciate it.
