### ISSUE TITLE
Can I use the "layered" edge routing in conjunction with a different node layout algorithm?

### ISSUE THREAD

**Issue by timothypratley** [kieler/elkjs#197]
Hi! 👋 

The "layered" algorithm will route edges based on `org.eclipse.elk.edgeRouting` as POLYLINE, ORTHOGONAL, SPLINES... which look nice. I'd like to apply the same edge routing to other layouts. How can I achieve this? It seems to me that the code to do the edge routing must be there so I could call it directly somehow without positioning the nodes?

**Comment by soerendomroes** [comment]
Often the edge routing relies on the information where layers are. What you are searching for is standalone edge routing https://github.com/eclipse/elk/issues/315 which is a little complicated. 
It is not available elkjs but Typefox developed a bridge to libavoid https://github.com/TypeFox/elk-libavoid that could deliver this feature.

**Comment by timothypratley** [comment]
Thank you @soerendomroes 😄
