### ISSUE TITLE
How define a default target node position when source have multiple ports

### ISSUE THREAD

**Issue by RAFA3L** [kieler/elkjs#202]
I would like to position the target nodes always like the 2nd example

<img width="730" alt="2022-11-22_14-19-42" src="https://user-images.githubusercontent.com/3952265/203395038-b1eadbd1-7f42-4b9c-b520-9d8b7332ad69.png">

Thanks in advance

**Comment by soerendomroes** [comment]
Can you please provide the underlying elk graph?
My first impression is that it is not possible and would require a special node placement strategy.

**Comment by RAFA3L** [comment]
Yes, I think this is a decent solution [example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUIWDgEoQCucMAdmOgMoAKAMgJIByAokySADWAOgIx8AY1oQ66ACIB5AOpcBIhDDzAoEhFgASwOgRD1GabgGE2AVTk8A+pf0c2c8j1U4hwzLnwEwhIQSAAOwFIwMsKhEADOcJYh4ZHRCVDAcDhgWOhsPABiACpERHQQBDhoOAAewGEgOACMaADeRGidaOWV3S3tXYMY2NRwaADacTAAXjjoTQAMCwA0aACsCwC6HUOdsVCJMunA9HBx6AUcABo8cg4K5PbkO7v7Y6H9aAB6b8JTlcwFDYivo0ABfF5DN5oUIAJja31+-zmaCYQJB4MhYLQkJ6VTo8IGu2GWFGEyms3mS1WG22xJh0EOdGOp3OaEuNzuDyekMG0I+CJ+jL+MABaC4DwxEMG0q6pHxTRi8IAtAA+bqwmJNIgQsoVKq1eqhRqEyHeER+PCEYR4liYCQ4JA4OhwP5wDJZHLoXhFJQPADSDiYHAAsuweFdcfq+m1eV0-GTJjMUYsVustnG9oyksz3ScXWyObd7o8eM96fzPkKDiKxWjgaDZa9GTDCYjhcjAQ3MTKcYM8RrY-SEzRycmqWnaZmGQccyyCxdrsXuWXp5XBUjRSiJeQpVio706ABmIfEkdjJOUtCpmkZivZo551mLzklnn3g4wqubsU7vcys0CDIPolTQNUNS1QDgLoRUBXA49IN1AdDQaHATyJTpzV8bArUCW17UdZ1XWOT1cnFHhfQDINQ3DSN+2jGDT12c8xyvG90zpYk3jnJ8F3ZJcuVLcsuJbAVWnbGtO1RdFGzXUS22rYity7f8umxA98VNYcRlHS8U2pDi5NnR8MmffjXxXYTm0-MSJKU39JVkj93gUn8UXrVTOibboGPQ6cWL0idb046ymXnM4X2XISjPeb8O2U8VHJ7NSoIVUD4M1D5UoguEwPVBCssGeUQLg-Kj0Q0ogA)

But the symmetric option look better, and for some reason my code make it symmetric, the idea is avoid the overlapped edges

**Comment by RAFA3L** [comment]
I see the the difference between NETWORK_SIMPLEX and SIMPLE, I'm using SIMPLE

[example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUDiANYB0BM+AxnDBAHboAiA8gOoByJ5FCGHmBRaCLAAlgTAiBhMw6AJLcAwgBkAqqwCiAfVUSl61gCUdvUpUy58BCrQhIADsHqMmFZxADOcVU6u7swUflDAcDhgWOjqOgBiACpEREwQBDhoOAAewC4gOACMaADeRGgVWfw2eIQUaRkACpi0OEg4THChcOGR0ejcOomc7KYA0noAykoAso1xABrllQ2ZTMVllVtoy9to3lD+zGHA8nA+6PFKCzqseqO6prvbB3D7G2gAeq+hMBnok3YmkSEjQAF9nltXvsAEylL4-Hx-HAAoEg8HPME7LarNBMOGbPYYbAQACubwA2kiAF4otCFAAMDIANGgAKwMgC6kMqrwCTBOZwuaCuNzuDx0TyJ+2gb2cH2+st+-zQ3FG6IhW01lUIYDWhS8cIAtAA+PEwryFIgQ1LpTI5PLOAoE55WCg1Oz1O3NNxtDpdE59GJoaZzOLPXHrUo8ip8449U6dYWi273UyPGMyw7veGKw7KumA4Gg7V7aHOAkIpVIlVFjWY7ErO3m6PSuMChNCy7XVMSqVE8sKxHIgbqkuYiPNpgAZlbA9l-MFSe7YrTGbbspzJSr+ZrdLVpnrWtdBD1eINFbQpvNlpPZ-WlqvZpnt5tuId+Rws8JFTdHrqqw+q07SdN0vRRMGgzDKMEyhvMOhLDiU4bJmmbtku5wrr26aSmhm7yrmw61mi44btml7bnmAYjiGJEYlqjYVJGLrSjYZKUjSdKMiy7JcnhhyLp2y4ij24o4f2Zb4UO1Y0QeR7zuRlZUQWqLFvRlSlniU7fvxRwduEXYiaufa6VuO7USqcmkRpd76oaT43vKtmOcaz7TreWy6nZBHXi+Tlvs2H5OjgAAsc6-tU2C1PYgEtH6oGBhBAKzPBk4ZOe4UvAu8YGcJKZieuClytJu40XW1mSYphEycRamaViaVrCxRJseSaBUjAtLoNxrIctyZF6RhyaiWuuEDWZyl7qOh4VVlVWUURhZ0fVjV4jprEkm1HVdfSTK9XxA2CblmFGdhhWVcV1WlZZY7qRUmleee9m+RaTmeaeTXPW5Hk6h9T0+d9-kpEAA)

And the behavior in reactflow is like the red edge because I don't have control over the edges

<img width="640" alt="2022-11-22_15-59-12" src="https://user-images.githubusercontent.com/3952265/203410102-fb7933c8-8be8-4755-acdc-ba4768d46775.png">

**Comment by soerendomroes** [comment]
Is this solved then or are you still having open questions about this?

**Comment by RAFA3L** [comment]
Thanks @soerendomroes I think this could be closed
