### ISSUE TITLE
Internal nodes with fixed layout

### ISSUE THREAD

**Issue by RAFA3L** [kieler/elkjs#205]
Hello all and Merry Christmas!

It is possible to declare the nodes inside a group as fixed when some of them are connected to another in a layered parent group?

For example, I would like to fix all the internals nodes to the same position to simulate a collapsed group. For now I set the nodes to 1px but when there is a lot of nested groups increase the size of the main parent

[Example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEBTEBrAdCYATwygwBMAoBGE4KAYwUIAlgA7MkGNsdASQByAYQAyAVQAiAUQD6Q5nxESASlIEUKbCGQxoAzhACuDXQG8CAIyxoARAeP0MNgL4atOtEbh6YH0xTRAtAB6YLQAMxgAD3I0AkIvAH4AoMtrGy8fHRsUwPddNgBGNHNgKxBbIpdctHzagCYStIqbNnrqoMwyMALigFoAPgaKVwpyHv0jEzRBz0NvXwxcIqA)

<img width="819" alt="2022-12-27_11-34-51" src="https://user-images.githubusercontent.com/3952265/209689105-640df7ee-2a6f-4b5a-bc39-4d6364dbb23e.png">

Thanks in advance

**Comment by soerendomroes** [comment]
This is not possible. If hierarchyHandling: INCLUDE_CHILDREN is set all hierarchy levels must use an algorithm that supports hierarchical edges, which is currently only the layered algorithm. I advice to split your edge in two and add a port on the outside node.
