### ISSUE TITLE
to remove overlap of edges

### ISSUE THREAD

**Issue by anjali-venugopal** [kieler/elkjs#211]
**Describe the bug**

Edge is getting overlapped 
![image](https://user-images.githubusercontent.com/75406156/215045603-d65e833d-1bf4-4aa3-96d0-faa4c3479f0c.png)

The connection should go from A to B and A to C but it is coming as a single connection and is splitting from a point instead of coming as two connections.
![image](https://user-images.githubusercontent.com/75406156/215045952-72ac5375-0aeb-4dff-ac29-270bd9d96bf1.png)

Have used elkjs version: 0.71. and0.8.2

edge routing used is polyline and node placement strategy is Linear_segments

**Comment by soerendomroes** [comment]
It looks like mergeEdges is set to true. Can you supply a minimal example using elklive?

**Comment by anjali-venugopal** [comment]
mergeEdges is set to false.

"elk.algorithm": "layered",
            "elk.layered.feedbackEdges": false,
            "elk.hierarchyHandling": "INCLUDE_CHILDREN",
            "elk.alignment": "DOWN",
            "elk.direction": "DOWN",
            "elk.aspectRatio": 15,
            "elk.edgeRouting": "POLYLINE",
            "spacing.nodeNode": "30",
            "layered.spacing.nodeNodeBetweenLayers": "30",
            "crossingMinimization.semiInteractive":true,
            "nodePlacement.strategy": "LINEAR_SEGMENTS",
            "spacing.edgeNode":"50",
            "elk.layered.mergeEdges":false

**Comment by soerendomroes** [comment]
Can you build a small example graph that reproduces this problem in [elklive (json)](https://rtsys.informatik.uni-kiel.de/elklive/json.html) or elklive ([elkt](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html))? Otherwise, I can only guess what the problem might be.
