### ISSUE TITLE
Libavoid algorithm support

### ISSUE THREAD

**Issue by EugeneFi1** [kieler/elkjs#214]
Hi! Are there any plans to support the Libavoid algorithm?

https://www.eclipse.org/elk/reference/algorithms/org-eclipse-elk-alg-libavoid.html

**Comment by wirekang** [comment]
Hi, can I ask why did you close this issue? Is elkjs support libavoid? or impossible for some reason?

**Comment by soerendomroes** [comment]
@wirekang In the current setup how ELK (which is transpiled to elkjs) integrates libavoid this is impossible and there are already libavoid integrations for Javascript.
