### ISSUE TITLE
Question: How do I Increase distance between node and an edge's bend point?

### ISSUE THREAD

**Issue by agiron123** [kieler/elkjs#216]
Hello, I wish to increase the distance between a node and it's edge's bend point. Is there a way to do so in elk?
<img width="649" alt="image" src="https://user-images.githubusercontent.com/1031759/222606659-2aa479ee-cca5-4612-81cd-092271c546e5.png">
Ideally, I'd like the bend point to be about 50px to the right of where it is above.

Here is a screenshot of the graph:
<img width="1885" alt="image" src="https://user-images.githubusercontent.com/1031759/222606597-adf28df7-0c6e-4044-842a-4dc579e7efd4.png">

Link to elk graph playground:
https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGLhBAOQF4DmKSSOgAWAW07xOhIgFMkM6JyxsOHBDLwBrAHTRI8gMa0GCeAgBKASQDiACQAq2FasQadPSL3qiZ9TGYBhAFEAOXsg8yd2NUYqAgNIel5tehRoGRC0mVMwAEYABnzlaIgEWPjE5IVeDKycgqLnVTK4hKSUrMz0gCEZdAB3GV8AGWI5RnrCnBdXLW1pOQUO9IAFQgMZHz9tACMdADNIAA8FAEE8T29ff0Ru0+HTkOCAEWwS2Z1ytuSqAXRGADKpCQqFI9D0SRyAFYiu8yjI4kgCOgZAEGPQZEYFGjRL8MX4JvB0EhSDJpi4WhV2gYULiGNccXjrtDYRAAL7kgzCSB4aDyejwADa0VAMwgMDM+Vy+wAnAA2GQAdkVAFodjsAMwADhVABYCIrdSqtYUAEwqhS66DQBW6nYEXJat5isD9GAieAaqbvCDCGSeYToeC5GHRDkin1QOCIfIa6CmmX7dIqxNQ3J6gwEHYppUEFUGAwygwana6grF-LOsVu6AesBe1liv0BoN5UOqcOqUViiWIO1Sgy5OXmnYyU2q-WJlUEDUyI1Q6D5BMGKGKmWxmVVmY1usN8kzZu8QPB9scTscbszXsIRX7GRa3UKc26jUEPO6-amvNazHZ2dQjVlQKAg5WgHYtxcHdhE9b0XUPY823yMN9zAS8XGvLV4zlAgZCzFU5VvOU9XlfJpxkKEDGnfI5X2XIdgLOdYwg1QoJgxsD39I9WxDJCOxQtDVGvHYoTvGVTX2DV8I1GUjV1OUNXNGSdnTD9B3IzCtVlAhmI4Vj61gptOIQnjkIjF1r3SNdExDFU4x-PVFQMc0s3yHU31NAiDHyfYCBlLVFR0iA9L3SN4O4092X4yNrxkHYtTlENFVI-JR1kgioWNRU5Qy3VExlKFEzkmQ-MC113Wg-T2JcMKT14s8ovM6N1GgDU5V1KE7QtfVs11BiyJkfZ83EqEtRcrUnO0lCWPKtipo4GrENMrtoqaiTSwIeNVUTDa9S1Ubp2gGVoHzAjTS1Pz5WK3JSuCgyOJbWqlovFazCTCjipldNFTTd85RNFNdT2obX32fY5QLKFTV1G6ZsqubfSM8K6sisyeya3JoFlM7MZVfYCx6-YoRkFNCkG3Uzp2OVR3XOdJsjW6qtUBaTL41Grya017XGwnjswzM9QUPMCHG9NvII6AtR2fIoQAyt4bK2sKpCuDEce1nlsasxfPVLKDB1dVzr1MGMofUGUzXRVTVyOMaOEmHFdm0LVcW9Xns1xANp2T6CA-AX8ko3LyenL0MszL12pLQ1oAMe3dzu6rnZZ+q2fQprMxwxNAPzGU8Mff2U2wvMQ0hssOugXXY6V+OmcTiKwDZXAAF1yWqGRmDAYUXQ1tGtZlHXwf1uKZSN7LjQ-QaZQtq2bf2YSVSlWUFWVNVNR1fVDWNM0LWgK0bTne1HVKxgyCQDZ28FBBtZ2XXB8Nj9R9Niep+tm1Z6hBBm8jdACCQGp-iFBAC9LrL3VNqPUBojQmiXNvXetoD5Ok-q7CAAkODXivjfFed9jZjzNpPSe09X5z1jPGRMyZUwqUzNmGUuZ8yFmLKWcsXoj4nzPgA9BA9MHD3vibce5t8Ev1tu-RBYpv6-z6OfQBcYExJmJuQjMeFqGKjzAWIsJYyz+yYcIlG3d2ZmA1BqACMhpbD1NFCHYz4JIZWobqVUYFsogVyAYRc+d+yOKHCOMcE5fKDRnHOFUC4lxFlXOuaSzDgSsI7oA6UwDVSgLXhAze0DLTWjgQ6BB8tRF-wka4wcw41SePAVOXx85FzLmCRuD+KFzzIJeh7MC3tfZ5wDjJZyId8wznyBHa+VpKK3nvI+eMepXzvk-N+X8tlyKAUVMBUC4F5bH3CW3Nh9Tcg+zJkY5pQcOmhw6V0qOMctEuEyeIgBfSHxPiGW+I2X5jTjP-FMmZYFKlPRqe7G8d5zmDJfFcj8NyfwGD-JMoC+QQJgRVJzYWBgebGmju+QW04RbzzBoqCWUsZZMPmSwpZkSzkDOfMM65YyAUTIAsC0F4FDmqGOf-SJELuYLhhfzAZQtEVixRZLaWstnlINQrUhA+jDHGPBWYixBicw2JVHYqEDinGFEophDyOE8IETBsROUpEcIUSojROiDFdRMUxYsiRQCl6xNXuAjeUDzTJL3naNJ3KRE-yyQAhV2FcLZhVURXK6qyJaoINRWi9ENj6o1A67Rbse51K9qsxpGziJbLaWHTpAFunRzVCJYq4lJLyRknqeSik7QqTxrkdSEstJhNPtii+nsGnrJcS04O0t2nhxTfssNRynUnMicJUSWapK5rkgpAGykjZqRGmWnO7bqm8reenYqElVSFlznG+UVzi5QxDFaXW6be0SX7WlIdSki1jo0uWw1laJFzszounOPUV2FxVOu0uW7wbtqpZ2mlF8e2Zr3Tmg9BaR2qRLeOzSk7DnTpQeKdGmMxKYUGnjYlH4iYk28nqCmVNir5Fpjun92bpL-uHce4Dp7J3noiRfDGWM4O43xkbZD65UPk0lhhmm+o30cGpRI79Ylf34bzYewto7iMTu0uBhqkaEDcb7X+-jAGiOltA0LPu18OEGy4dgx+fDLYCLfhW8jkmM08bwwO-NhGhMKfLZSjjH6JHsL1pwkePDcHPxnnbMTKdBIcy5lChlfM4XQBZYOJF4sOXotIpZGU1kMp2WJjYpy04pZuQIB5Ry3lfL+T01WhAdKfO81hQLALCKgtstRZyzRGSbMAIi1F2yEtYuOWcol6cyXPJpb8gFdzOjU5mGq7RaLdWHLxbGs1lLXkfLtcfTB7G8HaNIdkaTNDzHqZYbY2RrLvWbIxcG411yI3WvjYy1ZiAnGAGUdgzjBDBN6MLaY5TZbtMp3id0a4OKCVVzJVSnm76mVR65VlAVfYRU-IHWjWsv2mzWlNqTXsnpmWJGxXiolD7fi5Lff8r9vKAOgfpK-pVyJNaY11oh42nZLbI6w86xG57-KDGziFaY8xRsxXWNsZTaVCVZX5wUK1dqnVaY9T6jhAaQ1CajUSxNOHACTVKjNWA9ekCt42tSYfI7YATuRO521Dq2Z+cZg2P1QaTlRdjQl5T15EmcvQr8wVwLotkWlbC7jNRG1xwph8sdQG+0NpHROpbc650FSfUl7S7zVv8vMqK3bkLaKuWq-VxfNa+pNpu52p7oWh1joGFOv7y6Qezczok4nl3W13e7S9xn33Z0LqB-TFehd2dl351XUXGWG6y4VzWxIovyftoe72unn3We-fV6uux47eOL516zkuu9TeH1Ps3eXV9+fINRl7v3ezanHM4Kfvw1zGU3obEi19H6eb-oySBk5EGYMIZQ2D9W5TGCt-cJ31pghgix9q4nwgQ-H0T+rLP1Igvx1CvwIFBnBhXDv3AybhADZCAA

**Comment by soerendomroes** [comment]
Have a look at the [between-layer spacing between nodes and edges](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-spacing-edgeNodeBetweenLayers.html). There are many different spacing configurations to consider. If I don't know which to use, I consult [this page](https://www.eclipse.org/elk/documentation/tooldevelopers/graphdatastructure/spacingdocumentation.html) which lists them all.

**Comment by amit-debugger** [comment]
@soerendomroes  What you suggested works for me

**Comment by soerendomroes** [comment]
I still suggest the same `edgeNodeBetweenLayers` spacing as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGLhBAOQF4DmKSSOgAWAW07xOhIgFMkM6JyxsOHBDLwBrAHTRI8gMa0GCeAgBKASQDiACQAq2FasQadPSL3qiZ9TGYBhAFEAOXsg8yd2NUYqAgNIel5tehRoGRC0mVMwAEYABnzlaIgEWPjE5IVeDKycgqLnVTK4hKSUrMz0gCEZdAB3GV8AGWI5RnrCnBdXLW1pOQUO9IAFQgMZHz9tACMdADNIAA8FAEE8T29ff0Ru0+HTkOCAEWwS2Z1ytuSqAXRGADKpCQqFI9D0SRyAFYiu8yjI4kgCOgZAEGPQZEYFGjRL8MX4JvB0EhSDJpi4WhV2gYULiGNccXjrtDYTNKd9tNVaj0+oMRmMkIS8oUwAB6UVgezCGRgL6VMAkUhgAjyfBoTTy-YCXAAX3JBmEkDw0Hk9HgAG1oqAZhAYGZ8rl9gBOABsMgA7O6ALQ7HYAZgAHF6ACwEd3Br0BwoAJi9CmD0GgbuDOwIuQDbxtYH6MBE8D9U3eEGlnmE6HguRh0T1VqLUDgiHyfug0ad+3SXrbUNyIYMBB2nY9BC9BgMToMfp2wYKE-ymZtOegebABdZNpLvDLFarqhrqmtNrtiBTDoMuRdsZ2Mmj3tDba9BD9MgjUOg+VbBih7qdTad85mi7Lqu5IzBuW55DuHB7hwB4zEeCDuvsMgBsGCixsGfoEMOwb7NGw4BpiA5PlCfqegUBAutAOz-i4gHCPmhZZmB5YQfk1YgWAsEuPBAYti6BAyP2XouohLohq6+QPjIUIGA++QuvsuQ7KOz5NjRqh0Qxa6gTIpYsZWbG7hxXGqPBOxQkhTrRvsfrCX6ToRsGLp+rGDk7D2OFntJvEBs6BDqRwmkrox666Zu+mQRA0EQCZHDwek35tpWXrNgRIbugYsb9vkQZYdGIkGPk+wEE6AbugFEBBcBdbMduhlQcZdbwTIOwBi6lbupJ+RXo5IlQpG7ouv1wZtk6UJtk5MilRV2a5vRwXaS4tWsextZZs10B+i6wZQimcahgOwYqVJMj7CO1lQgG2UBpl-kcRpc1afdHDLQZq37k1DYIDZU4EC23ptn9IYBldD7QE60AjiJ0YBqVrpTbkM1VSFOl6XV70wZ9ZjtjJU1Oj27rdthLpRp2wYg+dmH7PsLqjlC0bBkjj0Lc9xZheBb1GWth5fbk0DOjD-Nevso6HfsUIyJ2hRncGMM7C6V4-s+d11sji2qK9kVgNFnFY4g0apjd4uQ7xfYhgow4EDdPZFSJ0ABjs+RQiRc6s7NS7zdVTHsxF9VRY161fSVvqDQYQa+rDIY0-1KHU5237utGuTNgp5lMx7T01T76Ncx9gdmH9Oz4wQOHm-kskjbLD4Fv1fYFjtk7htABjp0BKNLdnK255j+eIH2AltqRI5OkJqHl52-HDpW9PTrt0Ch63nvtxrnec1BuAALrklyzBgJaWZ5zzBdOiHtPh61TpR0NkY4WdToJ0nKf7OZXoOs6bqej6-pBqG4aRjGcZoAJiTM+VM6YZqMDIEgDYu9zQIGDjsUO59I44WvrHO+D9k5JmflCBAW86zoBVDUf4FoEBv3hp-X0gYQxhgjFGd8gDgHJjARmfB3cYp63gSfRBZ8v4oOjjfOO9976P2wS-JsLY2wdi7B5PsA4nRDhHGOCcU4ZwFggVAmBpCEFIL4ZfVBMdb7xxEVg1OuC2E2kIUgYhsCyHNlbO2SWMjexCQUe6Yco5xyTmnOXdRFj-bczgl9P0foSIyCdpfaMUIdjoRsv1BRwZvRUSGhRXIBg3zjxPGk88l5ry3hKmdR8z4vSvnfOOL8P57IaOBFoveZDHQUO9FQn+tD-4MPjImZhaZWFuysTY0hWSzwXh9Hkmh94ikvjfB+Cpv48EcR1rFW0QcqLF1LmPCuDkso1xHI+fIDdEEJlkohZCqEWwhkwthXC+FCIpWkqRd05FKLUTdpAmpMhbGF1WTLcJGyq67Nrrs-ZTcW7+JcH0votjjkoTQucrCUc8KRhucRe5jyqJzIxhw3uCEkLQrORhOFOEEUEQMERO5ZF8gUSol6A2VsDDG0jM3bCFsHzW1fjTd09tHbO3US8zR7zSFQtOehC58LrkktuSRcllLqKgtUOCkhdSaVG1fAys2pzLastthyh2TsXbovYbrLFISwkROpdE2JoTByJK9MkqEqT0mFFkrxfKAkhIiRpuJF0kkBIyTkgpJSKlgxqV5W82x5CP5NO-jQv+9DYwdJASmbp+rLFEIhaQ51-FBIDndWJEaXqpK+oIPJRSykNhBr9MmgJh8gkFxWbkEu3zMmbOrk7HZ9cSIHObj6CyU1rK2Wcg5EMzlXIpg8iLXI3l7Z+WqdA-ldTPn1rWT88Sfztl1z2R24FlawWpoVXA8ylk+12UHU5FyZN3JRy8pdKdI9t0LM4f3KaNlvRjlHsu10cLp4M0rAmUO3bD02WPb1M9bkx1Xp8tOkNs7bGPsHi+keh132Ty9F+2ev7abbrlbu2xB7e2AYHcBkdF7PITuvb5W9oL71Yr5gLXiZ0RbipwhLKWRUQxywVlNfIyt-14f7fZQj56wOkYg7eqDtS4E0asnR4Woso7MZ-Kx2WDsONK1DJhjg8qcM9qsvh-jQ6QOjsvcJm9-lKMByPogXDOm+MnuHYJozk7yOW24boiO+iBHoOMYnUxOCZ3iYQFZo9BH9NEaE456dsqNPYe0S53hbmr6GKEZgp+aczOBO4l9JVdKVWmyZdADVZ42V2x1dyySCUnRJX6qlSWiTMoPkdrlAg+UMpFRKmVPzc64FZfpbl82+WWWFa1Zy3VfjenRbqeVyrKV7Y1YyllBrD4msFVa6VcqaXq0ZbMJNxSVWZvpTq9dRbzXCrFVWyh-mUmhYMbFvJ6WbHlOKy42psTnWEDbeStV-b82cpHeW6d9rkWICadIZJwW9HZNMacXdpT8tHvKzveZmtrhWrtS-F1HqQ7CYDWviNZ0419iTVKmDIui7G2-K2a29dQLDkddsS1NqHV0fFKcljsqOPRr48Jz0gh424ELobWXcnLaAXtsbjT9bPcLMIGNU+U1USYlR0tQkpJ8s7XtQdePBQW0dp7WVodY6AlTrnXFldBrt1aekPDR6SN1Df50IAfGrp4DAdgGB3UrX21doDj172DYJ0zqZRN9dc3EvMVS+6zlxlfWCs23ZcN0rwtvF-RvJ2YqkNyagz+hDKGidYawzdPjC3irDbZZNlH9VA3Y-Fa5Xql3bu4E-VDP9VPQMM+W3BpDAw0M8-w0L6Hw1UvG-J4Bmn4GmeO855hnDAvPZYPPuHm+8eH6p7O2-XPBeL3bFD+b4DdPIN2-Z677n6fCN1NA95wgOfQ9X2IaX8h1DP754Yf74s+sx9T5hz0QlwRGCTEpf6jjBsBVgTETEOqTA5BTJlFTDTHTAzEXnzrFp-vFgYj-l5qImYmfq7hfoAXjCAfWmAZJBAUGFAQQNTLTJ+HAZRpvCADqEAA). I suggest to play around with [this graph](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQM4AOwAxjAHZgB0hYOAchATgEI5wDuOHLQAy2PKXQBGAAzSStDjjS1JRBZ2UAmNYuUBmIsyUq0AWgB8WwwRbLJZy7T1A) to find out more about spacing.
