### ISSUE TITLE
Layered algorithm: how to balance or align nested nodes?

### ISSUE THREAD

**Issue by kahboom** [kieler/elkjs#217]
Hello, I have the following function and configuration for ELK:

```ts
static async getLayoutedElements(
    nodes: IVizStepNode[],
    edges: IVizStepPropsEdge[],
    direction: string
  ) {
    const DEFAULT_WIDTH_HEIGHT = 80;
    const isHorizontal = direction === 'RIGHT';

    const elk = new ELK({
      defaultLayoutOptions: {
        'elk.algorithm': 'layered',
        'elk.direction': direction,

        // vertical spacing of nodes
        'elk.spacing.nodeNode': `${DEFAULT_WIDTH_HEIGHT / 2}`,

        // ensures balanced, linear graph from beginning to end
        'elk.layered.nodePlacement.bk.fixedAlignment': 'BALANCED',

        // *between handles horizontal spacing
        'elk.layered.spacing.nodeNodeBetweenLayers': `${DEFAULT_WIDTH_HEIGHT}`,
        'elk.layered.spacing.edgeEdgeBetweenLayers': `${DEFAULT_WIDTH_HEIGHT * 1.5}`,
        'spacing.componentComponent': '70',
        spacing: '75',

        // ensures correct order of nodes (particularly important for branches)
        'elk.layered.crossingMinimization.forceNodeModelOrder': 'true',
      },
    });

    const elkNodes: ElkNode[] = [];
    const elkEdges: ElkExtendedEdge[] = [];

    nodes.forEach((flowNode) => {
      elkNodes.push({
        id: flowNode.id,
        width: flowNode.width ?? DEFAULT_WIDTH_HEIGHT,
        height: flowNode.height ?? DEFAULT_WIDTH_HEIGHT,
      });
    });

    edges.forEach((flowEdge) => {
      elkEdges.push({
        id: flowEdge.id,
        targets: [flowEdge.target],
        sources: [flowEdge.source],
      });
    });

    const newGraph = await elk.layout({
      id: 'root',
      portConstraints: 'FIXED_ORDER',
      children: elkNodes,
      edges: elkEdges,
    } as ElkNode);

    nodes.forEach((flowNode) => {
      const node = newGraph?.children?.find((n: { id: string }) => n.id === flowNode.id);
      if (node?.x && node?.y && node?.width && node?.height) {
        flowNode.position = {
          x: node.x - node.width / 2,
          y: node.y - node.height / 2,
        };

        flowNode.targetPosition = isHorizontal ? Position.Left : Position.Top;
        flowNode.sourcePosition = isHorizontal ? Position.Right : Position.Bottom;
      }
      return flowNode;
    });

    return { layoutedNodes: nodes, layoutedEdges: edges };
}
```

It is capable of producing a layout like this:

![Screen Shot 2023-03-09 at 2 54 03 pm](https://user-images.githubusercontent.com/3844502/224062372-7ef2176a-77af-4aff-adb2-287c9be0e2c0.png)

However, I'm having a problem with branches that contain an uneven number of nodes and am not sure how to configure it properly.

1. The nodes are pushed all the way to the right, as opposed to being balanced in the center or aligned to the left. How can I balance these branches or at least push the unbalanced branch nodes to the left?:

![Screen Shot 2023-03-09 at 12 02 50 pm](https://user-images.githubusercontent.com/3844502/224050884-b0a39786-742b-4d56-8ac8-23bc36dd33f9.png)

2. It gets worse sometimes when the middle branch is the unbalanced one. How can I fix this to not go crazy?:

![screenshot-2023-03-09 copy](https://user-images.githubusercontent.com/3844502/224052047-fe2b28ff-c9e7-48be-bc25-38b21f569b0f.png)

Any help would be greatly appreciated.

**Comment by soerendomroes** [comment]
Hi, can you recreate your layout problem in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html) or [elklive json](https://rtsys.informatik.uni-kiel.de/elklive/json.html)?
1. Is the result of the [layer assignment strategy](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-layering-strategy.html)
2. Seems to be the result of `elk.layered.crossingMinimization.forceNodeModelOrder` which enforces the node ordering given by your input model. This option should only be used together with a `considerModelOrder.strategy` other than ǸONE`.
However, I need the model you are feeding into ELK (in elklive otherwise it is always hard to recreate such problems) to help you.

**Comment by soerendomroes** [comment]
I guess you want something like [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAMYQB2AzjAXgLIS0gDyUtUAdJXFMHDmCzoACgCUAogDFxogPoA5ZgBFxAZVJQIlauTB0Y5GEhgAvPjAocAZtBI55jHAyat26HgFccRTLli6uHj4BITQAGWZ5AHE1ABVZYQBBWIAJWVVmAFVRAGFxIiJyRzRyAEY0AG8iNBqMYAAjHBA0ACIylqIAXyJCMBwS8oBaAD4SgCYegj6BtBGSgGZC4vIxyurazEbmtrGO7t7+ldnR8gAWAqLaBbXauq3W8nm9yenH45KAVgvl05uNhqaD1OzwOJV+c3IXyWV0hfxqm0BbQ+eyAA). However, this is currently only available as a nightly snapshot of the java version and will be added in 0.9.0.
You can replicate that using partition [like this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAMYQB2AzjAXgLIS0gDyUtUAdJXFMHDmCzoAcswAiAUQDKAfQCCwsTIliA4tNJQIlauTB0Y5GEhgAvPjAocAZtBI5hjHAyat26HgFccRAA7AoOHhLIz0OYBIggDc+HA8obyIicic0cgBGNABvIjQ8tH9A4IpDMA5CoKCKdAAGXPzMACMcEDQAIgy2ogBfIkIwHDTMgFoAPjSAJj6CAaG0MbSAZmTU8gns+ryK4tCy7arydHTNjGBm1o6Jrt7+wbX58fIAFiSU2iWN-IKAypDS8p+OyOJyaLXa5EW12mswhDzSAFZXqsnp98vs-mF0dU0FMvqCLs8obc0iiFuRESt3uTUVtAQd-ljDmhlnizmCOvDrkA) with the 0.8.X release.

**Comment by uncutz** [comment]
@soerendomroes I currently trying to achieve the same. Have you found a solution for this problem?

**Comment by uncutz** [comment]
@kahboom Have you found a solution for this?

**Comment by uncutz** [comment]
@soerendomroes Thank you, this problem has given me headaches for hours!
