### ISSUE TITLE
Partitions not aligning by order

### ISSUE THREAD

**Issue by willedanielsson** [kieler/elkjs#218]
**Describe the bug**
We use partitioning for having nodes in a certain depth but some the nodes are not partitioned in their give partition order. 
[LINK TO EDITOR](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGAOQF4DmKSk6ACwC2beG0JEApkknQ2WdlQJJatBpHpcAdAQDGtAG4F0k0WHRJSkhYkl4A1luiQZ+uvQTwEAEQoB1ADlsMABfHAhdAUg8aBl6eABtXAhWGC96AEZggHcYQXgAZgAGBQFJSC4BdEKS-GIyShp3ZjBgNiUVfncNbQ7VdzMikLDk1qg4RHoAJhy8gRrS8srqsGKFCQbqNSYWduV+9U0tPq6GMwzh8IgxtMmC2eh81dqyiqqFupJyLebdk+2esd9qd6GYppdRqkJgh6AAWB5PNZgV7LD4bb5NBgtNr-bpHXFneDg0JXFLjdIAVgR82eizeKyR6Ma22xe06APxwO2ZgKIRJkPJkwAbNSPij3rTPptMTtWmyDvRAQTQYU+SNrjdofQAOyiyXihm1Jk-LF-Ll43rmwlgIb8jVQ9IADj1SINaPqGJZZvZFqBPutFzt1wdkwAnC6XksJYyPczfnLlUqrSqwIGQrgALpXWRcSQtJL2wUISRZBSMMhIXR5xKTLJgLPmZS59D5yYzetBsm3YszMsVqutmF1hvoJuSFs1mH3Dvq4NFyT3PukSvVsAJWsIesKUdIZuDuGbjOdzVeSTwpcr-fD7djidryZUmekk+2KkXgeTzKHm+78f7kVPgK3aSCK76ruuMK6luja-neEH0M6M6ZiAIRAA)

In this example, node n9 would in my understanding be positioned in the same layer as the others with partition: 1 but is now Y-alligned with the nodes with partition: 0. Is this a bugg or is there another way for me to accomplish the desired behaviour?

**Expected behavior**
Nodes are layered by partition

**Screenshots**
<img width="1191" alt="Screenshot 2023-04-27 at 12 38 04" src="https://user-images.githubusercontent.com/3958296/234838412-66a95b40-d18c-47d6-9eb2-4ae177e9faab.png">

**ELK Version**
0.8.2 and rest

**Additional context**
```
{
  id: "root",
  layoutOptions: { 'algorithm': 'layered', 'partitioning.activate': true,  "elk.direction": "DOWN", },
  children: [
    { id: "n1", width: 30, height: 30, layoutOptions: {'partitioning.partition': 0}},
    { id: "n2", width: 30, height: 30, layoutOptions: {'partitioning.partition': 1}},
    { id: "n3", width: 30, height: 30, layoutOptions: {'partitioning.partition': 2}},
    { id: "n4", width: 30, height: 30, layoutOptions: {'partitioning.partition': 2} },
    { id: "n5", width: 30, height: 30, layoutOptions: {'partitioning.partition': 3} },
    { id: "n6", width: 30, height: 30, layoutOptions: {'partitioning.partition': 3} },
    { id: "n7", width: 30, height: 30, layoutOptions: {'partitioning.partition': 0} },
    { id: "n8", width: 30, height: 30, layoutOptions: {'partitioning.partition': 1} },
    { id: "n9", width: 30, height: 30, layoutOptions: {'partitioning.partition': 1} }
  ],
  edges: [
    { id: "e1", sources: [ "n1" ], targets: [ "n2" ] },
    { id: "e2", sources: [ "n1" ], targets: [ "n3" ] },
    { id: "e3", sources: [ "n1" ], targets: [ "n4" ] },
    { id: "e4", sources: [ "n1" ], targets: [ "n5" ] },
    { id: "e5", sources: [ "n1" ], targets: [ "n6" ] },
    { id: "e6", sources: [ "n7" ], targets: [ "n8" ] }
  ]
}
```

**Comment by soerendomroes** [comment]
You need to specify that the three different separate connected components should not be handled separately.
[Your updated model](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAOQpIDmAdAKYBjPJCqN+AvAGte4qgSQF0-AMIN6Q5dDUBbKg3710jdvHYAzAnnHscbMOyvcukdAAsdph4SL8k-aFtcDnkkWloGSHo+AkFaADclfi90JFJ+LDBgxH5pXmhIfzi6egR4BAARCgB1ADkEXABfOzBBN0g8aH96eABtbOAoOER6AEZsMAB3GHd4AGYABky3fkhuN3R5pfxiMkoaEuYwYHZQ8JKovjPXEq8FxuaBofL6ACYJ6ehZsEXl1fXNj9tj49tQIkwWKcFOdItFeNdwV5Rg8WhBBjAXnMPjM3Fs-msNnidiRyGDDpCERc4ZSGF5XiinhiRgAWbFfXFA-EAokg0kHBhHE40+iXeHQm60+D0sCPezo4YIegAVjZ31+YBWBMB6t5+3BgqhYQlIup4sR80aMtRx2eIwAbKqOerNdzOcTQfyIcdDTCTVczbcLVbGQr6AB2R1El2Et26skCikB2H+o3msD3YNy22KgAckbd0e1wN2fP1idTVJTvqRltlbHlLwAnPnnf8YzqS3ryd7haLhTWZbgALotALcfhHfpZpkIfjjTKMMhIQQTvojcZgEdgdAKcfGNeK96bzP17P8d4LpcryfrhCbzI7nj8fdgXojLHHutos9Yy+kZerq+t73tuu7Pjeiqsp+1oNjkrJ-gBEFjHeW6PnuSEqtBIblPwKoIdeB7ISBaHgYRDpYdOCr8A6+GAW+ioRsRYEvvR9B5p+w4gI0QA)

**Comment by soerendomroes** [comment]
Another option which might be interesting for you is `org.eclipse.elk.considerModelOrder.strategy`. If you use elk 0.8.2 you might want to set it to `PREFER_EDGES` to order the nodes and edges by you edge order per default if no additional crossings are introduced, as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAOQpIDmAdAKYBjPJCqN+AvAGte4qgSQF0-AMIN6Q5dDUBbKg3710jdvHYAzAnnHscbMO0ENGMfkgCyKaPzwUk3pFl0RWVuIlMHAAUAJQBRADFY6IB9WIARAHFYgGVbXA4rbi5IdAALHQj2QiI3fmg8+3Z5JFpaBkh6PgJBWgA3JX4I4NJ+LDB8xB8ZaEgkTTp6BHgENIoAdQA5BFwAXzswQVLIPGg5+ngAbQngKDhEegBGbDAAdxgy+ABmAAYx0v5INxSugvr98MQyJQaAtmGBgE0FK0Fh0+M0kQwIt8dntrrdlvQAEzPN7QD5gH5-AFAkHksHVSHUNpMFgIlolZGdXho9kY+APbH7CA3GD4z7E96lUGUwHAqXgkjkRkwlncpkormInn0CIEgW4kX3AAs4tJktp0upcvpiuhzhVmrVnNVCx1OzAOPswruCHoAFYTWSKWB-jKaUHrVCmbD4c72k6HS6vm6PWwvfiAGwBs1BkOW83yhm25lw1no+jq2PapPuwVwvH3ADsWbludl+YjSrtJcrFYTvLAWJr+u99AAHM3862w3SITao-a2Y7UX2q2B+UPPfWfQBOCc5qlt8OzyPK7sr3uLxNr5O4AC6+zq3H4sKum4NCH4TzGjDISEEz8ue4njAe8wHQBQn2MQCfSJECN1TLd+CJb9f3-F8gIQECxnAnh+CgsALnuMU4JTIVELFFDSD-ACCIwrCwIgvD0J9Y0SNrNNJmNSjqOYx5MNAnDIN4-02OHZZ+H9bi0Ogvj6MEpiZMzUS329fhMykmjCJ9Js5MY-CtLHfj3TvEAdiAA).
