### ISSUE TITLE
Balanced Link Layout with Multiple Ports

### ISSUE THREAD

**Issue by kam-ushur** [kieler/elkjs#219]
I am attempting to achieve something similar to [this](https://github.com/kieler/elkjs/issues/162#issuecomment-1076363158). 

What I have ended up with is [this](
https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUDiANYB0BM+AxnDBAHboAiA8gOoByRTEBHAAVMtHEhxM4FAM5wowODjBZ0AZQCSAWSEAZAKJFaWWiBwAhfMDIwmYWfMXLVaVvqEAVABIB9AGIaAEpqHkR8AjhoTACMaADeRGhJaAAO0HAAwsxyCrZwMugBABr6rD5C7GqJyWlQcKmxCQCQTZhYEACu9QDaRC1NaTLwjCxo0QCsADRoAAx9LUMAXjjo0dNzLQC61cnJAHq10kOC6uwAqt47aAC+YbuHqQBM8fNtnT3zAxBDDMyrU7NPksVmN1vNtrtdgd0rIYCc0Gpzpddrcrg8UgBmF5JFpvLpoXr9QbDP5jAEbBYwZarMFbK5Qw6w+GIi5eK63W78QRRZ4Je7pLJMHLAPIFNDFUrlSpo9INF647DvAmfYm-UYTWmU6mgwF0yH7RnHEHcdiBZHJDlhLmRJhYvk1AXZRyiwoaEplCpVfl1OXNVqK-GElqqkb-TVNYE03VNCH6tDQupM42m81JVHe+opXmJBXtQMq74k9XkoFUkFraOx-UJo5w5Nmtkou4On2Y+X+vMfImFtVh6MRstRilVyE1pPoE0N9lEW6EMA26IUFKxAC0AD4eUvoiQCPOoous2h11EMVuiEA)

<img width="119" alt="Screenshot 2023-05-12 at 7 50 12 PM" src="https://github.com/kieler/elkjs/assets/106711046/f7ea747a-92f5-41d5-8b4a-ea198034e06b">

As you can see the links coming out of n1 are not branching left and right in a balanced way. My goal is to have the left and right branches emanate from the same point. I don't really want to show all ports which is why I have multiple ports on top of each other.

Any hints would help. My config is:

```
algorithm: layered
elk.direction: DOWN
nodePlacement.strategy: SIMPLE
cycleBreaking.strategy: DEPTH_FIRST

node n1 {
    portConstraints: FIXED_POS
    port p1 {
		layout [
			position: 15, 0
			size: 1, 0
		]
        ^port.side: SOUTH
    }

    port p2 {
		layout [
			position: 15, 0
			size: 1, 0
		]
        ^port.side: SOUTH
    }

    port p3 {
  		layout [
			position: 15, 0
			size: 1, 0
		]
        ^port.side: SOUTH
    }
}
node n2 {
    portConstraints: FIXED_POS
    port p1 {
		layout [
			position: 15, 0
			size: 1, 0
		]
        ^port.side: NORTH
    }
}

node n3 {
    portConstraints: FIXED_POS
    port p1 {
		layout [
			position: 15, 0
			size: 1, 0
		]
        ^port.side: NORTH
    }

    port p2 {
 		layout [
			position: 15, 0
			size: 1, 0
		]
        ^port.side: NORTH
    }

    port p3 {
		layout [
			position: 15, 0
			size: 1, 0
		]
        ^port.side: NORTH
    }
}
edge n1.p1 -> n2.p1
edge n1.p2 -> n3.p1
```

**Comment by soerendomroes** [comment]
Hi, try using the same port for your edges that should be merged as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUDiANYB0BM+AxnDBAHboAiA8gOoByRTEBHAAVMtHEhxM4FAM5wowODjBZ0AZQCSAWSEAZAKJFaWWiBwAhfMDIwmYWfMXLVaVvqEAVABIB9AGIaAEpqHkR8AjhoTACMaADeRGhJaAAO0HAAwsxyCrZwMugBABr6rD5C7GqJyWlQcKmxCQCQTZhYEACu9QDaRC1NaTLwjCxo0QCsADRoAAx9LUMAXjjo0dNzLQC61cnJAHq10kOC6uwAqt47aAC+YbuHqQBM8fNtnT3zAxBDDMyrU7NPksVmN1vNtrtdgd0rIYCc0Gpzpddrcrg8UgBmF5JFpvLpoXr9QbDP5jAEbBYwZarMFbK5Qw6w+GIi5eK63W78QRRZ4Je7pLJMHLAPIFNDFUrlSpo9INF647DvAmfYm-UYTWmU6mgwF0yH7RnHEHcdiBZHJDlhLmRJhYvk1AXZRyiwoaEplCpVfl1OXNVqK-GElqqkb-TVNYE03VNCH6tDQupM42m81JVHe+opXmJBXtQMq74k9XkoFUkFraOx-UJo5w5Nmtkou4On2Y+X+vMfImFtVh6MRstRilVyE1pPoE0N9lEW6EMA26IUFKxAC0AD4eUvoiQCPOoovl2h11EMVuiEA). Both edges begin from n1.p1 instead from n1.p1 and n1.p2.

(I am currently on vacation so I don't have that much time to answer and look into issues)

**Comment by kam-ushur** [comment]
Thank you, that helps
