### ISSUE TITLE
Question: is graphviz.dot can be used as layout algorithm?

### ISSUE THREAD

**Issue by HanzhiWang1105** [kieler/elkjs#220]
Hi, I am following the doc https://github.com/kieler/elkjs#layout-options and wanted to choose proper layout algorithm. The graphviz.dot algorithm is listed in the page https://www.eclipse.org/elk/reference/algorithms.html, but when I declared as:
```
const elk = new Elk({
    defaultLayoutOptions: {
        'elk.algorithm': 'org.eclipse.elk.graphviz.dot',
...
    }
})
```
I got an error:
Error: org.eclipse.elk.core.UnsupportedConfigurationException: Layout algorithm 'org.eclipse.elk.graphviz.dot' not found for Root Node root
Do you know which lib I need to add to use graphviz dot?

Thank you so much!

**Comment by soerendomroes** [comment]
Hi, only the ELK-native algorithms (so not Graphviz algorithms or libavoid or Draw2D) can be transpiled into Javascript and hence elkjs. If you want to use a similar algorithm to dot I suggest using ELK Layered. If you have problems configuring it, please have a look at our [documentation](https://www.eclipse.org/elk/reference/algorithms/org-eclipse-elk-layered.html), this [blogpost](https://www.eclipse.org/elk/blog/posts/2023/23-01-09-constraining-the-model.html), our [examples](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=general%2FmixingDirection), browse past tickets here or in the [ELK repository](https://github.com/eclipse/elk/issues), or ask again here or on [gitter](https://app.gitter.im/#/room/#eclipse_elk:gitter.im).

(I am currently on vacation so I don't have that much time to answer and look into issues)
