### ISSUE TITLE
Wrong routing of edges from version 0.8.1

### ISSUE THREAD

**Issue by tmarsik42** [kieler/elkjs#221]
**Describe the bug**
Edges are routing in a strange way since 0.8.1. It works fine in <0.7.3.

0.7.3-dev and under
<img width="557" alt="Snímek obrazovky 2023-05-16 v 8 39 41" src="https://github.com/kieler/elkjs/assets/95856146/12e8be68-525e-47f1-957d-77fa5911f7d8">

0.8.1 and higher
<img width="498" alt="Snímek obrazovky 2023-05-16 v 8 40 00" src="https://github.com/kieler/elkjs/assets/95856146/6bfc0d4a-9411-4d90-b15d-7b3c57561b71">

I quickly looked through issues so I don't make duplicates, maybe https://github.com/eclipse/elk/issues/901 is related?

Please toggle between versions 0.7.1 and 0.8.2 in elklive reproduction

[reproduction link](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGBECWAmkC4oCcD2qAukA04oBsBDAT1QFcMB5ABw2lQDsBnRMUCCSAU3wGsA6QvgDmqZNAwALALatIRYl2Rd4uDlB4CFSlfwBmXFQCNCAY14BRWMK4skGZGS5qOkMcP5dT+aNSZdPPn4majNoBg8VGysbVgAmAFYXTkloJUJkU0liAAlCBlgfCLkASQA5AGEAGQBVABELAH0KnJKquoAlCzLIPABfF0gs6HxYZQZWAG08CHZ1KDg5Iy49AAYEgDYtgFoATgB2AEZTbYAWWFgNvdhTAGZtgA4jvQ3bhMJVowTVGdcAdzgUlYhwSq2SrkkXGgwkkWCQcVup3BnGGo3GU1+6jm81ciyQkFuhi+plWsG2+ziRj0Z0OGyM20IcT0cW2sFutwehA2sH2hFuuweOEx80gANgQKQhziG2RIsh0Nh8XWsvUQ1SaK4EyQ0xxOOxutVeKgG0OjI2+1O+3Jhz0ZNOeltjzid0e+1gxwSpoRux+BpxosBkmBqziKt1kHlMLhYEO+xlwoNapGY01GL9uv16cN8HxsDiq12XlM9LMFzOVJOhF2JO2Gy4h1gu12hzeXFWXCFWfDYolYFuYITWYjUKjrH7YfTkGoYgwdjAOq7GcHi4WOag70pegSXF2202NrOq0I1Ob7YZcUOq1uWy+emrnZX3cDrH2E8Xw4V0dfy-fCnIVFoehmFYTNH1VadkAwYI4A7fEykoDoABUcgfMD-QgqDwlgLgAA9WFWH8uwGQihzwyVDn4JISMnYgxwItCOD6aj5gAXTfRMABIUKQXZTludjwzIsAEgSfgHnZCTJMkgT-VoyU4mYiBiLA0CuxgNdIDjLZYE9Q5WVWUw9NOQ4fT2I5d29OJDA2AsNj0W5UMfANxSDJB9geGS5RHRUeIHBikw1LV50U+ZVKco1IHWOzL1MU5tlMWBTgSM4KROB57JOPQHkpUxdgvPK80c-ye1c4SkRC-1Ix8sATU8xNURTIKFwYrEKr9dS5B9VZ7NgF5tg9LgaXcvYW1WbYjHzQ4uARN1KQSIqWs4Eq6Lqocqujcc2sTDC52axbQq2ocIu5a8732E5TnWQb7QSe48tuPSNjuB4uH2B1YAeS8Fv2-5nzc1aVw-Ud-sOyc-woGg6EYOcwp+zgMOg7C5HgpCUIBpyEaw3D8NBv1lLh-0hNjfgtlJsnyfKgnZNYclcZxfGqbYOnwwit59iMN0uDi1Y6SuU45vG17kpe-sr32BIjle764ec3tv0Z1V1pfdG1PBgCoeApBYZlhGmBguQAGVKBqZDpYJqcZ34LGieZ+mVdI1hRKk53pNtkU5LAWmFbAJjGbYt3IC41hdlBe3CeBUMA49kzmd9-b-Z+wPuLAXiPNxyAicjxPo-2Q647AhO0KT4PTnjfzM-RyAPYtEL86zQu1KDnjjM8jOI9bnOSLrnEG-DJuU-5N82-kofO4NbuwF7zh+92W55ZFImHn4WlydX+fVQ9-LfgZpn-WOlsTGOOLTmbB4zmdE9SWSwldj0Q5S-7PR9g7WVZdKkE-K8z9gX2dfXAa9E2pBzaw6viIwywQT7FntsaUfFz5GCuIQPiLIeS3EpF8IwNojC7DNlAZa8ky7tSVpKU4adJwANTEArs2tsxyEJBse0jIz6nH5tdJk9IHgJAeHFOkJ9Ppz0StlXBqp8ExhDK3YhMYTKtwoU1EKNCWYaVMJyN0fEyT1hPuWK8jx3QnDiIQdKuw6y3DvC2YRT4XIvjIUXSRuxP5gQCo1NMLUFGTgiqYZRD0srJRsqZc4qwxpINvuNB45ongJCMTcPQ5jJyiISJTfaQNqq1XTrI5xP1XHvgivo04O4EGEBgQg66V4z4PALGfNssBVjcM+occBqwYnvlEZtRmSSNr2J1jOXabtZg9NxBpCkv8uAbG3P1T0F08q7kIAg6k3VpoMKMA8cSRjGkONEX-VpkiNlU3kCQf8kMgIwz6eBS2eskZwQQqbMOQ5MYFGxkgei3sfbXMTETCiVEnlQA9v2PpE9FpT0STPBhLzXAVyjhHWOuMAUOKBVnRJYLs4QsWn8+ulcgUdMBgiou0cFJgRRT3VuM8uGtyxWpHFXcfzQtcESwhrz24-irki3UE8AXFx4vE1+pLXDkvUHHQu3BrC2HSbvEUEUeawHAbzVkfIxq5KpAyLcZ9pQOienEA4hxxILUgEwcgmQhXakgBuKk25dz7mpJdY8I0zyMkvNeOkCQ7ymEgKyjAGQbCzimJAE6dkDgXSumcLcd0ESPWeq9d6n0Gmsv8KYDW3SDQgLFdySVCDpX9jOFweVx4uEwLsi8UwaqjjiUaEwBpQ8mCusggABVQOEaMCjh5gH2KsMSLtnYCUZUgE+P4d7+k1LAattaQIkQbRLZeq9x0JJosGW43ah7LAKAOhgHqqFZkyQ2ptLbW2u0Bh7CJXcBJrqEqOle46yaTqHLu3YFL0xUs4OEUwqBpDhGEAbSQhBqCwXXIyY1O49wmnNUeE8l5Bo2qvDeB194h7-lEM+1977P1erZD686h5Rk3SDQ9Wsoa3q2gjb0cewpWUPqXYQcISg5AmjNBaK0zw7TvSdC6J4ujPSMn5PAbe4JQKgPXJdGybZrrVmSklSkjxjyDVMBsZsl4EiHwMFqnVZA9W7U0nEIZIzBogmOGcSZDIZnbDmbAxZyyNjOtfhW91ym2Yc2wtzKV-MviC3Fo8Lgos54SymvsUzwptVeFjcK1qbiNLxJ5u2M8J9TBCYSCJzkBh4qScONJ2TXBi2loZeWjIGBF11uHUJJ47bo4FlnQyvtWWh1qVy9s6mSA3gbCK24hgD6n0RDgx+uQgzn7qbGVpk+ardN2X0wYQzSz+QmagxQGDzW32tfxFZzmtmU32eSssJzIsAluclp5wcLLX7EddWR5Acg0CYHw4xPA-KZ5vEGEJT+HawA3dERq5tJ7T2ScGJI0uCQQBMSAA)

**Comment by soerendomroes** [comment]
Yes, it is related to the issues you linked, and yes, you can fix this by containing your edges properly as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGBECWAmkC4oCcD2qAukA04oGMALaAG1mQFMA7RMAbTwlAhajlsgCMKAzABgCsANhEBaAJwB2AIz5RAFliwhE2PgDMogBwyeQ9QICGfTgPi5WESEVLlqtBpZbMnLGPCSR1FCqfx9YUUkAJk4eBWkhTlFDYJ5g0Vh1dS1DIVhJQ3VxLRxGV2tiMkoaJEdXVhcK1ncOIWlYoUl5SSDpHkD5Hg7tYI1tSVhZAQbg7PN86oIiu1L6SamwKsWa9k9YYL5xCnx8aMN8JQUwuUNxf1EhCmlYcXFpAwo+CjyVp0gAB1RkDABnBwWbyWgKBbA8UCMoR4Ago4lEwnaCj4hnC92eMWC0j46hEph451eoPeJEMAE9UABXDAAeQ+GGgqCo-yQyyJNS+PwAdL84C9PAA5akAJQAKgAJQlsyyfb4YTnQKiwCgADw4fEgIKBAF8LFK3KqkNJpJyBLq9VBSbR1HxOXwzXrIAB3OAYQi0SS2+1SyCECjQADmhCwSA9fE1iy14YqAF0vW9IAawAIBJytMl0xmM3GVpBLYbgp6owVnbBXVabXai+9fQGg+XbVWWDrG0wW241lBJCJ0iNpIk+Pg+-JpOJAlIR6IxuJgj4hFshDx1JLQYVbCUAebWWzap5BAusfh5KJDvIBAoQnItIu5DwtKF8NOR8ENsvvTZivYym2KlvzTuoKOfCLrAeiiMMFARJIWgSA8fCiJwmzSBQYyDKEAivuaUAcn8G6YU4v54WCdRJAuUhyPIggQV0AiaNO6h9kIGhaBQkjdLAWhYhhhFQCS5JUrS9KMsywLcRUMpcjySocIKooStmoniXKCpKomkDqt+bzNqJ0qJtIHrdgZhkiPI8l4bmtBBIW2k1CWZYhlZ1lWDWgbBmAoYaVMWnWQRZkdl4AiSJwgwUEefBRCo8hofBLFnsx1rYpIAVIZIXGEZAvGUjSdIMkytA+Wl2HcryHAAMrUgAquKqXcYp8qKiqHDSBqjkQF5jkJrQKaZt1WYeYs5lIJZlYtVAtluvZw0tT6foue6DaOZG2mxn17y6QWk01XmYAjg5NVjfWG1pc5dZINa82EYtmHLWZa27Q6W16Xd3r7UgAjyE927Ha59TnVKl1Etd263YdQIDW570g-GL1uVoH05l9tDiBWbb-YsgM5sDpnSg9oZYzZLrjdtfDrXjbgI4aXZwwUFCwP6FDCeUQL5WJflhbAnCcOFiRZHB8i+OEKICNBwQLno+DBOOabVdUkC-JSyD4PTuHepCYQwnCCLhBRKIweisRYjiUQCPi+DNWy6MrhghjIHTOFfn+6Q4vikjkZRCjQrRYwMUxLFsRx6lShboO-Dsgm5fberM-1rPpBzXOwDzCj8zE0LC6LjESzIaYAPq-OqpNTLLVs-AACqgCquVHGPujaaY9ZmBf9Vt8jiL9eptQ61CwGXFd5St+qdR6kRGUZJn91YD3Ym3f2N2J3CKj3VB2-M3FV-GiaSLX9cN+PbhbQIrdhtxHebrvViJgFnLDyPBlj9pYMH9P7f90H24KvgqAALYKv6JWEIYHw+QQliGrWE8J6ha2RKiLEEF9bYlxMbAks8CiZX9OXKgv9-6AOIk7MiSIYTuxohIL2lwfasQ6P7M2f0NLRhRo2WhKxUZOFfjUTG4YwaPUhvjUshNpAiypk5GaJ0wCbBTEfVwTCwCvw6oaWG18b5NDjGDTEh8lHQ2kAICsSjyYiPUBDfIHctz-kgPUdQnBDCyCPC3aQ0FIr4FRAEM83hxA8GkPIfQQFJAvCUe+WYytLD5WMRza4AVxCaBFvITQkVOYxEiQkDI6hQimE4O0Tg4hparg-HMRm1Q17GO8EILosRbGRSonEaIWghZHiiC3Di6hBjyDvNLGovj1wRyZhpYx+BUgNPUIEa4LdjjYm0EMOQwRDBXnEFcdQ+IHjNIKK0z8K9I79y6d0+it4zxzlHAoWAfA4KGBbuETgWgmg6APukex8zC6LOybvNeOY-LjL5uITmhhJycyotiaCWgtjQSeHsrQjSjQc3zmfLCsoGbgtbCNYxIRJBeKEAQjRsgFDTjhIYTm4QgLIUKSctMUzrnbgyvxbKQk+4jSsIVSSQDIAySqsgoktVlINV3FQ6yJ8FK6WNKaaFe8DqMqhgTOaXCjpCNcu5Ba4KWEOjYffB6JNwVOmFadLRSqdFnXEXhSRANBWsNoHwgR8YFVGpzNDN6pr+o6J+lqtkOq0aCpkdtRV3oTWisLtDKClrqzisRsjIk9rmGNydYa912MDUuqFTwg1xNvVQB0UaQ+RZA1SKxiGyNYk3VpvUfwsN01ayuTcbDW1rBJHSLleG-MH1lXRsNJo6tCaEVt0uoDdKZJMoCRysJZYkBDAkDQcgaArpP4cF4hQSgEwag8B8OzA4ABrAAorTJWngMDIApN4-IssPgHB-pyGmdMl10w4MEMRy4fTQHHdbIgpIxSGEVCQH+HAACS-IADCAAZcqAARBd2c31imfR+79QoF38jNl5Gtdltq-Kvgo7s4hdT5tmkgdxYikMHpXcsmF0o-JvTCs8dELd8BnlPKEbQKIIL4CEPcLEAhzHtE3e8OWFIFZYZyTUeFiLkUjHIuimIWLRA4oifi7IQh2UQGkcXW2UKxIGECsFUKXNolnm4IlbQFB4r1KSixCTqaFiy1Dl2-xlR2F4YonOJ4VFzikYEOR1I07jw0aNIIBj07c5gsLr8YuGBF6VyLE6nQlqOFbCfqWtNXc-MUv6omILYaJ5WmEGFpsab35fx-n-ABtKuMUCRRBFFfGJYCYXEJ6dImtAEvE2m1B6DMFZY4PJoKSolMxJU9FdTcV9naZkLpkEZaDF4FoVqIAA).

(I am currently on vacation so I don't have that much time to answer and look into issues)

**Comment by tmarsik42** [comment]
Thank you for the link, I wasn't sure if it's related to #901 so I'll close this issue then. Enjoy your vacation.
