### ISSUE TITLE
mrtree layout always using DOWN

### ISSUE THREAD

**Issue by geohuz** [kieler/elkjs#223]
```
const graph = {
    id: "root",
    layoutOptions: {
      "elk.algorithm": 'mrtree',
      "elk.direction": 'RIGHT',
    },
    children: nodes,
    edges: edges
  }
```

I've tried other directions, it always return DOWN layout. I've tried layered algorithm and it works fine.

**Comment by soerendomroes** [comment]
Directions other than DOWN will only be added with the 0.9.0 ELK release or are usable with the ELK Java nightly build. In the meantime, I suggest using ELK layered.
