### ISSUE TITLE
Minimize the number of bendPoints?

### ISSUE THREAD

**Issue by CrashLaker** [kieler/elkjs#227]
Hi all,

is it possible to minimize the number of bendPoints

for example this diagram

![image](https://github.com/kieler/elkjs/assets/4432491/74c45263-4e75-44e3-ad49-48f6c450ee13)

the stair case ish look makes it not pleasant to follow

regards,c.

**Comment by soerendomroes** [comment]
Could you recreate the model in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html)? Otherwise, I have to guess the exact properties.

At first glance, it might be related to spacing between ports, edges, and nodes.

**Comment by soerendomroes** [comment]
Have you added all your option to the elklive example?

**Comment by CrashLaker** [comment]
yes.
only this one
```json
"layoutOptions": {
      "elk.layered.nodePlacement.bk.fixedAlignment": "BALANCED",
    },
```

**Comment by CrashLaker** [comment]
hmm ok. now i see.

it's due to the versions
`0.7.0`
![image](https://github.com/kieler/elkjs/assets/4432491/8efd4e59-043e-4009-9b0c-0b160b644bd2)


`0.7.1`
![image](https://github.com/kieler/elkjs/assets/4432491/d662b3eb-6d95-4261-b539-c54073172917)

**Comment by CrashLaker** [comment]
awesome.

`0.7.1` solved it

![image](https://github.com/kieler/elkjs/assets/4432491/8689efd1-2558-4643-acad-6d10d9a524b9)
