### ISSUE TITLE
Unexpected hierarchy rebuild after update

### ISSUE THREAD

**Issue by piotr-jarznicki** [kieler/elkjs#229]
Hi everyone. I'm building a hierarchy using ELK. In my application, there is a possibility to change the hierarchy using drag and drop functionality. Everything seems to be working fine, but ELK seems to recalculate positions for nodes, which often turns out to be confusing for the users, as nodes they've moved end up on the other side of the hierarchy. Is there any way to avoid this and provide more predictable positioning?

**Comment by soerendomroes** [comment]
Have you looked at [this blogpost](https://www.eclipse.org/elk/blog/posts/2023/23-01-09-constraining-the-model.html)?

**Comment by piotr-jarznicki** [comment]
I dug around in the options and achieved quite a pleasant result - the entire hierarchy no longer jumps abruptly when making changes using drag and drop.

options: 

`      'elk.direction': direction,
      'elk.algorithm': 'layered',
      'elk.spacing.nodeNode': '50',
      'elk.layered.spacing.nodeNodeBetweenLayers': '50',
      'elk.layered.nodePlacement.bk.fixedAlignment': 'BALANCED',
      'org.eclipse.elk.layered.nodePlacement.favorStraightEdges': 'true',
      'org.eclipse.elk.layered.considerModelOrder.strategy': 'NODES_AND_EDGES',
      'org.eclipse.elk.layered.layering.strategy': 'INTERACTIVE',`

In the meantime, I found an even better algorithm fit for my case - mrtree. However, I'm unable to achieve the same result here; the hierarchy changes in an unpredictable manner.

**Comment by soerendomroes** [comment]
This issue with MrTree will be fixed in the upcoming release. If you have further problems feel free to ask here or in our [gitter chat](gitter.im/eclipse/elk).

**Comment by piotr-jarznicki** [comment]
Great to hear that. In the meantime, it looks like I will have to use 'layered'. Are there any options to set up the graph in a way that closely resembles the one built using 'MrTee'? 

The link to the chat doesn't seem to be working.

**Comment by soerendomroes** [comment]
The link should work now.

The algorithm that resembles MrTree would be the layered algorithm. The options mentioned above should mostly resemble MrTree. What exactly do you need for your diagrams? Can you recreate your layout in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html) or [elklive json](https://rtsys.informatik.uni-kiel.de/elklive/json.html)?
