### ISSUE TITLE
[doc]: not clear how to use options

### ISSUE THREAD

**Issue by dberardo-com** [kieler/elkjs#231]
how to change the alignme options ? https://eclipse.dev/elk/reference/options/org-eclipse-elk-alignment.html

i have tried with

```
new ELK({defaultLayoutOptions: {
      "org.eclipse.elk.alignment": "LEFT",
      "elk.alignment": "LEFT",
      alignment: "LEFT",
    }})
```
but none seems to work... 

also: is it possible to set all 3 kind of options from this page? or is it elkjs only limited to layoutoptions ? 

https://eclipse.dev/elk/reference.html

**Comment by soerendomroes** [comment]
The fully qualified id `org.eclipse.elk.alignment` should always work. I think the other options should work too. However, what this does depends on the used algorithm what is actually happening.

Please replicate your problem using [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html) or [elklive json](https://rtsys.informatik.uni-kiel.de/elklive/json.html) and describe what you expect your algorithm to do.

**Comment by dberardo-com** [comment]
thanks a lot for sharing the content. i understand that my issue was indeed the attribute in itself, and not the way it was transmitted to the ELK object. i have found this issue as a good source: https://github.com/kieler/elkjs/issues/167

IMO you could close this issue, perhaps just the documentation of this github repo is a bit confusing in this regards ... it would suffice to have just some parameters in the code example right below in the README section to disambiguate.

cheers
