### ISSUE TITLE
Documentation typo?

### ISSUE THREAD

**Issue by Vesper0704** [kieler/elkjs#232]
When I was going through [this page](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=user-hints%2Flayered%2FverticalOrder), I was confused by this:
![image](https://user-images.githubusercontent.com/64687700/253841653-de1f2e2b-dba3-4102-923f-4c5b7b469a6e.png)
Maybe the second one should be horizontal order in a top-down layout?

By the way, it seems that the user-hint part about the vertical/horizontal order control are all talking about connected nodes. What if I want to control the relative position of the nodes that are not connected by edges without too much change on the overall layout options?

Thanks!

**Comment by soerendomroes** [comment]
You are coreect, this seems to be a typo.
You can consider separate connected components by setting `separateConnectedComponents` to `false`.

**Comment by Vesper0704** [comment]
Thanks for your reply. Maybe I didn't make the question clear, here is the situation i want to cope with:
[elklive demo](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=HYewJgpgBATiIBcoG8BQUNQIYBsDmIMAlggBYC2AXFBDgNYB0OWAnhDBGOprY6UeywwAxqRYAJLMDA4iwPNQCSAOQDCAGQCqAEQCiAfVXjF67QCVdy7hl4MADljBg5CqACIA2jggAzBAF4AZgAGABooBBA7fwBWMKgAI0RI8n8AJnjiPFIAjIBdN2soBxgEEiIQYBcGLGEygDcsBAhqBBgAVwgi22cOOorgajNFAHFxABUi5gTadzhEQswoUEhioQhgJDQlpZ6iPrLK6m0AeQB1Kx2eentHZ3lqT28-IPjI6IAWeKSEFPTMojZXLBApFJYlMqHKryW6lcpHKBpMGYaazNwlDYIQrIjAraByYDsFA4na2BxOFyPLy+AIhcLvfxfUFXK78QQiMSSaSyB5QADKugACgBBMzC8YGIwmcyWEm7G69CD9BGnC5yzB49RYGY4ADO9mYwgg5ExVJUfMUeig4n06l0ADFxlAAGr6cYnQWg9UYCHw6F4Gr9RrNVodLreqConDuAnsRYspZ4qD2uCbPnsersXXEhMJ31Q6r5gbUYIRpZR9wpyoIdMwTMwXXx3NQAC+EaTVbTGazaRzzZ2RcqhaEkOLUFL-Z2FbcnZr3YbaSbubbk47qbndazgT7k59I79w7hUOoAEYyyjtWjZ7X67rAkuEyv+2vqzesx8d7vB-7YaOEWfdwvHVK3XN8Gw+B8WTbCMAHoYOWcBoDAdpyHIFhPwTOCp1YEB2iQDwoF1IgAC8WigE9whPKA8lg+Dy0vaM3GQ1CWEgq4sOgycsM4PBoGvedswAWgAPigZi0NomgwF45NQIE3sRLElCJK4+CeL4uTNwbbdFPElhJPU2TXwEj9dOU-TH1QIpOI1RCoGFDDMG-Q8-0GciSWnYUlxs3E7IAIUcvcjwGFy-VPDyGPcPzvKsxM7NUQK1mCocYW-cKE2nVQYqKJNtES5zUv3Y93IyyK3G0bKliwpM9N7bZMCw+iWFw-DCJIsiKPI6iikaoC0VqpcONihq1Ok6B6jsYQoDMlikSq0aZIcma0LmkapJkgLlpYVaMG4saoASradqgPaZLyo6rLbIA).
I want the four frontServers to be placed in the horizontal direction, but the default is vertical. Since they are not connected, and the layer structure is unclear to me, I can not find a good way to control them. What I did so far is to let them connect to a dummy node and set the partition, like [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=HYewJgpgBATiIBcoG8BQUNQIYBsDmIMAlggBYC2AXFBDgNYB0OWAnhDBGOprY6UeywwAxqRYAJLMDA4iwPNQCSAOQDCAGQCqAEQCiAfVXjF67QCVdy7hl4MADljBg5CqACIA2jggAzBAF4AZgAGABooBBA7fwBWMKgAI0RI8n8AJnjiPFIAjIBdN2soBxgEEiIQYBcGLGEygDcsBAhqBBgAVwgi22cOOorgajNFAHFxABUi5gTadzhEQswoUEhioQhgJDQlpZ6iPrLK6m0AeQB1Kx2eentHZ3lqT28-IPjI6IAWeKSEFPTMojZXLBApFJYlMqHKryW6lcpHKBpMGYaazNwlDYIQrIjAraByYDsFA4na2BxOFyPLy+AIhcLvfxfUFXK78QQiMSSaSyB5QADKugACgBBMzC8YGIwmcyWEm7G69CD9BGnC5yzB49RYGY4ADO9mYwgg5ExVJUfMUeig4n06l0ADFxlAAGr6cYnQWg9UYCHw6F4Gr9RrNVodLreqConDuAnsRYspZ4qD2uCbPnsersXXEhMJ31Q6r5gbUYIRpZR9wpyoIdMwTMwXXx3NQAC+EaTVbTGazaRzzZ2RcqhaEkOLUFL-Z2FbcnZr3YbaSbubbk47qbndazgT7k59I79w7hUJLZZR2rRs9r9d1gSXCZX-bX1avWY+O93g-9sNHCInu4w06XvOuofHeLJtu24DQGA7TkOQLDvpOzAsCA7RIB4UC6kQABeLRQAAjOE+FQHkp4Aee0ZuDBcEsGBVwQZOnB4NAQGbg2UAALQAHxQNR8ERkxLHri+C6cTxfEsAJYDMcmwnAdu3G8bB-GMdJQnPsBb6KRJJIMZgem4lBUDCohmCfoeP6DARJLTsKS4GcsRkAEKmXuR4DBZfrUPhNkUe4Tn2agRRJqorlrO5Q4wp+3m+Tq7iqIFwVGdoYXmVF+7HtZCbTtoiVLAA9PljmrBJvbbJghVTqwqHoZhOF4YRBEkUUlXln5VHKSwi4tUVDmVYJUD1HYwhiUpNFIgVRUDSZ2mdRNFVTWpUAubN409TQS2hat8HzRg-VLSl21dUFbZAA), when I render them, I'll just ignore the dummyNode. However, if I want to place the four unrelated nodes in a grid(eg, 2x2 layout), this approach seems to [fail](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=HYewJgpgBATiIBcoG8BQUNQIYBsDmIMAlggBYC2AXFBDgNYB0OWAnhDBGOprY6UeywwAxqRYAJLMDA4iwPNQCSAOQDCAGQCqAEQCiAfVXjF67QCVdy7hl4MADljBg5CqACIA2jggAzBAF4AZgAGABooBBA7fwBWMKgAI0RI8n8AJnjiPFIAjIBdN2soBxgEEiIQYBcGLGEygDcsBAhqBBgAVwgi22cOOorgajNFAHFxABUi5gTadzhEQswoUEhioQhgJDQlpZ6iPrLK6m0AeQB1Kx2eentHZ3lqT28-IPjI6IAWeKSEFPTMojZXLBApFJYlMqHKryW6lcpHKBpMGYaazNwlDYIQrIjAraByYDsFA4na2BxOFyPLy+AIhcLvfxfUFXK78QQiMSSaSyB5QADKugACgBBMzC8YGIwmcyWEm7G69CD9BGnC5yzB49RYGY4ADO9mYwgg5ExVJUfMUeig4n06l0ADFxlAAGr6cYnQWg9UYCHw6F4Gr9RrNVodLreqConDuAnsRYspZ4qD2uCbPnsersXXEhMJ31Q6r5gbUYIRpZR9wpyoIdMwTMwXXx3NQAC+EaTVbTGazaRzzZ2RcqhaEkOLUFL-Z2FbcnZr3YbaSbubbk47qbndazgT7k59I79w7hUJLZZR2rRs9r9d1gSXCZX-bX1avWY+O93g-9sNHCInu4w06XvOuofHeLJtu24DQGA7TkOQLDvpOzAsCA7RIB4UC6kQABeLRQAAjOE+FQHkp4Aee0ZuDBcEsGBVwQZOnB4NAQGbg2UAALQAHxQNR8ERkxLHri+C6cTxfEsAJYDMcmwnAdu3G8bB-GMdJQnPsBb6KRJJIMZgem4lBUDCohmCfoeP6DARJLTsKS4GcsRkAEKmXuR4DBZfrUPhNkUe4Tn2agRRJqorlrO5Q4wp+3m+Tq7iqIFwVGdoYXmVF+7HtZCbTtoiVLAA9PljmrBJvbbJghVTqwqHoZhOF4YRBEkUUlXln5VHKSwi4tUVDmVYJUD1HYwhiUpNFIgVRUDSZ2mdRNFVTWpUAubN409TQS2hat8HzRg-VLSl21dUFbZAA).

Could you please help me with this problem? How can I control the unconnected(unrelated) nodes layout in a group? I'll appreciate it!

**Comment by soerendomroes** [comment]
Adding the `separateConnectedComponent` property [work for me](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=HYewJgpgBATiIBcoG8BQUNQIYBsDmIMAlggBYC2AXFBDgNYB0OWAnhDBGOprY6UeywwAxqRYAJLMDA4iwPNQCSAOQDCAGQCqAEQCiAfVXjF67QCVdy7hl4MADljBg5CqACIA2jggAzBAF4AZgAGABooBBA7fwBWMKgAI0RI8n8AJnjiPFIAjIBdN2soBxgEEiIQYBcGLGEygDcsBAhqBBgAVwgi22cOOorgajNFAHFxABUi5gTadzhEQswoUEhioQhgJDQlpZ6iPrLK6m0AeQB1Kx2eentHZ3lqT28-IPjI6IAWeKSEFPTMojZXLBApFJYlMqHKryW6lcpHKBpMGYaazNwlDYIQrIjAraByYDsFA4na2BxOFyPLy+AIhcLvfxfUFXK78QQiMSSaSyB5QADKugACgBBMzC8YGIwmcyWEm7G69CD9BGnC5yzAAZwgJSaEFUlUJdU4+vIdkqmI11B8uC1UAA9HaoIpsE5OBF+Br1bjwBB1FgZjgNfZmMIIORMVSVHzFHooOJ9OpdAAxcZQABq+nGJ0FoK9azhUOqtQautaHS6edROHcBPYixZSzxUCTcE2fPY9XYGuJDYbEPh0LwsMhA2owTzSyr7hblQQ7ZgnZgGvrvagAF8802Z22O120j3Vzt+4WYcfR1Bx4edlO3Nu57ul2kV72N1et637wuu4ED1eMGfKmqADBigABGCcUX9NE73nRcNUCZ8G1fQ931nWCuw+X8-2AoChBHBFwL-SCA2nD90KXD5EJZDc8wdZYfSgMB2nIcgWCwhs6MnVgQHaJAPCgDUiAALxaMDwlAqA8lox0uJItwmJYlgqKuOiaKvOjODwaAYIfbsAFoAD5GOY1jpJoMAtObMjdP3QzjMUszNO06yvyXH87IU0z1MdJyrLQ3TMI8kyWBJNTMDC71VmFdjMBw088IHahCJZG9hWfCL6NWAAhGL-wSk8h2ApKSRvLL0tQIom1UXL83wwdh0SsCSqg6s3FUcrKoY7Qariwr8vPZKrhvbQOqWOim08lh922TBOMglgeL4gThNE0DxMkoo5owG9JqfTbHQyjSLOgeo7GEKAgsUpExp846oGiy7WOu2bbssnLHqm-bzMs6qPuejAjss7q-oqjcgA).

**Comment by Vesper0704** [comment]
Thanks a lot! I implemented the grid layout with this option.
