### ISSUE TITLE
Hello! Markmap.js vs. ELK.js Layout

### ISSUE THREAD

**Issue by magnussentio** [kieler/elkjs#234]
Hello! I've had quite a bit of experience using Markmap.js to create mindmaps. Although markmap produces fantastic layouts, its functionality is very limited (basically can only include markdown aspects as the data).

I've switched to react-flow and am using ELK for the automatic layout capabilities. Additionally, I created a parser that can take my original markdown input, parse and create nodes and edges based on the markdown hierarchy, and generate a react flow diagram using ELK js for the layout.

Without diving too deep under the hood (and happy to provide examples if requested), what would be the best layout options to achieving the tightly nested but highly readable layout that markmapjs produces using ELKjs?

**Comment by soerendomroes** [comment]
Hi, could you add example drawings such that I can suggest suitable algorithms and options?
