### ISSUE TITLE
Two Sided Layered Layout

### ISSUE THREAD

**Issue by magnussentio** [kieler/elkjs#235]
Hello,

Got a question here. I'm building a diagram that has a parent node, two children, and a bunch of grandchildren nodes between the two children. Is there a way using the layered algorithm to have the two children be separated on either side of the parent node?

Meaning the first child (and hence all of its grandchildren) would be aligned left of the parent node, and the second child would be a aligned right of the parent node.

Any thoughts would be helpful!

**Comment by soerendomroes** [comment]
The layered algorithm cannot do this. I suggest trying the [mrtree algorithm](https://eclipse.dev/elk/reference/algorithms/org-eclipse-elk-mrtree.html). Since the new release will fix some issues with it, the documented options may not yet be supported by elkjs which does not have snapshot releases.

**Comment by soerendomroes** [comment]
[Here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AESpygUxwKEIDsIATHNIgRnx1LAurQFoA+SgJlvsapfaIBmfCXKduDTvzRgAxjTqSiHaXK6LGKtjNnCNU7XIAsIsoz09Kg1bICsxMzpqiKa02LnCXOk97n2gA) is an mrtree example to play around with.

**Comment by Garychen-eaton** [comment]
Hello, when will the direction=RIGHT bug in mrtree mode be fixed?

**Comment by Garychen-eaton** [comment]
Hello, when will the direction=RIGHT bug in mrtree mode be fixed?

**Comment by soerendomroes** [comment]
@Eddykasp did you fix something regarding directions?

**Comment by Eddykasp** [comment]
I haven't touched anything in MrTree. Is there an issue documenting this bug? And I think this is offtopic for the original question.
