### ISSUE TITLE
INCLUDE_CHILDREN and SEPARATE_CHILDREN

### ISSUE THREAD

**Issue by Vesper0704** [kieler/elkjs#236]
Hi,
I am struggling on the network architecture layout now. Since different hierarchies demand different layout style, I tried to give the root container (as the whole graph) `INCLUDE_CHILDREN` option to control the overall layout, and for some other containers I give them `SEPARATE_CHILDREN` option to let them decide a different layout style. However, I find that some options may cause an error when `SEPARATE_CHILDREN` is set. Here is the [demo link](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=HYewJgpgBATiIBcoG8BQUNQIYBsDmIMAlggBYC2AXFBDgNYB0OWAnhDBGOprY6UeywwAxqRYAJLMDA4iwPNQCSAOQDCAGQCqAEQCiAfVXjF67QCVdy7hl4MADljBg5CqACIA2jggAzBAF4AZgAGABooBBA7fwBWMKgAI0RI8n8AJnjiPFIAjIBdN2soBxgEEiIQYBcGLGEygDcsBAhqBBgAVwgi22cOOorgajNFAHFxABUi5gTadzhEQswoUEhioQhgJDQlpZ6iPrLK6m0AeQB1Kx2eentHZ3lqT28-IPjI6IAWeKSEFPTMojZXLBApFJYlMqHKryW6lcpHKBpMGYaazNwlDYIQrIjAraByYDsFA4na2BxOFyPLy+AIhcLvfxfUFXK78QQiMSSaSyB5QADKugACgBBMzC8YGIwmcyWEm7G69CD9BGnC5yzB49RYGY4ADO9mYwgg5ExVJUfMUeig4n06l0ADFxlAAGr6cYnQWg9UYCHw6F4Gr9RrNVodLreqConDuAnsRYspZ4qD2uCbPnsersXXEhMJ31Q6r5gbUYIRpZR9wpyoIdMwTMwXXx3NQAC+EaTVbTGazaRzzZ2RcqhaEkOLUFL-Z2FbcnZr3YbaSbubbk47qbndazgT7k59I79w7hUOoAEYyyjtWjZ7X67rAkuEyv+2vqzesx8d7vB-7YaOEWfdwvHVK3XN8Gw+B8WTbCMAHoYOWcBoDAdpyHIFhPwTOCp1YEB2iQDwoF1IgAC8WigE9whPKA8lg+Dy0vaM3GQ1CWEgq4sOgycsM4PBoGvedswAWgAPigZi0NomgwF45NQIE3sRLElCJK4+CeL4uTNwbbdFPElhJPU2TXwEj9dOU-TH1QIpOI1RCoGFDDMG-Q8-0GciSWnYUlxs3E7IAIUcvcjwGFy-VPDyGPcPzvKsxM7NUQK1mCocYW-cKE2nVQYqKJNtES5zUv3Y93IyyK3G0bKliwpM9N7bZMCw+iWFw-DCJIsiKPI6iikaoC0VqpcONihq1Ok6B6jsYQoDMlikSq0aZIcma0LmkapJkgLlpYVaMG4saoASradqgPaZLyo6rLbIA).

I want the root container to control the relative order of ABCD and the parent, and the same for the 4 servers in inner node. But when I want to add edge between them, eg.
![image](https://github.com/kieler/elkjs/assets/64687700/a542064b-c496-4b39-882c-0097e82f89c1). 
the `UnsupportedGraphException` error was thrown. It makes sense because they are different hierarchies, but I wonder is there any way to implement this requirement?

Any guidance is appreciated. Thanks!

**Comment by soerendomroes** [comment]
The `INCLUDE_CHILDREN` property should only be used if you want to solve edge crossing problems across hierarchies. It is often however used if one wants to introduce cross-hierarchy edges. I suggest adding hierarchical ports instead as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=HYewJgpgBATiIBcoG8BQUNQIYBsDmIMAlggBYC2AXFBDgNYB0OWAnhDBGOprY6UeywwAxqRYAJLMDA4iwPNQDKAUQAKAQQBK6gCrKA+gGFxASQAyAEU3KActwy8GAByxgwchVABEAbRwQAMwQAXgBmAAYAGigEECdggFYoqAAjRFjyYIAmZOI8UhCcgF0veygXGAQSIhBgDwYsYSqANywECGoEGABXCDLHdw4mmuBqTRMAcXEdMuYU2m84RFLMKFBIcqEIYCQ0VdWBoiGq2rHJ6bKD+mdXd3lqX38gsOTY+IAWZLSEDOzconyhXCJUumAqVROdXkN0q1VOUCyoIwcwWXgq2wQpSRa3A0DkwHYKGxV0YLjcHgefkCIQi0TewU+IP2zKg-EEIjEkmksnuUBUGm0eiMpks1jsLP2h2OIzOUxmEtW6wgZiw8xwAGdnMxhBByBjKSYbIoTBZlFBxPozMoAGI6KAANX0OgA8qoQcSwUIISN6o0Wm0OjEen0PcjVaj8ewVgqMEqoNa4DtFOxmux1USY8zwXCoXgYd74eFQ-sUThvAnaghkzBUzB1dGYwBfYtxitJlNprIZzOrbOQ+p9mVQIs91al8uJqsdutZBsK5s91uT6u19Whbujzaw-vQwfwgCMxbH4bLXjbU5radCc4lC8zS8rK7T7w3o73ufzOeoh83YbVE8fad1XeG8WWbYsAHoIJxDYwG6chyBYV8JSgktWBAbokB8KB1SIAAvQN92ifcoCKSDoOPf8vDghCWFA5lUPAntUM4PBoHPJ86ygABaAA+KAaMQ8iaDANj42XICuz4gT4KE5joNY9iJMvOt12kwSWGExTxMAlTgJ4-iNNQYsnEIJAnEPYttIsgydPbPTsSYllTMqcpLIlaySOkyMYGcdzMCc2NcSgdRkM9bcfV3L0vygH8WXHLx1DnQKYOgAAhMKMHfAdoshb9sQStLkuMxVgsMTKtwLD933yiUEsMYqyjjCwKuyqKIoPAqT28CxGt7My3JKnhROgULpPRHY-KGjBULjDSuz2TBUOPFgMKwnD8MI4jSLKZbMAS+a50Y6aoBYkaoGaJxhFs+bdoU86xsM2SWERVYzrEjL1Oe16lvusTyq+2ifpmv7oBawHEMRVBmyAA).

**Comment by soerendomroes** [comment]
[This](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAM44AOwUwcOAwhAHaM4DGtBDS5TOjcJdADNQZIkUYQCONIwCMaAN5E0qjNggBXOGgDaJGAC8c6AEwAGcwBo0AZnMBdIgF8JUmY1NKVazFi06+kYmaHKWNvZOamigMGCMSHxw6AAyAKIAYgAqLkA) should solve your problem.

**Comment by Vesper0704** [comment]
Thanks! It works.
