### ISSUE TITLE
Question about how to control horizontal position 

### ISSUE THREAD

**Issue by Vesper0704** [kieler/elkjs#237]
Hi,
I ran into this problem when I was trying to implement the architecture graph. [demo link](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBA1gDgM4BsCuSAuBTEAoFMATwHs1MYBtGJASwC9sAuGAZgCYAGAGhgEYAbJxgBdPGBTASIWpigBbFoSK5sAEzxRauMCADGUIgAkwAOzUpap4CwCSAOQDCAGQCqAEQCiAfUdHbzu4ASp72eNgocAB0arQg2HqYtCSmLO4A8gDqYUgQYHpWwFGmJGrY9qXM-Jx4ufmFxZUVZQBC2JgA7tjYps7EuEgs7ACstXkF1lHqwNieajNtnd29-SCDMKN1E0XT5ZWLXT19KmssoyVlAAqEetjyPZhRWOA4wEQs9p4AKpnpQQDS3gAyrYALKXZyeAAaBFWDWeYFe7xgznS9gA4p4gV9vJcAIJfIx4C7YPoAIwiSCiEBudweLAARJQjN5IQAxL68ABq3i+6UuvAcIK8IgZtWweRe2EcKVMCRwahl8ggKQe6wAZhIkNg8JKkkkUg18kkAG6IqqYEBoHUk675OmmR5k6Lq2gAD3UeMswFM90dLBaeOceKcnnc4Ui1LAali1kZlEwJAgAF5WJwojwUNh1ZhU+meGSSJhE-Jk8MM9wZMAoLm0xnRbCKSgYAy0GhgNGwMAkN5MAyYABvPAASGUZAo1DojBYAgEvGGohHJPJlOptL9mHjLMcoS+niC3O8LXSXz5oN46VcX2FngbAF9iZUYBAY3AuiR1d4iIOR2PyFQaAYKp2AAFh4fghEXYctB0fRDBMcxLDjGAHCMfdbC+EcImiPIY0KeNExTEYKyzHM8wrQtixIUtyx4Ksa3IzgG2HLYGhJZoqj4GoWPGNimn2dpDhWE51hGJdKhXFAqRpe0Ny3bwglsdEjE5GAeWPU90nPGBL2vWwRTFUc4UmBEkRYbEQi+PxvEyfTCRHPVZGSUwGkcg1UhgbjCCbFt5BwJIwGwE1vDJfsh2HIzSH-ScgJYPgEHnKDh2XMAm2k9d6RbZlfF3fdDw0s8LyvG9mIfZKnwgYA9DUD16DUbxsB-CK-wnQDpxgAQQN4Tqkpg8A4OMMwLHwlD7DQxTMIi7Cozw5CmUI5NiMzbNa3zbhKJLMsK3o1b60Mnj6kmdjKji7iDu2Royg4g5lmOAYhlGCKUrStdZMypkWUU5TVPUk9Cp04r9NvfbvIiFsiA6TA9AARz0VLvA6MKR2a4hxwAqcqgAdnYRKxAi8qykk9K3v9LLt1yg81KPP6tKKvSDORsqypJGA1BNUwACtbigUwQqayK0Zi9rOu6kDeu0fqDEGxCRtQ9DJuHabcNjGwsoWpbuFI3aCyLTbaMrWhq215jzr4q6TuqZHWKO-jWkE27VlEx6CdJVLVxk245LJhSlJU-Kae03SSpBt3mwZNQQCzNQySQeqOaR-GWvR2KNi6jYkpdonXs997sp3ew90p37NMDwGGYipnxLKGBzHVPR1SzPRvDUfmk6F4CwN4QRhDx6CJd0KWEOG5C5Ym5GlejFWCKTRb9a1xj1t16itrow2GLrJj9utopjrKU6rd4m3zbtpYjkdh7kee92MtJj6fe+-2S7p4PkeUXB4Utc03hYUEHBsuyiQox8gyQg6o4BlDJLzUwCcUZRVahjM4acFy90zqHYmOdb55wpo-f6QcgYmzKi7GAJBsBkjQHoMkIB6pkn5gLaKbUqgiw6mLFBfUB7wSGkhVWo8MLI0VpGZWI15ozw1vPDei8qI0W2mvY2+1TZHz2HvS2+Nt6XUUdgG6Z8RIX3xlfKS2cHSbm9l9P2VMCq0wBvTYGfDQZhwgFDMBboUBNzUDA2BgsGEznAsgvhqCXoe0MfJfOhccEWLweXCujNL5PkwOqNQ6p5DSCbmAWhbdPHMNFhnNhA0h5cLsGNeWfCJ6zVVsIoic8VoLw2svfWO1GIm3kTvW2nEzqNLUdde2Wj7owDEroiSaCDFezviYn61Mn6WJfonUOLYkBkg5lzMAHMwDNzcXQ+BKdsa418Xo9BgTvbBLymYgOz98FyMIYQlm1EwDXJIEQMk3g9CpNRvQhBGTmFZP7jkzhssClj3xsUqeasREVLIuI6pUjV5G3qXI1Ru8Wl8Nhc0zRwlum9Kev0-xN8jHDN9qM8xpcrENNsS2N0YBaCUO1E3EAqy0mvOGEgjOfjr4k2xVgguhzi64LLtY-G5zonVzAPQWgcMyT128LAcK7iXkpyYT1VhnzB7fJHr83h-yBGTyEQmYFJFKlgqXhCg2UKN4NMRcfeFKjD5NLNciu6pwenOyZfogJQzsojNCQSyZQCwYMkCmAOACRETeGgbQtZyd2qsDnOnFBjrdkuvJuyouYyuWErOVE4czMnxlDAPIE0eg4DQ28OqVuzz1nCzTnK5G2TFUy2VeNVV-CcIarmlq8pOrQVrXBSvQ1698wm1Neo-eEV+0dNPiiu1aKdmDNzp9XF7qTkROJSAsAJoyR1z0E3PQbjaUysjT4vphMBnOunTlBNc6JmnLTWVXYMB3T+uzJA7w6xa710bs3KIsT4mJP0N4FJABaAAfM+KqNVsB1QavzCAMhpCyCIE8T+Mi5RIHWFxbiV75iNQjmAKA1okBwB-SwZ9DcEhvquTcu5DyYAAdZuzLm2AeZ80lZB5IMhMCwYRAh7ASHTqoawuhmAaBArYECpqcVBH4kvuI2oKIgrhWpTFbAKjlVqq1Xqo1RjUGWNsfg0bRDyHOA8YfCzNQaB5DyCIEGp84Vt3tRQ91HuI4q0cJrarIEnh8RBAJD4PwARgihCwuqkp09W3LXbRRfVXa6nGsMsOi2XERwxZPkJW1Tsq6u0xSy+SbqjnjPCTyiQUgWMKCUKsdQ-noixHiIkZyaQshhBdnaDBjxTLYG-iiBwng8RBGBJ4dEoJdxAl-NMhk6o4kJG6CAbwwAYHWcYd4pKk6j2YPjSE7LybJkZoFfXegJo1AkGCiAYtcCw2MPLSwytCqnPD24SqhWALNXqxBdrCRetpFGt7VvS17TYtnQSxozpY6UvooPelxrmXZ2rbCdyk2i64kxlXYKlZTyjvtzilwLZ+60vMtB-s7BEOPUXsiem1LMB1RkgjsAE00NllFslTNmcp3xawWrVd-JdbbsBcBWU2ebanudtqTI6FB9DpWoHcotpcKbXn3tfyzHTqsVg4fnj+dPKjLAOAPcNQgV6D0ER5K0NKOYAAE45soIW-LnHp6lfnoiZXRWfHTCmD0KYREtAewdBYPkdU23dv7co4B0n5PKfU4gxpmDcHwAca49UAzj5q4czuaATXHMGODeR+k2VZ2+5M8u3k0abOyszU5y27nIXefhf529va8XPtwsHb9yX2jpcxqnUt++pjOWQ5TYN4BcB8hlEjss4NtOS3Ha8ej5vi3WXLY5Umzv628CGafPIa0q6IAc2wIWpqdO3kVqz5LHPPz88NsL-d7Vpeqnl9ez2qv4vml15r0i-7yWdFm4y8Y8HHf8fl0XcACO9dqrLKbqHYeJ0oMq9yv7Y53wHKJr4rK6lQL6x4YZoCkr1xkgQA-pb4j4G4Z5QSObSws556FLH6CLNoPY84X6SIRYC5RbV7C5fZKJxa37WpP5S69IQF7I4qK6f5wGGSLryDZoUjRyYDeDyDTZYHpJ8Bo5Roy5ZyT5BK47cHW48oPiL4CpwAFDEBgA9g06p4gEyoM54x4G5KH5EF3akFn6ay6odqX6QrX6by0EXS17KL14sGN5sEYpY4cGuof6z5f48qLqkL0BIDRjIENRiFp6vKSEm4yGHrm5QEKG+E8EjgqGIEwBCZmC5pgBoAYFWbiGvI4GGEXb4G548KTRmGlLF6iJWFhaUEV52HMS-b350ES6uGoqPTsFxpt54rHJKHMSLpqD0DrodBwBkjLIQDhF6HtSYwJTSFA6y6xrHrQFnq5bwEPjXqroxgzDqgb4cwsDpGmCZHZF-qAYvhqBvjYAfhfjFDiZEYuJRAkJkIUJUIp7DhMbQasbh5ko6acZ6Y1BrF8Z+pqB6AcwdBuhNzqgsDL6kLqhr4b5FpUbx5kiJ6LIvFvGaafGR6-EIHXrXLqgdC0BwAQA9hQAsDGYoGk7oHHEwB+oaFEBaGb7hRolh7sbfFR4oYIFAA)
Can I move the node from pos1 to pos2 ? The three nodes seem to be on the same layer. 
![image](https://github.com/kieler/elkjs/assets/64687700/1ef44cf7-6542-4369-bbc2-935850cabc40)
Thanks!

**Comment by Vesper0704** [comment]
And the same for this one: [demo link](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBAbhAxgZwC4CgA2YCeB7AV1RgG0ZkBLALwFMAuGAZgCYAGAGhgEYA2VmALrowmYHhAVUUALYNsOGiBoATdFAqKwIRFBwAJMADtlmCoeAMAkgDkAwgBkAqgBEAogH1bey-ecAlV2t0GkwAawA6ZQolRFQKPEMGZwB5AHUg5AgwRDNgcMM8ZRprQvpuVnRM7Nz80pKigCEaVAB3GhpDe1xFZAZmAFZKrJzzcJVgGldlCabW9s7ukF6YQaqRvPHi0tm2jq6FJYZBgqKABWxEGmkO1HC0cFQaYBwGa1cAFVTkvwBpdwBlSwAWVO9lcAA0sIsavcwI9ngx7MlrABxVz-d7uU4AQXeenQJxoXQARiFkOEIBcrjcGAAiEh6dxggBi704ADV3O9kqdODZAW4BLTKjQsg8aLYEoYaLEVJLpBAEjdlgAzETIGjoMVxOIJGrZOJwOFlVAgAiawnnbLUwy3YkRFUUAAeKmxpmAhmutoYDWx9mxdlczmCYQpYGUUXMdJIqDwEAAvIxWOEOJgaCrUInkxxiXhULHpPH+in2BJgFBM0mU0KoaTMDBaQQVcTpMSVXBEO4oLSYABvdAASHkhGIZEotAYPB4nH6gkHhJJZIpVK9qGjjNsgXerj8HPcDWS725QM4yUc7wFrhrAF8CaUYGAAI7YTCIN-uAh9wfDoikcjUMpmAAFg4bg+DnAd1E0bRdAMYxTCjGAbD0HdLHeQcQgiLII1yaNYwTAYSzTDMsxLXN8zwQtiw4MsK1I1gawHNYakJeoyi4ComOGFi6m2ZpdgWA5lgGedSkXTByUpa1V3Xdw-EsFE9DZGBOQPI9khPGAzwvSxBWFIdoVGWF4ReGAMQCd4vHcVJdLxQdtUkeJDBqBzdUSGBOOwOsGwoBVKFQKhiXcJ0e37AcDPwX8xwAhguAADhnCCBwXMA60klcaQbBlPC3Hc9zU49T3PS9GNvZL7xERBQmJMAqAIdxEC-cKf1Hf8JxgYDQN4fghHCqDwBg-QjBMXCkOsFD5PQ8LMLDHDEPpfD40I1N00rbN2HIgsixLWi1urfSuOqUZWNKWLOMO9ZaiKNidnmfYej6QZwpStLl2kzL6UZeTFOU1TD0KrTit0q8DvkRQYVNY0ERgIEbGs2z8Wa1KQgbYBQhVKhDAAK0QOB3GkULByRyLWvHMoAHZmES3rnrE5GJLey4ZKyjdct3FT93+jSip0vSibK8qihgCAaGJLGWix5QIHcYkmuJkc-zJycgM4HggKSyCNAGnQhvg0bkNQqbptDbDIwsLLFuW9hiL2nM8y26jSwoctbcY8LmOO3iijOomLp466+LmPZFmEp7aaKcT0ve70WbkhSlPyrnNO0kqDoM7zaXF1LECoRBpcQQnwvlqK2opqmVg1wWiXpqOmY+7LN2sbd2b+9Tk6Bvmi4FsqysJGBHydZQ0DAFVOxwOWWsVmKYDV1X1Zp-qtB1uCRsQg3JqJmbTdGha4yWx2bfojb7co7aaOduiqwYg6PbyE7vfKInb6urZGn4u6Q8eomXqXKS65jz6ccfqJzbjzVORMvIo1pLEHAiBiSIGAMgdwYBC7F1JtPcmCUK40yrpHRmNo1yx0bs3EBAMU7Azdj3USQsaBGEfDnWh7hlAT1wAraK7VOqcG6klReg0V4IXNuvNCm8TbhjNnhPeVtD5X2PhRKiO0L6uxvtxT2AcH4cSfiou+XsaC3WDkJL+4dq6vT-gQ2S30E4cwKtzQGvMQYQMMnkYyTxTKw2sPDZwdkkYZ2QAQKgFBSSXBlqgiKbDS4MDiirbBvsf4M1MczQBxC8pWKTmAihB0BZ9xoKEPAeAWyPmUMguWoSS5KxnlEtWGteHL2GgIqw41Da+y3mIneMZJEH1WkfTap9Ha7Xom7P2qjX7sXOoM7RajdHv30Q9DqYdcE13wQk7KFjfqc1AbY8BRdIH1lpFARABBHyix0O4YAISSnoPapE6mvt5kmIygAhubNSE2PIZ3cK3dv73mUAQaQ0gcDuD7mFNBU92ocVAuBHB1TYK1NGv8VwOI-C4g8F4Hw-hAhNNEXNc2u8CIdJIjI7p8jz4u36WnZ+98Rm+3JTovRgkZkiSLrE2uZjY4rOee3OxAyRBiAkFIWQMAwZKFUEXGaUQYhuSSGkIIjLShWn-rcZx0N7A2FcNiPwAJXAoiBFuf4vttkNhwI8PJopDDILOZPdhZQ+DXKLrc3+9zCGJKeSk9Zrz7FdxiV85QKpMDgDgcFYp5yQVWoqfPG5ULdar0EQ0jetrmlYokbioinSCUnyJU7ElV8BljJfmxH2trqUTNpfdQ4syblMsWfXL68dVnWI5ZsrZ9MGzICgCqUI4BWzBMDUGy1sU2A2ttRW+JVacpN2Sa3MhHd3UepnUYmA+BgAFJoLQdwcBA0WvCeUuelcI38P1jG4RcbMXiItu05N+L1qErPhmy+2Zs2FuGfmouD6bpTLpaWhlMqI4LOHQ86twCXWTs5WndOUCFRvjAHgWIH4zk9s3Rxcus4cFGLwb+x1jyx0tzWUBht7zfYCyrvOyDwBgAtAgCAdwEB12sNKdPWe5Sd1ayXtCvWa8D1G2NlhFp802lJpWhesiabr19KzSBl9p1H4Fq0bmwOAkS2h3LXTO50d0P-ssROl5U7s36tpE6KAbYs4UAarBjdZSuD9uibau1cSHWySSVhutaS3l4dnYRqgqVQgyhdA1ajJNg3K23ch3dMK2MTUPSK49rTLZ4ttrIh2CjM13rE9JilT73YpZpW++Thiv3GPtSp8xNb2VOend4qBGp2gQGJE6JBygTM0YuexCzSGbnWeZUs1mmHisbPSTcgjBHNgwGJPmHAIAoDIBaMghgOBiOkfI5RmAABaAAfPOvAi6igrrXUC8K5H4i8pwHcSGijpTIGWGC-DTTpg0BgCAYwYAnR4AoCqD8DB3P2i8zQHzK21sbeXV97bNy9viEkId2EJ2aBnbOqMgb12HyoB0IgNtY8GARh9X6oKTolurYXUurbgbgcHaO+ACHUPygw-5oOXu95RZjekJcQpKoWF+d7R1ECXCIVE2C6x6NYWjbxpPTi-e57YtXt6Yo0lmijrjMfZJnNFLi2fzLShn9tnWVFcA5p4DDiDgQ3FNDNxHivGgZ2VQZQoQigqidC94kITTMYMQxrIdaunVdc1-W3rLnCMEEQJgCMj5iQUdCMU+37V6OVMhUxvhIXeeNIi1xhNp6+PWxTZeoT4vEv7SpRliZaXxNvyDu+hTuXUMu+WRrjTHvnM6cMDVEeUAffuBVOahr-mZ6gRa4OpT+X5V2edZXkrAyPlzvAMSZQxJiRUGkO4FoIfW+s-D2Gou3Oo31L5xihPgvePC-46L9PCXb1Z+fTn2XGjj-S5kwXuTSvP1tcrX+oB6nsNa9wzpv5xJgAZngWa3zYSymUwHRV2U17yIX72fyr1K2H1vFvD7kHj2TAFSkm3HjClDxDUC0HBXzqTGnXwHAFyizPV3y6X32JUP2vkHHz0pXl0y0L2y2V2dwK3VwAwHx607h01CAoDABaBqjwCgC7SBVQL7Q7ySnoJANdxIXd0H30mgLvCFj0ybGyGUH+VnxQPn03UXwgkwP3RwLwJ42ixFyILkWEwl1E3IJPzzUkwoMVwMToO7xswYMATZQkJYPdR0xUAQWQFAEwHcBoFQQEO4C4CiU7zvzQz7zd2YLdVKnQBgPvBVEfGQDwFCGAG9VXSaj8PUN6k0NCzjx0OxW3ykVT0E0MIz1IMYgoPzUsKyxvyehEJZQcIr3AMkO-CbVpAjEQBACQGkCMxQWZz-2nnMyEJphqI61HXEPCK0ykKiJkJu2zjABoAKTACb1SNULKXSIwKjxqR5zX2yMi10IIJTwEztiKIPyUVMIv1SwsLMNkw-msIZSGJHUcLGO1xNwbAR2ADACgBaGkDwCYV8OWIwSwSCLuIf3s26wiImNvEGzhEQAQJoEHncFCAYFiPiMSOSLXR+zkLVEQEUJnyakJ1B2JzAFJ3O1YAqAhLhxAHH2zhaE7DAAYBmLmOUAWKZx+yfBfDfE7AIDGEDxkAZyb3CB9z92UADyD1xIkBB1QDB2OxdlO2JNJOCDhyuBVBaDADgGUCdCmxgDgOhMQPcHHnRIb0xOxOUPsjFKJ3B2lMh1lMmKAA)

The two nodes at the bottom should be on the same layer. I found out that it is caused by `layering.strategy: STRETCH_WIDTH`, but if I remove this setting, the parent node will be too long. Is there any solution?

Thanks!

**Comment by soerendomroes** [comment]
I suggest to use partition, which is only possible if you do not use include children.

**Comment by soerendomroes** [comment]
Partition will solve your problem. Other options such as interactive strategies described [here](https://eclipse.dev/elk/blog/posts/2023/23-01-09-constraining-the-model.html) will also solve your problem. But they can only do this if the graph is a normal graph. For `INCLUDE_CHILDREN` to work, nodes outside of the hierarchy are put somewhere in the normal graph. This messes with all of the existing ways to influence the ordering.
Hence, I recommend to not use `INCLUDE_CHILDREN`.

**Comment by Vesper0704** [comment]
@soerendomroes I see. Looks like I have to make an option, because not using `INCLUDE_CHILDREN` makes the layout in my scenario more difficult to control due to so many hierarchical nodes/edges. And I'll keep trying with other approaches. Thanks for your patience!
