### ISSUE TITLE
Question about alignment

### ISSUE THREAD

**Issue by Vesper0704** [kieler/elkjs#239]
Hi,
I wonder what's the difference between `alignment` and `contentAlignment` ? They seem to fail to work in some cases(eg. alignment: CENTER fails to make the nodes align), is there any precondition for them to take effect, or maybe some options can override them?
Thanks!

**Comment by soerendomroes** [comment]
`alignment` positions nodes appropriately inside the layer bonds as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQHYQE5qkCMaA3kWsxsAEY4hoBEN3RAXzIUqpAEwMmLTFggBXOGgDaAZxgAvHOgAcABgA0aAMy6AulOagYYUkhyk46AEoBJAOIAJACpoA9L7QPYBVqCDQcADMInABjRTVSGKp4NEoImFIcEMQqGTw0AHcYAkQ0YFICNBgQhHsktAAZAFEAMS9DAGEmgDkvJqdDcsrXTy8LVg4ubjF+IXJKaiNJFjKQa1t7RzQu3v7xzEmeI1miQjBROgBaAD5qMVOCc+or29IjIA).
`contentAlignment` works for the content, as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQHYQE5qkCMaA3kWs9RTgMowBeOAdAMYRSAZzhRgMUnGHoAsgEkAcvNkBVWQH128gFoBRJi3KVOPXkkkwkAV1RoARAAoaABhe8XAGlfuXASntDZkEpHCkAQRAYMFIkMLh0ewAJDQBhPUUAFT0AJU80ADUNACEAeUzM0tlAlgxgACMcEAcaQKDWSjRJUjw0AHo+tHlSHqgOnHzEKhC4eMmEYDgu4TRQaJ7iAF8gA).

**Comment by Vesper0704** [comment]
Thanks! that's much more clear to me
