### ISSUE TITLE
How to control the horizontal position of connected nodes?

### ISSUE THREAD

**Issue by Vesper0704** [kieler/elkjs#241]
For unconnected nodes, I use `partition` to layout. What about nodes that connect with each other? In this [example](http://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBAZgIwCYHsC2cBQAbMBPFAVwBcYBtGAZwEsAvAUwC4YBmAJgAYAaGARgDYOMALqYw2YChDViUNM1x56Iekkz1sAawB0SaioDGxaigB2zAEoBJAOIAJACqZKEMAeqng20yiT0Acr5MfBwczq7unt5BgX4AQvTEAO709KYAMvjKlMy8oc70ruDE9ADCZqb0RqrlaBBmacQ58OKU9JhFxsZmHl5uxgBuYCXMxCCE7T5+AAq4BvRojdoIOnDUAB6qAILY1MCmi6bEzOkAogBiDgAiAPIA6v6YBmYlRzt7B43MAERkdgD6Z0uwm+TxAKEoNE8AFkPNQ0HRhiZTNo4FJ5rF6NCgtgbiA-CBRuNJkEYAN6GBgPRKDAAN6YACQiiIpAoNAYzDYABZuDBuUJRAzxJJpLJ5DBFMpVIyoNRlGAQAYoHg7GBTEhdp5mFZ-KV0gBVK6nf6lOxWdJXCynR4MjQ6PSGbrmGC3B6MlxuXrRPyY3JhBkeyJeKYBIIJZKpDJZEDNNgAVndES9qippyQVPDKTSmSUMeYCYDSaiKdD8USWajueaBZDszcCyWlDGw3owDwzDiFi2-iNAGV-gBpG6nabnRmS6RRJvFVvtmDpG7+GynXsOf7TLYOOyMkOZBAaSjaCBzBtHH5-QEXBw8ABq-wcN2mPB1vasRpB7sKCpb5VMlWqSC1PUlRHM0cCtO0DKdDIyJev01BDCMMBjBMjJ2keYBIHoWowL8xAoBAAC8LAcNo3DYPQcDEMRpHcAgKDEPhaCEXGZFcNIwBQNRJFkR+Qq7PshzHDApTWg4pwWIyzxHI07yCV8uEXqJ-jiRYH47qSYBogAjokdKMky+AsuQVB0ME-I8PyIgGbK8qKsqqrqpqwDav4dgSVYTgMraWgYVhvTnvhRE8eRlHcbRXD0Yx6AsWxHFcTRvGgt5gZeiGvohAZqVROlYblpGObZJyBYMrWJ5Cdo04tm2Jw6qcWwWP8vanDY0Jib2Bm7mA+7YIex71kJ54AtY9jXjAd5xDcDgPtCPA3PqDivu+yWGbmXpVSUNUwKuVoOKa-x3G+W6YJ1pKILI1A0vS3mrcZbJmZyPKWTy1k3bZ4D2SqaoagFMA6u51hed56GuP5OF4QRiWhVRUORQxTGxdw8XhUlBmFp6OUxEEfpo9lwZY2WEbZtGsYlaVQR1vMFUbbOtX+PVjXNa17Vo11PV9eVCm-MNtiOLe-yTdNNyzTA82LW+px8d5E7rc2m1ztCOoHUd24MqzZ3YFASAIBA+k3bdJAmeywRPTAL2Cm9cofUqX1Ob9-0eUDwO+aD2EuYpQWwxRMMhXD0XMaxSN7AlIVSylRb4z62OZfrePeqW9CZgVJPFWj5MzJzRyVXLtPznVDVNS1bUqR1+tsweR6Z8J3P-CNfPjQLU0zXNC1LZLK1owAvgZ3feSGMBIHA2vUGAevS0Zhv3RyfKm1ZFsMu9Co245P04Q7gNoyDmFu4FkO+97KN0fDMWB+xweH2Hce5X4OM3VfBOJ-lxNVqnN1lQNjY51t6T54zRcs2-IIe4K79SplzC8dcxoTSbsLFu4tlpoxllOL+CslaHSuMdG66s-AwCVJQPwwAx7jwIJPUy09TbmzTovT6K9nKuQBp5NOW8wbuwhsFCKB9YZRQRqfZGUMw7oyDPHDKeQ073yjoTCshU8x8jJuneglNTzEGzjOb+v9C7MxLmncuvVK4fzPIpHmo1+aC2bqLVuEt1I3V7n3TSEAvzUCIQbVkZCTa8kofrahy9vp0L+m5R2TCXbb1+mwr2YUuHHwDnFc+-CVrhwxpHBOt874R2EXlImlYiqyO0RTKuKjqpzh-vTAuTNi6LRyX4YBujQFKKGrXXmUDG5CxFmLNuVjvI2NtOmegMAIAgCSAYEA7tIAOJgAAWgAHy4KgPg1sTi+kmFFHgfJ59KiQj9P6DpPcDIlhgNpEwCA0TMEHsPMA2gRmuEcZM+ACALqHjgJrbWutrreQWVIGQyyqqrOpM0PImze6937sQAwFEdZj2ZKQ42zAKEChslbJeDkfH238RvZ2OhXYhLIJ7fe4TfbcJPtEziF8VriKSTHQRaUH5J2flk+Mp0M76OUTTNRxS-6aPKbYyp3UQFVzqZAkxMCWkWIQWrBkgLSTaTgMAAwcAroGQhS4qFZt3Gwu8l4xFds14osYWivyO8PZ7w4biiK+KolByJbErKqTr7BFEfEoRNrqWZJkXSzlCi8nMsKeo0pAD5FVI5oyvlDSBXNLgW05KjJe67O0gMeYSAwCjBBfQMF1ytIoF0sok5CAR7nPsZcsebylkrKJWs35+QxVoW6TAYAfg0BoAGMwSV0rZXjKmcC0FzyDKFo+cWripaNmRswN3IAA), I want to place node1 and node2 in the same row instead of conforming to the `elk.direction: DOWN`, is there any way to do this?
![image](https://github.com/kieler/elkjs/assets/64687700/f457da83-825b-4fc6-adc6-7cfed56b71c6)

Thanks!

**Comment by soerendomroes** [comment]
Edges between nodes in the same layer are not possible. You could however change the layout direction for the three hierarchy levels or use hierarchical ports to split the hierarchical edge, constrain the nodes to be next to each other and use nolayout on the edge connecting them.
