### ISSUE TITLE
Multiple edges to single port without being a hyperedge. Possible?

### ISSUE THREAD

**Issue by jonmcgill** [kieler/elkjs#243]
Is anything like this possible? Big single port with one edge coming in but multiple edges coming out that are not connected as one "hyperedge".

<img width="365" alt="Screen Shot 2023-09-29 at 9 22 28 PM" src="https://github.com/kieler/elkjs/assets/13082333/8e4906db-7ee9-43b1-8cb5-84c2934f6b7d">

**Comment by soerendomroes** [comment]
Have you tried adding multiple ports and forced them on the same position?

**Comment by jonmcgill** [comment]
That's a good idea. What if the port sides and positions are dynamically rearranged, though? This is not in the context where I have specific control over the x/y of a port.

**Comment by soerendomroes** [comment]
Then it does not work. You need fixed port positions for this.

**Comment by jonmcgill** [comment]
Good to know. I'll still play around with your idea. Thanks for the thoughts 👍

**Comment by soerendomroes** [comment]
[Here](http://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAMYQB2AzjAXgLIS0gDyUtUAdGUgA4U7k4ldHWYARAKIAZAPrMASpPlEi5RjjRqAElh54JBMBoDeRNOc3qpwAEY4QlDj0wkcSAXHQAiLTIDCEgByACoS8mgAajLBzAAKaACSgQDKCZJeZhaYdiBoXoEQaDp6UAZGGRaWtJoAjGimlZV8UHB+FJRwUMAwgsJoAGIJABoSYjKxzMmZjWjNcLN1DTONAHpzHNS06BIAgsnB040AvodN0PM8AEz1p8tr5xs0ONt7B8toJ+9zswDMN++Ve4tR5bNC7fa3cyfCzQ8yEIy1Jx1AC0AD5NJdDvCNOQak5rmjND8sYYcXieH9CeQACwqSpqarkTGHBk44ks9SaWknVSchC6fSk-4WVnWHKOZzAVzuQTeXwBEJhSLROKJFJpCQVLK2ex5YqC8p0kWc3HCmZzNpUTrdXroQYjMYTKZfc4LM0AoFwEHPMGvSEfQ6wtDYxE8FHopkkhG4pFoKnEyohmNhuMR2kcxnM+km9nZxnpo5AA) is a small example with no hyperedge and hyperedges. I am not quite sure why you want no hyperedges and how you want it to look like.

**Comment by soerendomroes** [comment]
Wait, maybe [this ](http://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAMYQB2AzjAXgLIS0gDyUtUAdGUgA4U7k4ldHWYARAKIAZAPrMASpPlEi5RjjRqAElh54JBMBoDeRNOc3qpwAEY4QlDj0wkcSAXHQAiLTIDCEgByACoS8mgAajLBzAAKaACSgQDKCZJeZhaUPMAkMORgTtBwscXoAAyZ5ph2IGhegRBoOnpQBkYZFpa0mgCMaKZdXXxQcH4UlHBQwPlC6ABiCQAaEmIyqZJVQyNwAIIgMGDk7oIcOMCT6AEhYVvDxWg8-YNDrwB6OxzUtOgSu8nBO4WAC+QPMO0eACYBmChh9il8aDhfv9Aa9zKD0Y8HjwAMwwrFdeGjRE-NB-AGwzEgraEIx9Jz9AC0AD5NJDaYYNORek5oazNLjOfSeU58QLyAAWFRdNQ9cgcrZy7lCpXqTTS0GqdUIXT6LkEizK6y1RzOXJuDzeXzXULhKIxeJJDYSToWGr2eotfUdGVG9U8w2vHbjKhTGaCYRoRYrNaxZjJWEQp5BwnEuCk5Hk1FUrbU8x07m8lMSjldQsMkts8hC8sG0VVjV+8zK9nN7oq9utqUqYFAA)looks more like it. The idea would be to create ports with no spacing between them that look like one port.

**Comment by jonmcgill** [comment]
Ah ha! Yes, this is excellent, thank you! I'll play around with this in my context and see if I can figure something out. Huge help.
