### ISSUE TITLE
How to cuts with "Manually Specified Cuts" layered option

### ISSUE THREAD

**Issue by DimitriChauvel** [kieler/elkjs#244]
Hi, I want to make manual cuts in my VerticalParent node, but I don't know what the value I need to specify in `org.eclipse.elk.layered.wrapping.cutting.cuts` looks like, I need it for elkt and JavaScript. Thank you.

[Manually Specified Cuts](https://eclipse.dev/elk/reference/options/org-eclipse-elk-layered-wrapping-cutting-cuts.html)

```
node VerticalParent {
    org.eclipse.elk.algorithm: elk.layered
    elk.direction: DOWN
    elk.layered.wrapping.cutting.strategy: MANUAL
    org.eclipse.elk.layered.wrapping.cutting.cuts: [2] // Not Working
    
    nodeLabels.placement: "H_LEFT V_TOP OUTSIDE"

    label "VerticalParent"

    node n1 { label "n1" }
    node n2 { label "n2" }
    node n3 { label "n3" }
    node n4 { label "n4" }

    edge n1 -> n3
    edge n2 -> n4
    edge n3 -> n2
}
```

EDIT: I'm sorry for the `bug` label I couldn't change it.

**Comment by soerendomroes** [comment]
This is indeed a bug. Elkt does not support lists and hence cuts cannot be manually added and the switch statement deciding what strategy to use does not work for manual cuts in elk 0.8.X.

**Comment by DimitriChauvel** [comment]
Ok thank you, do you know if it works on previous version or with json ?
