### ISSUE TITLE
Mocking a swimline-like layout

### ISSUE THREAD

**Issue by peerpalo** [kieler/elkjs#245]
Hi everyone, I would like to use elkjs to reproduce a similar layout with layered algorithm

![image](https://github.com/kieler/elkjs/assets/6475341/72bda9c8-a2f3-4604-bfae-9e21c2de1f09)

I've already tried partitioning without any success. I've already searched for similar issues and, per my understanding, there's no way to do a full swimline layout with ELK. 

The thing is, actually, this is not a "full swimline", as you can see the layout should have a right direction with only specific nodes that could have a down "detour". Is there any way to do this?

**Comment by soerendomroes** [comment]
You could try something similar to [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQHYQE5qkCMZFVpATGgN5Fqdo4gDWAdAAdgBAjFJh0AIgDacCIIC8ABn7KANCBwAzOCrXqARhDjyk+jbDAI9q5QF0pHLjwFj8AYzgwIpdABEAeQB1ADlnTnJKaiYmCOoGGIBmeMIwRli0AFoAPmSiAF96aNIUtMYabLzmInKYquokoA) with fixed port positions on n2.

**Comment by peerpalo** [comment]
> You could try something similar to [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQHYQE5qkCMZFVpATGgN5Fqdo4gDWAdAAdgBAjFJh0AIgDacCIIC8ABn7KANCBwAzOCrXqARhDjyk+jbDAI9q5QF0pHLjwFj8AYzgwIpdABEAeQB1ADlnTnJKaiYmCOoGGIBmeMIwRli0AFoAPmSiAF96aNIUtMYabLzmInKYquokoA) with fixed port positions on n2. But I guess you cannot force the last node to be where it is currently at.

It's actually what I did and yes, with fixed port position, it's closer to my initial idea. The problem is the last node: no, you cannot force the position. This is the final layout

![image](https://github.com/kieler/elkjs/assets/6475341/0355a2d7-8c7a-457d-8fcf-e6ec1e43bafb)

Basically each new "right node" start from the previous one and then goes on bottom. I don't think there's another way with ELK.

**Comment by leonarddietrich** [comment]
A little bit late to the party.
I implemented a swimlane layout, where nodes get an extra lane index property.
`algorithm: layered
    nodePlacement.strategy: SWIMLANE
    
    node n1
    node n2
    node n3
    node n4 { nodePlacement.swimlane.lane: 1 }
    node n5 { nodePlacement.swimlane.lane: 2 }
    node n6
    
    edge n1 -> n2
    edge n2 -> n3
    edge n3 -> n4
    edge n4 -> n5
    edge n5 -> n6`
It looks like that:
![swimlane_example_simple](https://github.com/kieler/elkjs/assets/73589771/a89e926b-062a-422a-b68b-fc37b99770ec)

another example:
![swimlane_example_multiple_lanes](https://github.com/kieler/elkjs/assets/73589771/3748b019-8301-460e-a84e-526f6e1ffb68)

and one more example from wikipedia that I replicated and added a lane overlay:
![test](https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Approvals.svg/1024px-Approvals.svg.png)
![approval_swimlane_with_lane_overlay](https://github.com/kieler/elkjs/assets/73589771/3991daeb-183e-4f7b-9b25-542be990fe7d)

**Comment by lee-chase** [comment]
> nodePlacement.strategy

You have a codesandbox or similar demonstration?
