### ISSUE TITLE
Do elkjs support collapsible tree? 

### ISSUE THREAD

**Issue by zeyupan888** [kieler/elkjs#246]
Hello all,

I guess this is more like a QA, I'm wondering which layout option supports collapsible tree? I'd like to click the node to be able to expand and collapse, the behavior is demonstrated in[ react-flow ](https://reactflow.dev/examples/layout/expand-collapse)
<img width="1026" alt="image" src="https://github.com/kieler/elkjs/assets/71034205/bfc5b052-d2ce-4f6f-b827-d80359c1ea05">

**Comment by soerendomroes** [comment]
This is not directly supported by ELK. react-flow or other libraries that use this feature together with ELK change the graph structure they parse to ELK.

**Comment by zeyupan888** [comment]
Thank you @soerendomroes , this answers my question
