### ISSUE TITLE
Target nodes are not centered

### ISSUE THREAD

**Issue by zeyupan888** [kieler/elkjs#247]
Hello all, would you please help out?
This is my layout
```
const graph = {
        id: "root",
        layoutOptions: {
            'elk.algorithm': 'layered',
            'elk.layered.spacing.nodeNodeBetweenLayers': '100',
            'elk.spacing.nodeNode': '100',
            "elk.direction": "DOWN",
            'elk.layered.centerNodes': 'true',
            'org.eclipse.elk.alignment': 'CENTER',
        },
        children,
        edges: nodeEdges,
    };
```

But I want to make the target nodes centered between two nodes. For example, w0w1 and w0w0 both points to w0w2, but w0w0 is not centered between edges. Thank you

<img width="403" alt="image" src="https://github.com/kieler/elkjs/assets/71034205/e250694c-2c19-4053-a8c5-f6cf76c8c7ee">

**Comment by soerendomroes** [comment]
Have you tried setting bk.nodeAlignment to BALANCED?

**Comment by zeyupan888** [comment]
Yea, I used `'bk.nodeAlignment': 'BALANCED'` in layoutOptions but still not working

**Comment by soerendomroes** [comment]
My bad, I mistyped the name while on the run. It should be `
nodePlacement.bk.fixedAlignment: BALANCED`, as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAHYQE4AKmAxjkjiXAHQBGA1swGYwAehAQRAwwJBk3QAhAQBkBAOQDCAUQAiRUuRxoSARk0UdAJgPaSAZiKEwZ3WgC0APmNWCNnXac7zQA).

**Comment by zeyupan888** [comment]
That's working, than you so so much!
