### ISSUE TITLE
what's the best practice to hide or show children when click on the node

### ISSUE THREAD

**Issue by zeyupan888** [kieler/elkjs#249]
I have a use case that when click on the parent's node, I want to completely hide the children(with parent's node's width and height restored to normal node's size)
And when I click the parent's node again, I want to toggle the visibility of the children .

what's the best practice to achieve this? Thanks

**Comment by soerendomroes** [comment]
If I remember correctly, Klighd https://github.com/kieler/KLighD calculates both the expanded and collapsed representation and switches between them.

But I do not know whether this is the best practice.

**Comment by zeyupan888** [comment]
thanks for replying. 
> calculates both the expanded and collapsed representation and switches between them.

seems like this is one way to solve it.

but in elkjs, if a node is set to be hidden, is elkjs automatically handle the positions changes based on toggle of the parent's children?

**Comment by zeyupan888** [comment]
my approach is that, if a child is hidden, I remove the child from the graph that passed to elkjs' layout.
but this approach is quite hacky.

**Comment by zeyupan888** [comment]
if there's an option that allows elkjs to ignore the hidden children, meaning doesn't account for the children's position(because it's hidden), then it would be ideal.
