### ISSUE TITLE
Mrtree algorithm direction property being ignored.

### ISSUE THREAD

**Issue by acollazomayer** [kieler/elkjs#251]
**Describe the bug**
mrtree direction property is not working properly, changing the direction does not change the direction of the tree

**Expected behavior**
mrtree direction should properly set the direction of the tree, 

**ELK Version**
0.8.2

**Additional context**

**Comment by soerendomroes** [comment]
Our documentation sadly only generated for the nightly (with is not available for elkjs). Hence, the direction should begin to work with the upcoming 0.9.0 release.
If you want to layout trees and cannot wait, I recommend using the `layered` algorithm instead.

**Comment by NiklasPor** [comment]
Should this be working in `0.9.1`?

**Comment by soerendomroes** [comment]
@NiklasPor I hope so (at least the last time I tested it)
