### ISSUE TITLE
MrTree failing to layout Flowchart properly

### ISSUE THREAD

**Issue by arrowhead-404** [kieler/elkjs#257]
This may not be a bug but more of a question.

I am migrating my flowchart builder eclipse project into a web-based ReactFlow app. For flowchart layout I am trying to use elkjs. My flowchart is a directed cyclic graph, with a Start and a Stop node. I am expecting the layout to be hierarchical with the Start node being mandatorily at the topmost place, and then the rest of the nides should be placed like a tree and cyclic back edges should follow the natural direction from source node to target node. I have tried layered algorithm earlier but it failed to layout as per my expectation. With MrTree, Interestingly when I created a simiar structure in elklive, it is showing the correct layout shape, however when I use it in my javascript, the shape is messed up. The layout options are identical in the elklive and in my javascript.

**Expected layout**
<img width="239" alt="expected" src="https://github.com/kieler/elkjs/assets/3316054/ea605a31-e90a-469f-9453-b90e1b06c480">

**Mr Tree layout**
<img width="333" alt="actual" src="https://github.com/kieler/elkjs/assets/3316054/82e5a9ac-1bff-42c6-b55d-f132c4b9ee1f">

**ELK Version**
"elkjs": "^0.8.2",

**ElkLive Demonstrator showing the correct shape**
https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AESpygUxwKBxAGsA6AExlwGM4YIA7FAEQHkB1AOX2AGcAHHLQBKwOhBQAmfAODUYDMKQYRyOTqpwoAjAAZdhcmBzCIAVzqKAsppQBBAGqsAkswD6rBwFFhAGTsACjI4wFDUCKxQalAsAGIAyvgqami8cKFwBsk4aABGvAhJmmgq-NpFKQBm0L4QEPwVOTC8nDgA7rEwIATZaPy4-KE9xc2cZiAgjWg4DOSd3VOl0r1p9QY4RjlpGbpoALQAfHkFhsbHCPtHpeUbZ9eXaNVQtfWnOU8v-A+r-OubjzU6l9DmhRu15gRbk0WuCujkQf0cINcG9QTCOnCHktUYjkfCjqNxpMoWixhMHjM5nDUYTySDsSSllj6togA

**Layout Options in Javascript**
const elkOptions = {
  "elk.algorithm": "mrtree",
  "spacing.nodeNode": 50,
  'aspectRatio': 2,
  'elk.direction':'DOWN',
  'edgeRoutingMode':'AVOID_OVERLAP',
  'searchOrder':'DFS',
};

Any help with this problem would fill me with a lot of gratitude.
Thanks In Advance,
Soumen

**Comment by arrowhead-404** [comment]
My Further Investigation revealed that elkjs layered and mrtree algorithms fail to layout my flowchart properly when there is a cycle in my flowchart. I tried with flowcharts without cycle and layered algorithm gave me PERFECT result.

**Here is my fowchart with layered**
<img width="435" alt="image" src="https://github.com/kieler/elkjs/assets/3316054/3aa54c78-bd47-4fd5-a868-68516e7d672a">

**My Layout Options**
"elk.algorithm": "layered",
  "elk.direction": "DOWN",
  "elk.padding": "[top=25,left=25,bottom=25,right=25]",
  "elk.spacing.componentComponent": 25, // unconnected nodes are individual subgraphs, referred to as named components
  "elk.layered.spacing.nodeNodeBetweenLayers": 25, // this has effect, but only if there are edges.
  "elk.edgeLabels.inline": true,
  "org.eclipse.elk.layered.nodePlacement.favorStraightEdges": false,
  "elk.edgeRouting": "POLYLINE",

**Comment by arrowhead-404** [comment]
I was able to solve the problem by reversing the cyclic edges before feeding the graph to ELK. It looks like the cycle breaker (probably greedy heuristic) of ELK will not work in my case, which is perfectly expected. Before feeding my graph to ELK, I broke the cycles with DFS by forcing the entry node as the Start node, and it worked all ok.

I am closing this ticket since no resolution is needed from ELK.

**My Layout Options**
"elk.algorithm": "layered",
"elk.direction": "DOWN",
"elk.padding": "[top=25,left=25,bottom=25,right=25]",
"elk.spacing.componentComponent": 25, // unconnected nodes are individual subgraphs, referred to as named components
"elk.layered.spacing.nodeNodeBetweenLayers": 25, // this has effect, but only if there are edges.
"elk.edgeLabels.inline": true,
"org.eclipse.elk.layered.nodePlacement.favorStraightEdges": false,
"elk.edgeRouting": "POLYLINE",

**Comment by soerendomroes** [comment]
At least ELk layered should have strategies to reverse the edges either explicitly or implicitly by setting `cycleBreaking.strategy`. E.g. `MODEL_ORDER` would force the edges in the direction according to the order of nodes.

**Comment by soerendomroes** [comment]
Have you tried using the DEPTH_FIRST cycle breaking?

**Comment by arrowhead-404** [comment]
This is what I get from DEPTH_FIRST
<img width="452" alt="image" src="https://github.com/kieler/elkjs/assets/3316054/f4613b32-c946-4923-8a05-f3b6c8dff311">

This is likely due to the fact that DFS is entering my graph via a node which is not the Start node.
My ELK Options:
"elk.algorithm": "mrtree",
  "elk.direction": "DOWN",
  "elk.padding": "[top=25,left=25,bottom=25,right=25]",
  "elk.spacing.componentComponent": 25, // unconnected nodes are individual subgraphs, referred to as named components
  "elk.layered.spacing.nodeNodeBetweenLayers": 25, // this has effect, but only if there are edges.
  "elk.edgeLabels.inline": true,
  "org.eclipse.elk.layered.nodePlacement.favorStraightEdges": false,
  "elk.edgeRouting": "POLYLINE",
  "org.eclipse.elk.layered.cycleBreaking.strategy":"DEPTH_FIRST"

**Comment by arrowhead-404** [comment]
DEPTH_FIST is giving me somewhat acceptable layout. However, with my DFS pre-break step, I am getting a more uniform shape.
<img width="441" alt="image" src="https://github.com/kieler/elkjs/assets/3316054/1478b93f-734d-4c2a-ac9c-80b0e0783c01">

Here is the layout that I get with my pre-break step:
<img width="381" alt="image" src="https://github.com/kieler/elkjs/assets/3316054/e4881dfa-c38d-4749-9a16-83041b81c496">

My options:
"elk.algorithm": "mrtree",
  "elk.direction": "DOWN",
  "elk.padding": "[top=25,left=25,bottom=25,right=25]",
  "elk.spacing.componentComponent": 25, // unconnected nodes are individual subgraphs, referred to as named components
  "elk.layered.spacing.nodeNodeBetweenLayers": 25, // this has effect, but only if there are edges.
  "elk.edgeLabels.inline": true,
  "org.eclipse.elk.layered.nodePlacement.favorStraightEdges": false,
  "elk.edgeRouting": "POLYLINE",
  "org.eclipse.elk.layered.cycleBreaking.strategy":"DEPTH_FIRST"

**Comment by soerendomroes** [comment]
Oh, my bad, the "org.eclipse.elk.layered.cycleBreaking.strategy" does only work with the layered algorithm and not with mrtree.
