### ISSUE TITLE
elk.hierarchyHandling INCLUDE_CHILDREN and elk.direction

### ISSUE THREAD

**Issue by tylerlong** [kieler/elkjs#26]
According to https://github.com/OpenKieler/elkjs/issues/4, if I want to create edges between hierarchical nodes, I need to set `elk.hierarchyHandling` to `INCLUDE_CHILDREN`

```json
  {
    "id": "org.eclipse.elk.hierarchyHandling",
    "name": "Hierarchy Handling",
    "description": "If this option is set to SEPARATE_CHILDREN, each hierarchy level of the graph is processed independently, possibly by different layout algorithms, beginning with the lowest level. If it is set to INCLUDE_CHILDREN, the algorithm is responsible to process all hierarchy levels that are contained in the associated parent node. If the root node is set to inherit (or not set at all), the default behavior is SEPARATE_CHILDREN.",
    "group": "",
    "type": "ENUM",
    "targets": [
      "PARENTS",
      "NODES"
    ]
  },
```

Problem is: I can no longer set `elk.direction` for children nodes, it always use parent settings.

So question is: is it possible for the parent nodes and children nodes to have different `elk.direction`, and also to have edges between hierarchical nodes?

**Comment by uruuru** [comment]
Due to the way we handle the hierarchical edges, it is not possible at the moment. I'm not sure if @le-cds has anything on the agenda to make it work. I don't think so though.

**Comment by uruuru** [comment]
I'll close this issue. It's not something we plan to work on in the near future.

**Comment by Vesper0704** [comment]
In 0.8.2, setting `'elk.hierarchyHandling': 'SEPARATE_CHILDREN'` for child node helps to give a different direction, but the hierarchical edges are not allowed anymore. Will this be supported in the future? since using hierarchical ports are not so convenient in some scenarios, especially there are lots of nodes and levels. Thanks!

**Comment by soerendomroes** [comment]
@Vesper0704 I once worked on a new hierarchy handling mode that creates the necessary dummy ports and edges for you, however, that proved to be not straightforward.
The progress on this matter is tracked in [this](https://github.com/eclipse/elk/issues/891) ELK issue.

**Comment by Vesper0704** [comment]
> @Vesper0704 I once worked on a new hierarchy handling mode that creates the necessary dummy ports and edges for you, however, that proved to be not straightforward. The progress on this matter is tracked in [this](https://github.com/eclipse/elk/issues/891) ELK issue.

Thanks for letting me know. I'll pay continuous attention to that.
