### ISSUE TITLE
[Question] Does ELK support the use of (Extended) Backus-Naur Form (EBNF) conventions to define layout options?

### ISSUE THREAD

**Issue by EliotKhachi** [kieler/elkjs#261]
Does ELK support defining layout options using (Extended) Backus-Naur Form (EBNF) conventions? EBNF conventions are typically used to define the syntax/grammar of a programming language.

**Comment by EliotKhachi** [comment]
Not sure why this was labeled as a bug, and I don't think I can remove it. Sorry.

**Comment by soerendomroes** [comment]
Do you mean the ELK Json format or the elkt format used by ELK?

What exactly do you plan on doing?

You cannot write something like
````algorithm = layered | rectpacking ``

But you could create a grammar for all layout options using EBNF.

**Comment by EliotKhachi** [comment]
I'm reading a spec for a domain specific language that had a textual as well as a graphical grammar defined in EBNF. So I was wondering if I can feed that grammar to ELK to generate diagrams for it. Sounds like I can. Thanks!

**Comment by soerendomroes** [comment]
I think ELK is not really suitable to do this alone since it does not do visualization, colors, nor font-size estimation.

Since you reopened the ticket, you have further questions?
