### ISSUE TITLE
Support box layout along with edges

### ISSUE THREAD

**Issue by AjayZuora16** [kieler/elkjs#265]
Is it possible to implement box layout along with edges so that I can fit the view with large number of nodes?

**Comment by soerendomroes** [comment]
No, this would require a standalone edge router such as libavoid, which we were able to integrate for ELK but not elkjs. I suggest using libavoidjs[1] directly as a postprocessing after using box or rectpacking.

[1] https://www.npmjs.com/package/libavoid-js
