### ISSUE TITLE
How can we prevent edges from overcrowding on a single surface of a node in a layered layout?

### ISSUE THREAD

**Issue by AjayZuora16** [kieler/elkjs#266]
<img width="699" alt="Screenshot 2024-02-28 at 11 22 19 AM" src="https://github.com/kieler/elkjs/assets/122955782/494618ac-e358-4ddb-a4a2-fda526ff6be1">

All the incoming edges are connecting to only left surface of node which looks overcrowded and bottom/top surface of node is under-utilized.

Is there any way to overcome above problem?

I am using below layout options.

```
{
  'spacing.nodeNodeBetweenLayers': '300',
  'org.eclipse.elk.spacing.nodeNode': '300',
  'elk.algorithm': 'org.eclipse.elk.layered',
  'elk.direction': 'DOWN',
  'layered.crossingMinimization.forceNodeModelOrder': 'false',
  'org.eclipse.elk.layered.layering.strategy': 'INTERACTIVE',
  'org.eclipse.elk.edgeRouting': 'ORTHOGONAL',
  'elk.layered.unnecessaryBendpoints': 'false',
  'elk.layered.spacing.edgeNodeBetweenLayers': '50',
  'org.eclipse.elk.layered.nodePlacement.bk.fixedAlignment': 'BALANCED',
  'org.eclipse.elk.layered.cycleBreaking.strategy': 'DEPTH_FIRST',
  'org.eclipse.elk.insideSelfLoops.activate': 'true',
  'separateConnectedComponents': 'true',
  'spacing.componentComponent': '70',
  'spacing': '75',
  'org.eclipse.elk.layered.nodePlacement.strategy': 'LINEAR_SEGMENTS',
  'org.eclipse.elk.layered.wrapping.strategy': 'OFF',
  'org.eclipse.elk.layered.wrapping.correctionFactor': '100',
  'org.eclipse.elk.spacing.edgeEdge': '50',
  'org.eclipse.elk.spacing.edgeNode': '100',
  'org.eclipse.elk.layered.spacing.edgeEdgeBetweenLayers': '50',
  'elk.hierarchyHandling': 'INCLUDE_CHILDREN',
}
```

Overall diagram is looking like this
<img width="1551" alt="Screenshot 2024-02-28 at 12 03 25 PM" src="https://github.com/kieler/elkjs/assets/122955782/27b86dc3-b5c7-4ecd-b156-6511ca23ec55">

Am I missing any layout option?

**Comment by soerendomroes** [comment]
ELK does assume that the best node side for an incoming edge would be WEST. You could either manually assign different node sides and constraint the Ports to their side or adjust the node size based on the number of ports.

**Comment by soerendomroes** [comment]
Here are the options

to change the node size based on the number of ports and their spacing.

https://eclipse.dev/elk/reference/options/org-eclipse-elk-nodeSize-constraints.html
https://eclipse.dev/elk/reference/options/org-eclipse-elk-spacing-portPort.html

to change the port side manually.

https://eclipse.dev/elk/reference/options/org-eclipse-elk-portConstraints.html
https://eclipse.dev/elk/reference/options/org-eclipse-elk-port-side.html

This there something else you do not like or what in this graph? You set a lot of options that will not always take effect.

**Comment by AjayZuora16** [comment]
> ELK does assume that the best node side for an incoming edge would be WEST. You could either manually assign different node sides and constraint the Ports to their side or adjust the node size based on the number of ports.

Ahh I am using reaflow which is integrated with elkjs. I would like to change the node side of above node for receiving incoming edges to be `NORTH` but the diagram remains unchanged.
 
Did I provide correct layout options to the node in below screenshot?
<img width="612" alt="Screenshot 2024-02-28 at 2 16 36 PM" src="https://github.com/kieler/elkjs/assets/122955782/663a97a5-5c71-40d1-9591-dcf2e41dd508">

**Comment by soerendomroes** [comment]
[This](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAM4AOwAxjAHZgB0Z0cACs+gIwAMXaA9HzQBlCtTpoAZtDRMocEmgg00iHDOD4acSRDSgQaSghggCmohZoQCamhyJWbaGgCY0AbyJpvz6ziEwAF449JRKJHBQwLTy6ABELADyAEoAKkIANGgAcokAIgCiAPoAMgCCAEIFJUJxXj6OOCXAAEY4ICSMmJQ4SDha8QCS2UKDhWgAEkUAwgXZqQXJaABqM3MLyXU+aORUtAy0BDAAbjAEAK6g8bKs7GjccfyCicd4sE43O6L7aC1Y6po4PVvJg2gY4tk-GgXHUAL5EQhgWwcNAAWgAfM4XAiCEjnCiMVicXi7GjMa5iciyUTEVTCRTafjqQzcXTydjGaT6RzWUzuZS+eygA) is how you change it to have bigger spacing and change the node size accordingly.

[This](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQHYQE5qkCMZFVpATGgN5FqdoAO0cAwhFIBnOFGAxScYegBiASQAaAUQAiAfQDK81co5dylTTABeOAHQBjIaPGTp6AEQA5APK71AGQCCAIWWemo76nIY4nsAARjggwubcmJY4SDhSTvLO2rpoABLq-MrOACrKAEpoAGr5hSWlwVwYUTFoLgxoTMEhPHzUfAgACnw0bF0NAHq8UHDmwjCU6G6lRTldAL5dk3C9UwN8LOwN45szczgLrksrDesNm9uIg1MAzCOHXBN8J-Noi8trGz1yDtHnAACyvN5oD5TL5nH4XP7XIjrQhgRjDAC0AD5qExzECHkM0ERUei0Njcfi+iCmCSCGjqJiccwqcC+E86QzaOTmXiCbspqDOWSKcxhYyebjxdzRbTSRLZdKmVL5TLeUA) is how you assign specific ports to a different side.

**Comment by AjayZuora16** [comment]
Ahh this is working, thanks
