### ISSUE TITLE
Incorrect Port Side Switching in ELKJS with ReactFlow

### ISSUE THREAD

**Issue by MuttakinHasib** [kieler/elkjs#273]
Hi :wave: 

I'm encountering an issue with port side switching while using ELKJS with ReactFlow for auto-layouting. Specifically, I have a condition node with two ports: "Yes" and "No". The expected behavior is for the "Yes" port to stay on the left side and the "No" port on the right side. However, the ports are switching sides unexpectedly. The child nodes connected to the "Yes" port are being placed on the right side, while those connected to the "No" port are being placed on the left side.

I've provided my current ELKJS setup and a live demo link for reference.

Help is needed to rectify this issue and ensure that the ports maintain their correct sides as intended.

Live Link: https://client-journey.vercel.app/

```ts
import { useCallback, useEffect } from "react";
import ELK from "elkjs/lib/elk.bundled.js";
import { Edge, Node, useNodesInitialized, useReactFlow } from "reactflow";

// elk layouting options can be found here:
// https://www.eclipse.org/elk/reference/algorithms/org-eclipse-elk-layered.html
const layoutOptions = {
  "elk.algorithm": "layered",
  "elk.direction": "DOWN",
  nodeLayering: "INTERACTIVE",
  "elk.edgeRouting": "ORTHOGONAL",
  "elk.layered.unnecessaryBendpoints": "true",
  "elk.layered.spacing.edgeNodeBetweenLayers": "10",
  "elk.layered.nodePlacement.bk.fixedAlignment": "BALANCED",
  "elk.layered.cycleBreaking.strategy": "DEPTH_FIRST",
  "elk.insideSelfLoops.activate": "true",
  separateConnectedComponents: "false",
  "spacing.componentComponent": "50",
  spacing: "50",
  "elk.layered.spacing.nodeNodeBetweenLayers": "20",
  "elk.layered.crossingMinimization.forceNodeModelOrder": "true",
  "elk.layered.crossingMinimization.semiInteractive": "true",
};

const elk = new ELK();

// uses elkjs to give each node a layouted position
export const getLayoutedNodes = async (nodes: Node[], edges: Edge[]) => {
  const validEdges = edges.filter((edge) => {
    const sourceNode = nodes.find((node) => node.id === edge.source);
    const targetNode = nodes.find((node) => node.id === edge.target);
    return sourceNode && targetNode;
  });
  const graph = {
    id: "root",
    layoutOptions,
    children: nodes.map((n) => {
      return {
        id: n.id,
        width: 400,
        height: 104,
        // targetPosition: "bottom",
        // sourcePosition: "top",
        layoutOptions: {
          "portAlignment.default": "CENTER",
          portConstraints: "FIXED_SIDE",
        },
      };
    }),
    edges: validEdges.map((e) => ({
      id: e.id,
      sources: [e.source],
      targets: [e.target],
    })),
  };

  const layoutedGraph = await elk.layout(graph);

  const layoutedNodes = nodes.map((node) => {
    const layoutedNode = layoutedGraph.children?.find(
      (lgNode) => lgNode.id === node.id
    );
    return {
      ...node,
      position: {
        x: layoutedNode?.x ?? 0,
        y: layoutedNode?.y ?? 0,
      },
    };
  });

  return layoutedNodes;
};

```

**Current behavior (Screenshots)**

![image](https://github.com/kieler/elkjs/assets/44552983/e729cb2a-2c62-4b81-969f-88b31d856605)

![image](https://github.com/kieler/elkjs/assets/44552983/71bc645f-225f-4315-bfc9-43edf971bd97)

**Comment by soerendomroes** [comment]
I suggest to replicate the issue using elklive.

**Comment by MuttakinHasib** [comment]
@soerendomroes 
I'm Sorry, I actually don't know how can I demonstrate elklive based on my project. But I hope you will get the issue. I request you to check the demo https://client-journey.vercel.app/

try to add a condition node then add another node under false port. you will see that the new node is placed on the left side but it shouldn't. It should be placed on the right side. I don't know how can I achieve this, please help me.

I have attached my ELK setup https://github.com/kieler/elkjs/issues/273#issue-2211161869

**Current Behaviour**

![image](https://github.com/kieler/elkjs/assets/44552983/45e9ecab-3dae-47c4-8278-eb3518588c90)

**Expected Behaviour**

![image](https://github.com/kieler/elkjs/assets/44552983/5eaac46d-b652-4f3c-917d-967d7b290eb1)

**Comment by soerendomroes** [comment]
Hi, I wanted you to recreate your graph since I want to know the order of nodes and edges in our model as well as additional layout properties.

elk.layered.crossingMinimization.forceNodeModelOrder may be responsible for this but without a model recreated in elklive, I can only guess.

https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html

**Comment by MuttakinHasib** [comment]
:open_mouth: Man your guess is right. Thank you so much :heart:

**Comment by MuttakinHasib** [comment]
Hey  @soerendomroes 

I have tried to create two elklive.

[Example One URL](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAgKZ4DWAdAXgDmKJJHQALALYJ4CQkQ5IO0bLnZc+0SEoDGtBjMQARCgHUAcqraINvZYI4AlMrXqDDCAMoAFADIBJcwBRTys2Th5eeUVlXlJ6eg4dDkZGAiQiACEOemgqFEh6dEYPdCRSDjD1SOilaF5GKgIdQsE7aAdzFGgObPQAdw4c32JFEtkARgAGKpsa0breem6Ob0JkyRz0XgAjPgAzSAAPZQBBPEhBek2ij0zT31PzAGEgo1mIvlrYnSIdPF6SgI3FaDTKBHQHEERA8RiC3gAKgAJAD6ADF-I5PAiPrZCowYBxPFx9r40FRGPw9JAAG4QyqyMoVWaMDhNJD054MRJ6ZRcyT5RJFZiIfYCVkfRrNUE6FAChhbfmCrYeACsMxw1ilLTcsnVuPmCkW2tByx6XR6fUGwwW40QACYNWo5l8Fj9UKlWgBZQqQSSQABeELo9F4+xEyQtHC9KzwFCQPSQpXKlU14Vs33qOg9BLcPvofsDwYYDQ4-v8RUUzVoNIZiCZqednyibvqmyQDiCHRSyeZaYAvmmdOJIHhoEp6PAANrO1jWKBwRD0CazCD9GASeDTKZp6ziDiXcToeAAZh3zvYhB2XDtM-nbGA9Y4R0wskY6HSmDA-YvYAAurubDyC41D6EwLC-uw+RIOg5yXNcWy8D0YqkHgr6IK85gIkEjiruE0HoFyTDgoUxQeBiAAabwop4-hwnhg6-gRIp3veYBzmxC7wAA5O+n4oowZBIMk3GAfe67QJuYCqmJ877oex7SbJ1hUKgVCKLQKQsIgBENISHieBQACqyIIN+kHfrJf7Oox1gcWwMCyPQ9p4RJUnbrJ8mCEep7nvecgENeeC3hZj4IJCL4eERWhgWZP73gBv7AeQoEhiK9nWAgBFwVcNzbMhBCoehCCYdhuHKTpIiEQw74cqRdoIJR1G0fRsm2fOzHTqFFkQI5YDcbKuRiCGKIfh2HDoKJPVgG54jwDJ01eT5SnTapKDqTBkBaexlUwXpPQeOYFCOKZ5mce194ZfOfUDQwMUjQojACUJIkVWuG5zStnEQEtikLd9+CBTeXUAxAj4RYpCAAJo9md32JQDa0bZp6W7dsBIHbIhkmUicUWRd85XdYN2DfdDAossz2kMJHBTQDs3zW9YC-Yz01XsDYCsQD4PPpDXR4wDCPfUjGlbajWVVftdZeMZp3xWx8vWNZ1gE1dfUIPQJ6uR9W5TH5ckHt5ilnrJAVBSFnFhRDHgw4wYBRgL85C9YyWUDQaUQZxEswTlCFFEhHAoWhUVBFhOF4VBVVEbVBD1eR-hUUYNF0UEDGyZ1nPdQDN2PRTVM03T30M1930syXnEi5t21hbpGPS9jcv4xVRMOYu3G5-Qo3pA4k1M8X-2l4by0DxXami9XaNS4dx2N+dVk2YBauLhrAAs2uSZ9Hm-mXJu-mbN6GFzhNPpFshdPbKyO0rsmu6lNWe2x3uwRcuWIQVRUh2H5UWU-0ckcK8dE7J1ar+AmEAM5HzstNG6lNO6CWpq9aa-cmZlxHmxSuKNtJPynljWWuM4b3jAQ+aBbdYFd3Gr3JBOty5sVQUzDBYssG130mfGe+DFbziIcrNgqtfzq3oKqde7k9aeSHsbfWmV2bBUPqFE+xVQ7vAIWwZ2QFiAgXdvfdiP9sovz9vlQOhVg6yFKuHCqv8ar-zIrIJqScWqpzaunKqLEs7fRujkaA5Ce6F04sgxaYjWaIzHlXcWzDMaICOiddhTdfzcIgPLIW9htpH0fOrDgK4sBgHgTTFiiA+IwXzskMyAEwBjR7jkhApNhrk1KRNIpllZxcRsC5DJWTkjlMqWBFEudWmVH-BkmpxRpyIA7p42p-56l2UaZwLWLSXpJOGSkPOPSin9O7hNcp7jRlfj-BMh8UyOBr1mQg+ZFS7pVM7pTZZfSSlrMGZzJcKA84DLqarfZgijnZKGRrR5cC5krJuRQjZuQtkvLTNZfsQA)

Here always the **Yes Node and Yes Port** will place on the left side and the **No Node and No Port** will place on the right side.

![image](https://github.com/kieler/elkjs/assets/44552983/59b998e0-e175-4775-ba58-ebed61e26987)

[Example Two URL](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAgKZ4DWAdAXgDmKJJHQALALYJ4CQkQ5IO0bLnZc+0SEoDGtBjMQARCgHUAcqraINvZYI4AlMrXqDDCAMoAFADIBJcwBRTys2Th5eeUVlXkYqAh1INztoB3MUaA4AIQ50AHcODnpfYkVGDwBGAAYw9UjopWheekyOb0IdDkli9F4AIz4AM0gAD2UAQTxIQXoe+kxZbInfCfMAYSCjOpsGsqbeHSIdPBylAm5kwTj0JAJ0DkEiDyMg7wAVAAkAfQAxf0cnneOwifGSjBgHE8XCGvjQVEY-D0kAAbvcOB5bqQMThrIwOAk7g91gx6Bw9MoSZIqAxesxEEMBPiQfFEldDihqbSFlSaWSFh4AKy1XFsVlJNyyYUg2yNWLi9mtLIZLK5ApFEr7CqyABMIrUuz4cuaOlQjAhbgAsslIJJIAAve50ei8IYiLoqjiWtp4ChILJITFIbEyvYKA6mlDmq7W+i2h1OhhxbqQfwLRSJWgojGyLE4g2gqL7WI9JAOIJpDjaxB5sIAX1FOnEkDw0CU9HgAG0DaxrFA4Ih6JUdhB8jAJPAatVRdZxBwZuJ0PAAMzTg3sQj9LjV7t9tjAGscUaLRCMdAEJCYMB19dgAC6M7Y8hc1H0TBYt-YNMvUxmc16vBZIypB4CeCCbOY7xBI4I7hN+6AkkwtwEMk6DVgg-wABpbN8nj+K8sENre8H0rue5gL25H9vAADkZ4Xug3yMGQSBdDRj57mO0ATmAgocX2c4LkuvH8dYVCoFQii0FWLCIPBcSQh4ngUAAql8CDXp+178XeBpEdYlFsDAsj0DqsFcTxU78YJgiLiua57nIBBbngO5aQeCAPMeHiIVob4aTee4Prez7kK+zr0oZ1gIPBv6zPMfRAQQIFgRBUEwaJckiAhDBnncqHoVhOF4QR-H6X2JFdu5WkQMZYA0ToDB+c63znmWeTsTVYAWeI8B8V1Nl2SJXXiSgkmXpAMkUVll4KVkHjmBQjjqZpVHlXuUV9nVDVNWILUKIwTEsWxmWjuOvXDVRECDcJ-VXfgznbrAnbAF5wkIAAmlWCB1sF92jeN0mRTNfQQvNsjKWpnwBVp619pt1jbY19DNQw3ytEdpCsRwnX3T1fWnWAN0E11m5PS9b2yBkP1-VdANSZNwMxdlc05ogkMrYF5Fc9YunWHDm11Qg9AACzmedk7VA5AnzrZwmrvxTkuW5VEeW9C0oGAnow0F-GhZQNARR+VHMz+0zxQBSUpT5QSQdBsFftliF5ShCyFf42FGLh+FBIR-GVWAZEbV120Y-QmPY7jV345dV3E7HVH0xNU0efJYNs14qmc7DmUI0ZA40WHrUXg46BR1RMd3XHstDVXicSQzKcg6zC1Ldna06Xpj6CwOwuCuL3EXVZt7xwrt5K9uhhB-Dh7ebItvbKtfa09Y+vhblxvkab6Bxf+CyARwwGgTbdsZVp2-O8hBUeEVXslb7ZX+9lpHVfd23FNAxftWXhOV4T8d13IknIGslt4typm3aGS89xwwgHzNgXNab2CmtPA8QsODDiwGAZiWMuikVPG1RiODsYaQfGANqpd8EIGRqjcOFC8ikO0j2aiNgzJYOIXgrsiAaF7TRgdCOXRSFYPoWhLhnAUZf1LowgWLDODLmwNg46KDuG7TfOjFAAiMT3mESXPIVCi4iOkd3WRHB+7sKUfojR4cOFaLISIqhH9JEMPvEvXSdYgA)

Here the **No_Node** and the **No_Port** will always place on the right side though I don't have any nodes under the **condition node** of **yes port**

![image](https://github.com/kieler/elkjs/assets/44552983/2510c503-6e9f-45c5-88fe-20e5f28cfc68)

Here is my current ELKjs Setup with ReactFlow

https://gist.github.com/MuttakinHasib/abf85903a66c655c449c90042725dad2

**Comment by MuttakinHasib** [comment]
@soerendomroes Whenever I add a new edge or delete an edge while creating a node then the nodes are switching the sides

**Comment by soerendomroes** [comment]
If Yes and No ports should always be in that order, I suggest to set `portConstraints: FIXED_ORDER` on them.
The issue in your first model persists since elklive changes its version back to 0.7.1 which does not support all option you are using.

**Comment by soerendomroes** [comment]
If you constrain the port order, you only need to maintain the port order.

If you want to also constrain the node order via `forceNodeModelOrder` you need to set `considerModelOrder.strategy`.

**Comment by MuttakinHasib** [comment]
@soerendomroes Which one do you prefer? in this case? I just want the layout not to switch the side

**Comment by soerendomroes** [comment]
If you want the port to be in a specific order, I would constrain the ports and not use the model order strategies. If your nodes and edges are ordered based on the time you create them, it does not make sense to use model order.

**Comment by MuttakinHasib** [comment]
@soerendomroes Will you please provide an elklive example to fix this issue? [Demo Elk live](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAgKZ4DWAdAXgDmKJJHQALALYJ4CQkQ5IO0bLnZc+0SEoDGtBjMQARCgHUAcqraINvZYI4AlMrXqDDCAMoAFADIBJcwBRTys2Th5eeUVlXlJ6eg4dDkZGAiQiACEOemgqFEh6dEYPdCRSDjD1SOilaF5GKgIdQsE7aAdzFGgObPQAdw4c32JFEtkARgAGKpsa0breem6Ob0JkyRz0XgAjPgAzSAAPZQBBPEhBek2ij0zT31PzAGEgo1mIvlrYnSIdPF6SgI3FaDTKBHQHEERA8RiC3gAKgAJAD6ADF-I5PAiPrZCowYBxPFx9r40FRGPw9JAAG4QyqyMoVWaMDhNJD054MRJ6ZRcyT5RJFZiIfYCVkfRrNUE6FAChhbfmCrYeACsMxw1ilLTcsnVuPmCkW2tByx6XR6fUGwwW40QACYNWo5l8Fj9UKlWgBZQqQSSQABeELo9F4+xEyQtHC9KzwFCQPSQpXKlU14Vs33qOg9BLcPvofsDwYYDQ4-v8RUUzVoNIZiCZqednyibvqmyQDiCHRSyeZaYAvmmdOJIHhoEp6PAANrO1jWKBwRD0CazCD9GASeDTKZp6ziDiXcToeAAZh3zvYhB2XDtM-nbGA9Y4R0wskY6HSmDA-YvYAAurubDyC41D6EwLC-uw+RIOg5yXNcWy8D0YqkHgr6IK85gIkEjiruE0HoFyTDgoUxQeBiAAabwop4-hwnhg6-gRIp3veYBzmxC7wAA5O+n4oowZBIMk3GAfe67QJuYCqmJ877oex7SbJ1hUKgVCKLQKQsIgBENISHieBQACqyIIN+kHfrJf7Oox1gcWwMCyPQ9p4RJUnbrJ8mCEep7nvecgENeeC3hZj4IJCL4eERWhgWZP73gBv7AeQoEhiK9nWAgBFwVcNzbMhBCoehCCYdhuHKTpIiEQw74cqRdoIJR1G0fRsm2fOzHTqFFkQI5YDcbKuRiCGKIfh2HDoKJPVgG54jwDJ01eT5SnTapKDqTBkBaexlUwXpPQeOYFCOKZ5mce194ZfOfUDQwMUjQojACUJIkVWuG5zStnEQEtikLd9+CBTeXUAxAj4RYpCAAJo9md32JQDa0bZp6W7dsBIHbIhkmUicUWRd85XdYN2DfdDAossz2kMJHBTQDs3zW9YC-Yz01XsDYCsQD4PPpDXR4wDCPfUjGlbajWVVftdZeMZp3xWx8vWNZ1gE1dfUIPQJ6uR9W5TH5ckHt5ilnrJAVBSFnFhRDHgw4wYBRgL85C9YyWUDQaUQZxEswTlCFFEhHAoWhUVBFhOF4VBVVEbVBD1eR-hUUYNF0UEDGyZ1nPdQDN2PRTVM03T30M1930syXnEi5t21hbpGPS9jcv4xVRMOYu3G5-Qo3pA4k1M8X-2l4by0DxXami9XaNS4dx2N+dVk2YBauLhrAAs2uSZ9Hm-mXJu-mbN6GFzhNPpFshdPbKyO0rsmu6lNWe2x3uwRcuWIQVRUh2H5UWU-0ckcK8dE7J1ar+AmEAM5HzstNG6lNO6CWpq9aa-cmZlxHmxSuKNtJPynljWWuM4b3jAQ+aBbdYFd3Gr3JBOty5sVQUzDBYssG130mfGe+DFbziIcrNgqtfzq3oKqde7k9aeSHsbfWmV2bBUPqFE+xVQ7vAIWwZ2QFiAgXdvfdiP9sovz9vlQOhVg6yFKuHCqv8ar-zIrIJqScWqpzaunKqLEs7fRujkaA5Ce6F04sgxaYjWaIzHlXcWzDMaICOiddhTdfzcIgPLIW9htpH0fOrDgK4sBgHgTTFiiA+IwXzskMyAEwBjR7jkhApNhrk1KRNIpllZxcRsC5DJWTkjlMqWBFEudWmVH-BkmpxRpyIA7p42p-56l2UaZwLWLSXpJOGSkPOPSin9O7hNcp7jRlfj-BMh8UyOBr1mQg+ZFS7pVM7pTZZfSSlrMGZzJcKA84DLqarfZgijnZKGRrR5cC5krJuRQjZuQtkvLTNZfsQA)

**Comment by soerendomroes** [comment]
Here is the [port](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAgKZ4DWAdAXgDmKJJHQALALYJ4CQkQ5IO0bLnZc+0SEoDGtBjMQARCgHUAcqraINvZYI4AlMrXqDDCAMoAFADIBJcwBRTys2Th5eeUVlXkYqAh1INztoB3MUaA4AIQ50AHcODnpfYkVGDwBGAAYw9UjopWheekyOb0IdDkli9F4AIz4AM0gAD2UAQTxIQXoe+kxZbInfCfMAYSCjOpsGsqbeHSIdPBylAm5kwTj0JAJ0DkEiDyMg7wAVAAkAfQAxf0cnneO0YHASdwe6wY9A4emUUMkVAYvWYiCGAlBOwQ8USV0OKERyIWCKRMIWHgArLUcNYInxGrEcUkUq0shksrkCkUSvsKrIAEzU3AAXxpYB04kgeGgSno8AA2mowKxrFA4Ih6JUdhB8jAJPAatUxdZxBwZuJ0PAAMxGpXsQj9Lh8sCK1VsYCIB6jRaIRjoAhITBgYV2sAAXWNbHkLmo+iYLFD7CRgamMzmvV4WXRpDwPoQm3M7yCjm14WT6ChTFuBGS6GdCH+AA0tt9PP5XqXRaHy6jXW7lYm2DB4AByP0B9DfRhkJBdEeRt266D6sAUheq03my2r9fWKioKiKWgcVEehDluIwDgeTwUACqXwQwcHXbdYaVr-doeHGv5paXK6Guum6CBa1q2m6cgEI6eDOn2bpnl6eaVlocZPiGb7rtG5CxnQ8YDv2iDlqmszzH0WYEDmyFBIWxalkmIgVgwfp3LW9ZNi2FCOK8JZYGAAD0-FgP44riAQbjKGAEiQIwYD7igh6BkQUkoGAHFGN8XE8aGn57oxvaDiqhE-iOOgMKheHfP6SAOOg86DjqeriPAa4OWAIFgTubnyYpx6nkRjGXlkHjmFxj7PoRumqkZ-YmWZ9AWQw3wKIwU4znOu5sABzleYREAedurl5fg0FOgqbkQB6SGyAAmie6FuRG3kHkekAniwAWBkF16yLeD6fA1kWZTFbpxeZYiWa0aWkLOHD2cV2UuZl+VmqBhXLSVMEGcVlVSRw3qyBkg15U1xU+a17XKp1fSMFeN73uFGH9k91jvtYUUjWqsj0Fa-5OQa1QQRuq2eTa65QVthjwdFnr7XmdWyey14Raqp2qthlA0Hhp6DuejEkemCyZhw2a5h4BZFrxuPlpWLE1gs7H+M2Glth265RRAPblYRn3WCZKXfPQ02zfNeWLbleUFUtzUKRd-l411t3Bb1D0DSjboc1+xX8yegtWQGtmi4R4tFZLIPrTLvltfLF5Kz1iChY4j0vuub1sB937qgg9AACx-cuOVAaGUtgGDoYQ06UOGbD3ohapSPHa9WHEDGWPMQmhEK+gBNkcTpPUbRVOZzTzHVmxHjqa27ZBJ265cy6hluSZU1C9OM0ZW5JsbSHpuEedgbWx1Wfdfd-WJ6qmuVU36oji3+s2XkRv9l3bk9xt-d+UPtt3YdYVqy9E+ux+kafT+3sUv7gGA8B5vgeDDqR9z-aIXDHg0ds6tsGj1gY7h6cEf2LOOcMwUSouTGilN6LXVpmXBmFcmYtlZjXdmdd9JPwQtPUcxRoDz0NhtFexU16WzllvQKdsQp73Hu9I+71cBo3sJdaGHoz4cC1HxNus1ey+mspODhXQnwRikgbPIXCEDxUSkLaytkBHBhPl9Gwf52HpUYYgcRE0koCz4cjQRUiREKkQALSRwigxhlkUqZhXsOC-SUe3FRCBDHC34eGPiui6z6M4AlXBeQZEfXkZwP2NjOHuLUXGQWKBHHaJccY0Rc9XE+LkSwi+gSugxPCa3ZRAiokLzcS6Gwni4nhjMRAd8wogA) constraints option.
And [here](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAgKZ4DWAdAXgDmKJJHQALALYJ4CQkQ5IO0bLnZc+0SEoDGtBjMQARCgHUAcqraINvZYI4AlMrXqDDCAMoAFADIBJcwBRTys2Th5eeUVlXkYqAh1INztoB3MUaA4AIQ50AHcODnpfYkVGDwBGAAYw9UjopWheekyOb0IdDkli9F4AIz4AM0gAD2UAQTxIQXoe+kxZbInfCfMAYSCjOpsGsqbeHSIdPBylAm5kwTj0JAJ0DkEiDyMg7wAVAAkAfQAxf0cnneOwifEasXiiSuLTaGSyuQKRRK+wqsgATLUcNZQVF9rEdKhGIwrgBZZKQSSQABe9zo9F4QxEXThHBJbTwFCQWSQHlupA42DAAHohWB-EMwABNDiMFlgAj0aBgDJyghKMAibnKMA6ES6dB4IhYMASSCMDU0OnyxUm8QcDX0e39LgofJgfKQPB4MDFRlILq2+26pBKDh6DVcxS8NS7MF45oElBE0nkyk0-T03VMGCKNlZDmRpA3O4PJ4ecwUV6eb5rIzfLYAcRCCFwAF8sTrxJ7oEp6PAANox1jWKBwRD0So7CAe6ASeA1aod6x2mbidDwADMi5j7EIzrwqLAg5HbGAiAeo0WiEY6DVmDArZ3YAAuku2PIXNQM8wwMOTwgqBEdAphmOZel4LIhgIUg8CvBBNnMd4gkcKdwkApB0HWBgbzuZJ0EPBB-gADS2b5PH8V5UPbJ90PwgcnwgP8T1HeAAHIbzvb5GDIf0OFYt8TxnOcwAAVgEkcV0ENd4DEhi2CoVAqEUWgZRYRBaLiHMPE8CgAFUvgQB85Ook9nxjEzTyfGBZHoNFUKE8R52qbcT0k6SwC3cS5AIfdD2PZizwQC84KwxUxDpQzH1M8SP3IL86R-JjsVokDZnmPpIOg2CPAQpCUPE9haNCnCCDwgjiNI8jKPEizrFon9-JPJKR2ssBWKzLQM2+W8kAcdB+Lk6cYGE2TmLYNz11Egr5MU5TIFU391KAzSsnLChHAMoyxtqkdmusVr2oYTq6W+BRGC4niugGsahtnRypsGsAJpk6aID3LgGsexiTQ4S9ZGlCotpu19HoUlAlIw+bEqWjCVoFWQdP0z5IuM6a9rYA6OvChhvlaC7SF466bocl7Hueh6bvwHyPvoynvuC2QMhRymQcpsGIZU6GAOW4lVoRvTNqi5ihesMzrB25rWoQegN3s4b7oXcTyc8p9vN8wxGt289frggHlTaZmR1ZkdYsoS1sJYOTuYw1KwIWCCOCgmCQqCRDkNQwqgOK25SoWcr-BIusqqCKjxPq2mAseg6ztx-HCde915dJynydGm72bmhbAo03n4cQRHBdRuT0YgaOZVjnq+qJsaSYpm7U4TjPIazmG+lztaNuRoGTx2iAxbYCWrLHaWABY5bupyXIkjhV0mlX-3eg8NeL7XL3LFB9dW7u2GN6xTfii3fytlLpjS8DMudnLXbyj3W+93C-Y8Cqg4okOarDoDPrGkuWLavH6DjldBOtc05jQbqDWazcuY5y0vzJGhse5oyjmOVi-9upqirsApOdcwEzykpNUBzEm6czUtbNusDEAVk7ggkcvcXzmTfJLYe9ARLj2EorJ8ysp7YkXn5FeQUdYeFdtsbefcYrEE-ObJglsxpkNtulB2TtsqyFyu7aaZD76+3wk-AOlVX6hxop-COTVkFsWKNAdBvU8jV2YiAhO4C2aQJIYtMhcMO6F22uJfuEAhbG3sAtTWZ4pYcEnMabiBMugNWvD1dAgCBQvmNJXPIUSEBYy6kk+8z4HyMN-pwOyYTLoBMQGkk6Mdwm8UMq+E0GDkkDkQDHABGTKnZKHLkjgssCkRKKQgBpcTKmJJqXRI8NhFSWL6s0iWbSx6dN4ikkpOM8blK6P06pVihn9nHCgCugyJk5OCawmZkS6nSy2QApZ8SqkZJSeYsZeRdm4DMq2IAA) is the model order option that enforces node model order (remember to switch to 0.8.2).

**Comment by MuttakinHasib** [comment]
Thanks @soerendomroes your help :heart:
I have implemented this [Example](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAgKZ4DWAdAXgDmKJJHQALALYJ4CQkQ5IO0bLnZc+0SEoDGtBjMQARCgHUAcqraINvZYI4AlMrXqDDCAMoAFADIBJcwBRTys2Th5eeUVlXnoUaA5vQh0OSQ56dF4AIz4AM0gAD2UAQTxIQXp0zI8AIRLfEvMAYSCjMIBfHAgdcUg8aCV6eABtNTBWayg4RHoARjDrAHcYCXg5gAYN7qnxDgrxdHgAZm3x9kJsrkZDMam2YER0DkLMWUZ0AiRMMA7zsAAujtrPIXNR9EwWP92FQROgyhUqhksok8gRSHg3ohWuYACpBRyLKYIWHfZoMD5IAiQTI3WQAMX8AA02gB9CiOIwEokQLr-UnoZhgO73CbQtgweAAcg+X3QrMYZCQqSlwNFK2gazAAFY1fc9gcjjq9VMqKgqIpaBwhY8SXDeIwYBwPJ4KABVXEACQQv3FfPuAPG-oe-0lswATDywBqtZszvr9oJDid48TLtdbuLbc9Xh5yfQtBCfX8AybQeRwXRIWLRYgBQjKtUURw0RisQgcfjCSaYXD85TqbSPIyWUZ2ZzuSbg9YBUKRfdJrWw1KdAxC1XWZ8kA50KrxRAY+J4Lr92ADUmjSfaxAzSgLd9INaWHX7Y7Eh5zByvcW-T2a9fl1XAsxA3BRGAVJUVT-A9ViPY1T3PZN4OvfACCuPA51PCBHhzI0EAATWtH8UKBU9b3vK0bRfb4HSdF13W-X1a2nKZF1FQC1xAhhWXiCDSGVDg9xQw9j2gs9EyQq9r3TDDRiwiYwFw2RzBQYjr1IlDyMtR8qLtGi32dWRXQ9b0mNFEspkDawWLYiAwwQehjijESwDjE1EKNU4TTkNCMzk2tsxedtCMYMAVPfMzrA0qZy0oGgqxtcU9PhcpG2RXhUXRTE8yCPFJySgV+3QKkaUFYdmTZDkuW7f4WJvOFMIC09lzAni+IEoTrxcqTaw80SyPNbSnwU5LaPfIyGNMiz7jqkMUJa602q3HdOtrbqxL65Dry0h9httAUxsMxBP0cRjpqmWarLYGzQxmByABZnNg9YtnciTPNTawfPQulhSzJ4go-FAwoSZ1IrYaKQWIMF4opKFa2ShskUyDKWyy9tO3yhHCopYrBzKhkKrHKqsYuk1Z380VbKmZdePodqoNPdaEPe-rNMG3bdIOgz6JMtSZr-anrFplAlq+FaxOZlDNp60Udso59Rp55Svym39-iu3k1Wp+z6G1J7NTgtz-k2rz-m+vy-oCgHc1kXL2nBiBIbYWLKzh-97kR1LkebVtstkTGauxvtcZKodCdHcdqqjWaKatqnmpmKUMmgTdxY4XdJeerbetZnO5Y5hWRu5uiVdOtXmJNTWzOi+xhvnBT7I4BYsDARV+NSOdEFlb4GbBoFFPTwVRkQID1245aM59AFfm16ZZA4SNW-bgSu4QMeuPp1qV9SafW8n4fhUQVr6YP6fZ-GR4m6c5fIPr4-Fvpnf+-3oe15TtPtynwEL+sK+7o4I9W+Hd77r04hCHiotn570Hl-Q+IxZii1PkPc+Nl542H1sA1eI8HJIL7jAg+78Cyfx3KgnYgYOhAA) and it's looks great.
