### ISSUE TITLE
Layered algorithm custom wrapping/placement

### ISSUE THREAD

**Issue by nlafleur** [kieler/elkjs#278]
I am trying to create a diagram with a structured placement.
The reason I am using the "layered" algorithm is so that I can recursively loop over the nodes children.

I am using Elkjs combined with ReactFlow.

These are my graph settings:
```
  "elk.algorithm": "layered",
  "elk.layered.spacing.nodeNodeBetweenLayers": 200
```

Horizontal graph:
Initial result:
![image](https://github.com/kieler/elkjs/assets/40174298/02818ecd-751a-4d2e-9b83-baa87f95ba61)
Expected result:
I had hoped that I could determine the placement based on some kind of depth ID, in my example 1, 2, 3, 3 (see image)
![image](https://github.com/kieler/elkjs/assets/40174298/6d655756-eaf3-412d-b73d-64281cde4672)

Vertical graph: (there is a switch in the UI)
Initial result:
![image](https://github.com/kieler/elkjs/assets/40174298/f33271ce-83f0-4f0f-9c2e-a361da22a985)
Expected result:
![image](https://github.com/kieler/elkjs/assets/40174298/14ff7b30-a479-4761-8a7b-c6acd36d5497)

I've tested allot of the elkjs layered configuration (https://eclipse.dev/elk/reference/algorithms/org-eclipse-elk-layered.html).
But I can't seem to control the placement.
Any idea/tips what settings I can use?

**Versions:**
```
    "elkjs": "0.9.2",
    "reactflow": "11.11.0"
```

**Some additional code to create the nodes/edges:**

My initial **nodes**:
```
[
  {
    id: "1",
    data: { label: "Call_Stack" }
  },
  {
    id: "2",
    data: { label: "Modins" },
    children: [
      {
        id: "2a",
        data: { label: "Trafo" },
        children: [
          { id: "2aa", data: { label: "ID: 76" }, type: "CustomNode" },
          { id: "2ab", data: { label: "ID: 81" }, type: "CustomNode" },
          { id: "2ac", data: { label: "ID: 811" }, type: "CustomNode" },
          { id: "2ad", data: { label: "ID: 812" }, type: "CustomNode" }
        ]
      }
    ]
  },
  {
    id: "3",
    data: { label: "Modins" },
    children: [
      {
        id: "3a",
        data: { label: "Trafo" },
        children: [
          { id: "3aa", data: { label: "TS_SET:ID: 81" } }
        ]
      }
    ]
  },
  {
    id: "4",
    data: { label: "Modins" },
    children: [
      {
        id: "4a",
        data: { label: "Trafo" },
        children: [
          { id: "4aa", data: { label: "TS_SET:ID: 82" } }
        ]
      }
    ]
  }
]
```
My initial **Edges**:
```
[
  { id: "1", source: "1", target: "2" },
  { id: "2", source: "2ab", target: "3aa" },
  { id: "3", source: "2ab", target: "4aa" }
]
```

The Elkjs graph code:
```
const graph = {
  id: "root",
  layoutOptions: {
    ...elkOptions,
    "elk.direction": direction,
    "elk.animate": animated
  },
  children: recursiveGraphNodes(nodes, animated, direction),
  edges: edges.map((edge) => ({
    ...edge,
    sources: [edge.source],
    targets: [edge.target]
  }))
}

return elk
  .layout(graph)
  .then((layout) => {
    const nds = layout.children.reduce((result, current) => {
      const depth = countDepth(current)

      result.push({
        id: current.id,
        position: { x: current.x, y: current.y },
        data: current.data ? current.data : { label: current.id },
        style: { width: current.width, height: (current.height + (30 * depth)) },
        targetPosition: direction === "RIGHT" ? "left" : "top",
        sourcePosition: direction === "RIGHT" ? "right" : "bottom"
      })

      if (current.children) {
        result.push(...recursiveLayoutNodes(current, [], animated, direction))
      }

      return result
    }, [])


    setNodes(nds)
    setEdges(layout.edges.map((e) => {
      return {
        ...e,
        animated: animated
      }
    }))

    return layout
  })
  .catch(console.error)
```

```
const recursiveGraphNodes = (nds, animated, direction) => {
  return nds.map((node) => ({
    id: node.id,
    width: 200,
    height: 100,
    layoutOptions: {
      ...elkOptions,
      "elk.direction": direction,
      "elk.animate": animated
    },
    data: node.data,
    children: node.children ? recursiveGraphNodes(node.children, animated, direction) : null
  }))
}
```

```
const recursiveLayoutNodes = (node, result, animated, direction) => {
  const depth = countDepth(node)

  const newResult = []
  node.children.forEach((child) => {
    newResult.push({
      id: child.id,
      position: { x: child.x, y: (child.y + 30) },
      data: child.data ? child.data : { label: child.id },
      style: { width: child.width, height: (child.height + (30 * (depth - 1))) },
      parentNode: node.id,
      extent: "parent",
      targetPosition: direction === "RIGHT" ? "left" : "top",
      sourcePosition: direction === "RIGHT" ? "right" : "bottom"
    })

    if (child.children) {
      newResult.push(...recursiveLayoutNodes(child, result, animated, direction))
    }
  })
  return newResult
}
```

**Comment by Eddykasp** [comment]
Hi @nlafleur, for the future, it helps us a lot if you recreate your graph in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html) and link to that. To solve your problem you have two options:
1. set hierarchyHandling to INCLUDE_CHILDREN to support layout of hierarchy-crossing edges or
2. set seperateConnectedComponents to false (because your top-level nodes are not connected) and use partitions to manually decide where each node should be placed

Both options can be seen [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBCD28AuAoMAbY8QEslQFsAuGdMATwFMRKATFCMEJPHeAOx3eADowBjFgDcwSSiSQgArpRQBnSo3BiAwh3aVBdNQQgdK7JHJIAzDApQB6SzCg5qTflHIAJMO1rouwEgEkAcioAMgCqACIAogD6Ki6+QWEAShH+KOzwtJQw7ACMMADeKDDFMEosLBzePGWsHCQ5KAC+aRlZ7ABMBUUlNRWc3NVM5WzsJO0oAJDpmdntYF0TU62zYGCTSzMdYABG69Ntc-x7y1v0E83N+9kAzF0lpUO1-by9IyTXk1fs1-OFi18-NbnJotTYAFjuPUefSqrzqMA+GzaYN+x3Bq0mFxQdGAWUoORIuRgAFoAHyzbG0XEwSjtQntHhbRlzbYk8nfRk-TkYnF46705lgQWssnZMGMlESjFAA).

Let me know if this answers your question.

**Comment by nlafleur** [comment]
@Eddykasp the "hierarchyHandling": "INCLUDE_CHILDREN" indeed did the trick! Thanks
