### ISSUE TITLE
How to preserve nodes order?

### ISSUE THREAD

**Issue by Borouch** [kieler/elkjs#284]
I have tried many options variations and none of them seem to change the graph layout to achieve desired result. I would expect the 
 nodes order by which they are defined to be preserved (starting from top left) in layout but that is not the case. I use svelteflow for rendering if relevant.

```ts
		const elkGraph = {
			id: 'root',
			layoutOptions: {
				'elk.algorithm': 'layered',
				'elk.direction': 'DOWN',
				'elk.hierarchyHandling': 'INCLUDE_CHILDREN',
				'elk.layered.layering.strategy': 'LONGEST_PATH',
				'elk.layered.crossingMinimization.strategy': 'LAYER_SWEEP',
				'elk.layered.nodePlacement.strategy': 'BRANDES_KOEPF',
				'elk.layered.considerModelOrder.strategy': 'NODES_AND_EDGES',
				'elk.spacing.nodeNode': '20',
				'elk.layered.spacing.nodeNodeBetweenLayers': '50',
				'elk.layered.crossingMinimization.forceNodeModelOrder':true

			},
			children: nodes.filter(node => !node.parentId).map(node => ({
				id: node.id,
				width: node.data.width as number,
				height: node.data.height as number,
				children: nodes.filter(child => child.parentId === node.id).map(child => ({
					id: child.id,
					width: child.data.width as number,
					height: child.data.height as number
				}))
			})),
			edges: edges.map(edge => ({
				id: edge.id,
				sources: [edge.source],
				targets: [edge.target]
			}))
		};
```

#### Current layout

![image](https://github.com/kieler/elkjs/assets/60584457/4d9d2127-3c04-48ea-8c6e-ec0112aebd80)

#### Expected layout

![image](https://github.com/kieler/elkjs/assets/60584457/ba29b741-014f-49ee-bf9d-36f867e05604)

**Comment by soerendomroes** [comment]
I need you to replicate your model in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html) to be able to see what the problem might be.

My guess currently is that `hierarchyHandling: INCLUDE_CHILDREN` might mess with other options, or that you do not constrain the flow of your graph and need to set `cycleBreaking.strategy: MODEL_ORDER`.

More details about node order and how it can be constrained may be found [here](https://eclipse.dev/elk/blog/posts/2023/23-01-09-constraining-the-model.html).
