### ISSUE TITLE
Partitioning is not working properly

### ISSUE THREAD

**Issue by MuttakinHasib** [kieler/elkjs#295]
I am trying to implement the partition on my project but it's not working at all.
I have 4 layers of nodes that will be placed horizontally.

Here is the elklive [Example]( https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGBECWAmkC4oCcD2qAukA04oFMAbAawDpZpl8BjDaVAO0SgCUBJAcQAkAVHPSAAcAhsjp1G0BgHNSw2tABuwjPmaQMyAK5rcESNQAW0QrCpMkAbTwRQEe1DjqGABgD60lwHYAjAGYADgBWfgd9Q3xoaUMsJB8XFz0wyAB3OAxDZnjEm3tIQmEAIyIAZ2ZrMPtgKFUAD1ioQRdIMABfXIgAXSSHfOEAT1QtDAB5QQkGMqRqoVFxegYpWRExaAn1Zrbc1p6wO2SnJEgGH1DkiKiY5gCcytT0zKQb3f0C4sIpsArKvZr8evUglOW0q3Q6UAKg2GYwmnxmK3mkhkpARawW6mB7QcO1y+16hygDAATGdehdog0grdkmlYBlmFSXhCiqVyuDbH8AUdBCSQWEwXdIUNRuMFnDGnM0UjlpL1kdeVj7DiHHi8gTjgAWUl5clXJCM8H3OmPMAGwUsj5sn6-DT-BpCPwtRUOAXJIXQ0WMcWzVYTJYo2Xoo6OvkQZVVQ3qhghJmQXWU6m9Wn0-WJvJvVlWdk2ur2wRa0P2V29d0i2HMeGB6UB31BqAh518zogVpAA )

**Expected behavior**
![CleanShot 2024-08-03 at 12  49 20@2x](https://github.com/user-attachments/assets/14639c4c-b901-4496-a82c-6d7f76c1d0ab)

Help me @Eddykasp @soerendomroes 
Thanks

**Comment by soerendomroes** [comment]
You need to set separateConnectedComponents to false

**Comment by soerendomroes** [comment]
Per default everything that is not connected will be handled as a separate graph that has its on layer grid.

**Comment by MuttakinHasib** [comment]
@soerendomroes can you share an example?

**Comment by soerendomroes** [comment]
Here you can see how it is set to true, which is the default value.

https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=general%2Fspacing%2Fcomponents

**Comment by MuttakinHasib** [comment]
BTW, I want to make the layout like this: **top alignment**
<img width="541" alt="image" src="https://github.com/user-attachments/assets/32fe9140-7cd6-4a3e-abe2-db3c4854af9e">

Not this: **middle alignment**
<img width="696" alt="image" src="https://github.com/user-attachments/assets/b130a419-dd66-49c3-8f19-186055e4997e">

**Comment by MuttakinHasib** [comment]
@soerendomroes

**Comment by soerendomroes** [comment]
This depends on the nodePlacement strategy you might be using.

[This](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=KYGw1gdAJglgTsAxgFxgewHYC4AEAlASQHEAJAFQCgBnYABwEM57lgBhTDJFqdgW1szAMyKrgBm9EDQoM4qVJhgYA5hHooYAN2bBcyOAFdgFRJiowowOAFk0lkAHk4luBCr6dygJ64Acg4ARAFEAZQB9AEFfALCggKJQnAB6JJwiNDscMTQ4HEsWOF4lGHcYRBxNK1RESRwclzqxHAw7YCoKFssABRB1YF4hZDcPFm9cACE8KODwgGkHIK6AMWTUywkDEGQO1p6+geEIACNIMRgAD2AoCJAYZQwD5FwAGSClsgCHAHVfVbzgDZbCg7SzNAAMYWUYIA7ABGADMAA4AKw4ADeFAAkL0vGgDMgcABtHDmABeuhwsLBYIANJTqTgALpY2TydAYJSqVkwBTYHBgrG9I6gHAAIloYNFFAAviDgM1YejBfRcfiiSSYOTcIjaTgdUyWYw2YoVBBubzcLDlcKQGLaLCpbLOvKMAAmJXYlV4gnEskU5G6gMGzHm9mcs1Gnns3Cu60i8Wux1y5oAFg9OO96r9uADdKDzJDkd54dDmFw8LjtvF8KTzuaqIxntVPo1WpwufbYODpY5pp75crdpTSaAA) example works for me. Can you share a minimal example in elklive that reproduces your problem?
