### ISSUE TITLE
[Question] how to get Symmetric Layout  ?

### ISSUE THREAD

**Issue by BingCoke** [kieler/elkjs#296]
like this 
![image](https://github.com/user-attachments/assets/ae7e9294-edc3-4e55-b6ab-3168bc81f386)

**Comment by soerendomroes** [comment]
Please reproduce your model in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html).

I suggest something like [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAMZYkg4BC+wA1jAHZgB0AznFMHDmFugFkA8gBEAogBkA+kIBK42WgD0StAGEIjThBBoCMfCTgxNaCADM0hMDjZo2TEjjSJnmXPgJpQkWIiRoMHb6hjzEJJoOBHgCENEgQlDRUOyc3Lz8aAByomIAylIAglkiUmIiAOL5yqoaWlA6aABueMYkoGZJeESMcTgACphOSDhaqVw8fOhUssXiBQDSQmL9AGI9fYPAw6NwLABGdCzmMAAehIUgMGCMI1rThRLFauU1aFSgwIxOVi1QWIgmGA0OZoGh9jg4DwoPYsEgRpwsEQNtE0IwAAxoADeRDQeIwwAhugARABmYlEAC+KOcjAAjNjcfjMES0MSACwAWjpFOpvVRjAATIz8QTWRzOYLeTS0aSRczCTgSezpfznHYcaKWUq2WxVX00ez5XjtSSeVSZYwAKzGsU64lSi1qtEANltprZdO5+oFAHZ3YqzZLpURrLTMZyAHz2UMEGxohlR2Wx+NCtBJxiklO0uVJtjZ+zp6OMdkFuwZq0FktF11Vo0Z31AA), which does require you to know how to create the symmetry in advance to be able to use the layered algorithm for undirected graphs.

If you cannot know this, I suggest to use [stress layout](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEBnOUCmGMBQBAdhACY5rEAMaA3gWk2iMAEY4hoBEAzNwQC+JcpWIBGeo2asOXbgBYAtOIHDSFKgCYpzFu049lWtSM3FeumQfkLTGyhitNZh7hnuiqC5-rk9VITMxAFZfV3kTIIcqADZwmwCVT3MAdgT-bnElKOECHDIwMVolAD5MfMKxSTKqXkqi7TRaiwaxS1rCAsanFoU2zGby4hCB4h8W2LGJ4dSgA).

**Comment by BingCoke** [comment]
> Please reproduce your model in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html).请在[elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html)中复制您的模型。
> 
> I suggest something like [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAMZYkg4BC+wA1jAHZgB0AznFMHDmFugFkA8gBEAogBkA+kIBK42WgD0StAGEIjThBBoCMfCTgxNaCADM0hMDjZo2TEjjSJnmXPgJpQkWIiRoMHb6hjzEJJoOBHgCENEgQlDRUOyc3Lz8aAByomIAylIAglkiUmIiAOL5yqoaWlA6aABueMYkoGZJeESMcTgACphOSDhaqVw8fOhUssXiBQDSQmL9AGI9fYPAw6NwLABGdCzmMAAehIUgMGCMI1rThRLFauU1aFSgwIxOVi1QWIgmGA0OZoGh9jg4DwoPYsEgRpwsEQNtE0IwAAxoADeRDQeIwwAhugARABmYlEAC+KOcjAAjNjcfjMES0MSACwAWjpFOpvVRjAATIz8QTWRzOYLeTS0aSRczCTgSezpfznHYcaKWUq2WxVX00ez5XjtSSeVSZYwAKzGsU64lSi1qtEANltprZdO5+oFAHZ3YqzZLpURrLTMZyAHz2UMEGxohlR2Wx+NCtBJxiklO0uVJtjZ+zp6OMdkFuwZq0FktF11Vo0Z31AA), which does require you to know how to create the symmetry in advance to be able to use the layered algorithm for undirected graphs.我[建议这样的事情，](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAMZYkg4BC+wA1jAHZgB0AznFMHDmFugFkA8gBEAogBkA+kIBK42WgD0StAGEIjThBBoCMfCTgxNaCADM0hMDjZo2TEjjSJnmXPgJpQkWIiRoMHb6hjzEJJoOBHgCENEgQlDRUOyc3Lz8aAByomIAylIAglkiUmIiAOL5yqoaWlA6aABueMYkoGZJeESMcTgACphOSDhaqVw8fOhUssXiBQDSQmL9AGI9fYPAw6NwLABGdCzmMAAehIUgMGCMI1rThRLFauU1aFSgwIxOVi1QWIgmGA0OZoGh9jg4DwoPYsEgRpwsEQNtE0IwAAxoADeRDQeIwwAhugARABmYlEAC+KOcjAAjNjcfjMES0MSACwAWjpFOpvVRjAATIz8QTWRzOYLeTS0aSRczCTgSezpfznHYcaKWUq2WxVX00ez5XjtSSeVSZYwAKzGsU64lSi1qtEANltprZdO5+oFAHZ3YqzZLpURrLTMZyAHz2UMEGxohlR2Wx+NCtBJxiklO0uVJtjZ+zp6OMdkFuwZq0FktF11Vo0Z31AA)这确实需要你知道如何提前创建对称性，以便能够将分层算法用于无向图。
> 
> If you cannot know this, I suggest to use [stress layout](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEBnOUCmGMBQBAdhACY5rEAMaA3gWk2iMAEY4hoBEAzNwQC+JcpWIBGeo2asOXbgBYAtOIHDSFKgCYpzFu049lWtSM3FeumQfkLTGyhitNZh7hnuiqC5-rk9VITMxAFZfV3kTIIcqADZwmwCVT3MAdgT-bnElKOECHDIwMVolAD5MfMKxSTKqXkqi7TRaiwaxS1rCAsanFoU2zGby4hCB4h8W2LGJ4dSgA).如果你不知道这一点，我建议使用[压力布局](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEBnOUCmGMBQBAdhACY5rEAMaA3gWk2iMAEY4hoBEAzNwQC+JcpWIBGeo2asOXbgBYAtOIHDSFKgCYpzFu049lWtSM3FeumQfkLTGyhitNZh7hnuiqC5-rk9VITMxAFZfV3kTIIcqADZwmwCVT3MAdgT-bnElKOECHDIwMVolAD5MfMKxSTKqXkqi7TRaiwaxS1rCAsanFoU2zGby4hCB4h8W2LGJ4dSgA)。

that is what i need! Thanks
