### ISSUE TITLE
Node centering in layer with multiple widths

### ISSUE THREAD

**Issue by JoanLaRosa** [kieler/elkjs#307]
Hello!
I would like to center nodes in the middle of a layer in elk.layered. I've noticed that nodes that are not connected to another layer get positioned at the baseline (left) of the current layer; on the other hand, nodes that have an edge to the next layer get positioned in the middle of the current layer:

[Link to elklive](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGAOQF4DmKSk6ACwC2beG0JEApkknQ2WdgDNeAY0kA5FNEkBZLZLwUk2pKLDokpSQoC+OCCoGQ80GfXgBtXBAD0PsIzoBEi09Fxg9PreYKww8Aj0AIzYYADuMILwAMwADAoCkpBcAujZOXYg0X4RGGBq9OjSsmAARpIqBKSMkuYFMlCMNWCyXD3oKBGSAB7o+MTS0bFwiPQATCnp0JlgufmFxaU7eXNteMxgHsCNM7AIjAK8mDYAumAVEBBL8fRZGxkC8FWOWOBSKJTKCkIp3Ol2upQQeAYXAQLzeOCq-nqjRk0Bq2kGbQ6XR6KEUw2go3ME3o01mEgWHxiUGWCQALH8tgCjnswYddicDDCrrTbvdHmACPRcVimtAUa93h8visAKwc7a5EH7cFHMCQgjQzzCm4IpESqV1SQNWVgAAU2kUkBpg3pSACkAAXpIAJTytHRDHDC2RfGLZnfABs6q5-NBBzK-sZyoSAHZoxCwHGdbk3pUIM97OTRjCw3FEJJkgpGGQkGoYStkmAC+ZgqN0PWEusm4mleHy+sqzW654Gwgmwogkg2x2fmOFYXPn2EJJfoPSLXJDPG83J9OR2y5z3F2Xl+y1xut3OJ63JO39-Q1d3FceWZI1efhxcVuzxy2p7eZyjJ8FyZE9JCjD9N3vR8dxvO8v1TQ8bDzJsQBsIA)

I would like the nodes to be centered regardless if they have edges to the next layer. I would like them ALL to be centered on the red line below:
![image](https://github.com/user-attachments/assets/ff25a83d-e86b-4d51-ab41-a05031928723)

Please let me know if there is a configuration for this. Thanks in advance!

**Comment by soerendomroes** [comment]
Hi, you can set the alignment property for each node, as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGAOQF4DmKSk6ACwC2beG0JEApkknQ2WdgDNeAY0kA5FNEkBZLZLwUk2pKLDokpSQF8cEFQMh5oM+vADauCAHpvYRugESLT0XGD0+l5grDDwCPQAjNhgAO4wgvAAzAAMCgKSkFwC6Fm5+MRklDR0TCxsBgDWAHSchfRCkvToZmwAwgCi6gAq-QBKbNa2IFG+4Rhgal3SsmAARpIqBKSMkub5MlCMc2CyXLvoKOGSAB7o5VJIUTFwiPQATMlp0BlgOXkFRRKvzKEkq1FoDGY0XqeGarS47U63TEA2GYwmCkI6zwUPcwHQNxKCEYAl4mGsAF0wFMIBBnnF6JlPukBPA3tkyvlCsVSpiKuRwTUocAYXC8G0Ol0eqiRuNbOVsbj8YTYAg8AwuAhKdScDM-IsCTJoHNtEd1pttrsUIoTtAzuZLvRCfdpE8oC94gAWZnfVnA-7coF-e5g6qQuqNFrihGS5HsGXo+VYgxKgm3VUkslgAj0Y0G5bQLVUmm0+mvACsPp+OU5AJ5-pDArDtWhkfhiKlKMGsomYD5io8yvTao12dzCyRBbAAAptIpIE6jhJpP5IAAvSQASiLOqiepO44iprdsVeADYq37g1zAaVd7Tou6GQB2S+8sA3+s5anTCAUuy2mcuInh6khJAojBkEgai4q8SRgP+5hBGc6CwfEHwIfepZPogkgfBBUEwR4cEIAhCiBEgKFoYypHFgBdI4QgkhMgRpDQZI1HwYhFFUcRXq0VhDGnkx3qsexnG0eRyGSKhfH0JWmElkJoGVmJRFgO4rzemRSGUTJ1EXop9GPsJkgXmpHFyQp3HSbJGmvK+im-ghIDWEAA).

https://eclipse.dev/elk/reference/options/org-eclipse-elk-alignment.html

**Comment by JoanLaRosa** [comment]
Thank you so much! I thought putting that setting in the root layoutOptions would do the trick but it didn't. I did not realize I had to set it to the properties of each node.
