### ISSUE TITLE
Additional documentation

### ISSUE THREAD

**Issue by elbosso** [kieler/elkjs#70]
I would like to invite you to consider tweaking my project of turning elkjs into a dockerized microservice using express: https://github.com/elbosso/elkjsmicroservice
Maybe you want to add it (or parts of it) to your documentation efforts.

Best regards,

Juergen

**Comment by uruuru** [comment]
Thanks for making me aware of it. I'll take a closer look when I find time. 

One thing I'm wondering is whether using the (plain) Java libraries of ELK is advantageous in this scenario. At least in an environment where Java is available, as the Java version should execute significantly faster. 
@spoenemann do you have experience with similar use cases?

**Comment by spoenemann** [comment]
But using the Java version also means you have to transfer all data on the server and run the algorithms on the server. The JS version delegates all that effort to the user's browser, so it's more scalable in terms of numbers of users.

@uruuru shall we add that link to the readme?

**Comment by uruuru** [comment]
Isn't the idea of a dockerized microservice to run it on a server (or at least in the container)?

**Comment by elbosso** [comment]
Well yes - the idea was to offer the service of laying out graphs as a service for other applications to use. It would of course be possible to do it as a java version too. As i wrote - at the moment it is merely an idea for some documentation effort. From that vantage point - maybe it would be event better to also offer a dockerized java version as microservice so potential users could compare them?

**Comment by uruuru** [comment]
Yes, I guess it depends on the environment you work with. If you have a Java env anyway, it's likely better to use a dockerized java version. 
However, if you try to avoid the Java overhead, your current setup should work fine. 

I've added a link to the readme.
