### ISSUE TITLE
Wrong spacing inside group

### ISSUE THREAD

**Issue by krzysztofpniak** [kieler/elkjs#73]
There is wrong spacing between child and group border when ports with side: 'EAST' exist.
Spacings should be the same on both sides.

<img width="106" alt="Zrzut ekranu 2020-03-17 o 20 14 55" src="https://user-images.githubusercontent.com/2463068/76893079-06fa5280-688c-11ea-9abf-85f8b35a0d1d.png">

reproduction: 

https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYHIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAgKZ4DWAdAXgDmKJJHQALALYJ4CQkQ5IO0bLnZc+ywRwBKZWvUEzEFHQBUAEhQDiFAHIBBADKqIAXxwQAxuMh5oSvTwANpqYKxsEDCy9ABMrpFgVKhUirQczOFUIugAwgyM6EgEkPTomQgAYgCSABoAogAiAPqmjfU6CB5hENlI5SE9bBGJbNGIVPGeo2wA7jAS8ACMAAzTM2DiHJCC4ujLa0ORySip-ZAZLEeJnDy8fei8AEYi0IoUAGYfjByY8AC0q3WG0QGnuOV4jBgHGMCAA6vUAMpmBIbbpo4GREYzcYIKgAVlRM3m0EWYCB1wgWx2ewOmMSJzO6Uy2I2tz4D2er3eXx+fzAgMOILY7PB-Uh0Nh9QcyKJo3RMwVkQAuvSfH4AhwgmBQhtWYlcfQAMxyhkpNIXFkPfJMIolMoVGoNFptDpdemRElk-FCkHU3b7MA+j1sB6ZXXC8KUg1wCYmkOjL3iOnRyL+2nk32RpLm86XKPZyKizlQt6whGyhMzYsQl5IN5IT7fX7GQVVyJKkGdvWpsaxvEAFlNGyTKcLm22AbHhcZFvz+uFNfFpZhsmlld7RbBnLrDabfNbFPH3cVVdV1xP59GWnzEdGwFxHCmYEYZCQXlvePiqrA6AISG0AYdTxE1lRPCAH37Dh4xfN8P3DQcEB-P8AN+BCCSQy9gQVK8wBvcNzzcEAgA

**Comment by le-cds** [comment]
I created an issue at our main project's repository for this: eclipse/elk#530
