### ISSUE TITLE
Disco and componentLayoutAlgorithm settings

### ISSUE THREAD

**Issue by schwichti** [kieler/elkjs#74]
Hi,
I want to use the disco layout algorithm and layout the sub conntected components with let's say force.

When I use the following `layoutOptions`, nodes get extreme values for x,y, width and height.
```json
{"layoutOptions": { 
"algorithm": "disco",
"org.eclipse.elk.disco.componentCompaction.componentLayoutAlgorithm": "force", 
}}
```

see https://github.com/crossecore/ecore-editor/blob/master/src/components/SprottyDiagram.tsx#L27

What is the right way to configure disco?

**Comment by uruuru** [comment]
Looks fine, see [this example](http://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGLhAOQF4DmKSkdAAsAth3gdokRgGMUHHBE5TZKAHRyRVBgFN66AMIotBGbQYbj2+nvQAZYmXQBBXv0GjxYDgDN+MnQ5cAF9FMBkhSDxoJD14AG12MFYYeAR6AEZsMAB3GGF4AGYABiwwIR1IHiF0IuKwUKSUuER6ACZsvOgCsBKyiqqauoawiGa0+kLO-KE6-srq2t76xqVkqBb0gBZp7tnl+cGlkobcAF0wnWgeHWYwRLXxxB0sssYyJAC7+NassAuwOgCEgbuhvq0Ov8Rk0NmkdB03h8vglWlN-mUgSCdGCUdsEFDgucQMEgA).

Could you try `layered` instead of `force` to see if the extrem values stem from `force` as opposed to from `disco`?

**Comment by schwichti** [comment]
I tried out difference algorithms. Here is what I observe:
| algorithm | observed effect |
|---------|----------------------------------------------|
| layered | no exteme values. diagram looks as expected. |
| force   | somewhat exteme values (x=5000)              |
| disco   | extreme values (x=19454399258.04417)         |

I have printed my ElkGraph to the debugger console and pasted it to elklive. In elklive I get the following effects:
| algorithm | observed effect |
|---------|----------------------------------------------|
| layered | looks fine |
| force   |  looks fine              |
| disco   | no diagram shown (extreme values?)         |

I cannot deeplink my ElkGraph in Elklive because it is too large `414 Request-URI Too Large`. So I have put it here: https://github.com/crossecore/ecore-editor/blob/master/elkgraph.json

**Comment by uruuru** [comment]
```
{ 
    'algorithm': 'disco',
    "org.eclipse.elk.disco.componentCompaction.componentLayoutAlgorithm": "layered",
  }
```
This combination works for me in elk live. I'll take a look why force produces weird results.

**Comment by uruuru** [comment]
I believe the issue may be caused by selfloops. If I remove all selfloops from your graph, it lays out successfully. 

I'll investigate the issue further and likely create a ticket with ELK itself. As an initial workaround you could omit the selfloops prior to layout.

**Comment by schwichti** [comment]
Actually, there are two issues:
1. when I pass the `layoutOptions` argument to `Elk.layout()` I get extreme values for some layout algorithms. I solved this by setting the `layoutOptions` directly in the root ElkNode. Therefore, my original problem is solved.
2. using disco in conjunction with force. As you described, this seems to be an open issue. 

Regarding the second issue: I do not need the fix because now I am using just `stress` (without `disco`) which looks good.

**Comment by uruuru** [comment]
Thus, for you this ticket is solved? If yes, I'll create separate issues for further investigation.

**Comment by schwichti** [comment]
Yes, I am closing.
