### ISSUE TITLE
"Models" live demo failed due to github rate limits

### ISSUE THREAD

**Issue by yellow1912** [kieler/elkjs#76]
The current model browser demo seems to have an error:

https://rtsys.informatik.uni-kiel.de/elklive/models.html

![image](https://user-images.githubusercontent.com/374134/81197327-50dcfa80-8fea-11ea-877d-335b88933ac1.png)

**Comment by uruuru** [comment]
It's related to github's rate limits, which have been reduced at some point, I believe. The demo usually works for a short while after the rate limit cycle starts new.

**Comment by le-cds** [comment]
🤣 

Is there anything we can do about it?

**Comment by uruuru** [comment]
Yeah. 
With the introduction of the examples page, we require a checkout of the elk-models repo on the server anyway. I'll see that I adjust the models example correspondigly one the repo checkout is integrated.

**Comment by uruuru** [comment]
I altered the code to use a local copy of the `elk-models` repo. Hence the demo should be running more reliably now.
