### ISSUE TITLE
Overlapping orthogonal edges

### ISSUE THREAD

**Issue by matthewatabet** [kieler/elkjs#77]
I have the following graph:
<img width="706" alt="Screen Shot 2020-05-26 at 1 37 38 PM" src="https://user-images.githubusercontent.com/6320630/82932391-5b8a1000-9f56-11ea-910e-308eb390e52a.png">

There are some crossings between the subcomponents which results in overlapping edges (see center of graph). How can I resolve this? I tried setting both `elk.spacing.edgeEdge` and `elk.layered.mergeEdge` but with no luck.

Thanks!

p.s. here is the json data (with a .txt extension as github won't let me upload .json):
[overlap_out.txt](https://github.com/kieler/elkjs/files/4684029/overlap_out.txt)

**Comment by matthewatabet** [comment]
p.p.s. elkjs is seriously awesome -- after getting by with graphviz for a year, it's a breath of fresh air.

**Comment by matthewatabet** [comment]
I'm using a custom renderer in React. If it's helpful, here's a screenshot of the same graph rendered with the interactive elkjs viewer.
<img width="698" alt="Screen Shot 2020-05-26 at 1 47 45 PM" src="https://user-images.githubusercontent.com/6320630/82933222-9cceef80-9f57-11ea-8d05-885734f6e29b.png">

**Comment by uruuru** [comment]
You encountered a limitation of the current implementation, see eclipse/elk#318

As far as I understood @le-cds, a solution has been implemented by a student (but still has to be integrated into the master). The current plan is to have this in the next release.

**Comment by matthewatabet** [comment]
@uruuru great, thanks!

**Comment by le-cds** [comment]
...which reminds me... ;)

**Comment by uruuru** [comment]
Has been fixed in elk, will be part of the next release.
