### ISSUE TITLE
Hierarchical layout broken

### ISSUE THREAD

**Issue by matthewatabet** [kieler/elkjs#78]
Hello -- I have a recursively defined diagram defined in Python. The resulting json loads fine in the elk json editor if the recursion depth is low. However, with any meaningful complexity the layout quickly becomes scrambled. Do you have any tips for laying out these larger diagrams?

Here's an example of a small diagram whose layout looks nice and neat:
<img width="389" alt="small_render" src="https://user-images.githubusercontent.com/6320630/83301464-b2e2e700-a1c7-11ea-890d-36a70f906ee2.png">

And here's a larger diagram with a similar structure but more nested layers:
<img width="575" alt="big_render" src="https://user-images.githubusercontent.com/6320630/83301494-c42bf380-a1c7-11ea-8b6e-5e6a6e51f22d.png">

I've attached the json source. Thanks for your help! btw, I fully appreciate that laying out large graphs like this is VERY HARD (if not impossible). But, I'd love to hear about any tips or tricks you've come across. I was thinking of calling `layout()` within a loop, laying out each layer of the graph separately and them composing the results back together.

[small.json.txt](https://github.com/kieler/elkjs/files/4704106/small.json.txt)
[big.json.txt](https://github.com/kieler/elkjs/files/4704107/big.json.txt)

**Comment by uruuru** [comment]
In principle the graph should be laid out properly and is far from what I would consider a large graph :). 

I'll take a look if there's something broken in the description or if it's simply a bug.

**Comment by uruuru** [comment]
There seem to be two problems:
 * First, your edge containments are not always according to the conventions, see the part on "edge containment" [here](https://www.eclipse.org/elk/documentation/tooldevelopers/graphdatastructure.html). (As users struggle with this time after time, we should probably automatically adjust them).
 * Second, there seems to be a bug with `layoutHierarchy: INCLUDE_CHILDREN`. If you uncomment it for the outermost node, the result looks like below. I believe there has been a similar ticket quite recently. Further note, that for your graph `layoutHierarchy` is actually not required. 

Json with fixed edge containments: [json_fixed.txt](https://github.com/kieler/elkjs/files/4705770/json_fixed.txt)
Elkt for further debugging: [elkt.txt](https://github.com/kieler/elkjs/files/4705771/elkt.txt)


![image](https://user-images.githubusercontent.com/7552459/83330830-22bda400-a292-11ea-8285-4c9bcc30400d.png)

**Comment by matthewatabet** [comment]
@uruuru Awesome! Thanks so much -- that looks fantastic.

Confirmed that this worked for me. I'll read up on edge containments.

btw, thank you for the great support. ELKjs is wonderful and the few issues I've found have been addressed very quickly. 🏆

**Comment by uruuru** [comment]
Thanks. Always happy to help :).

**Comment by uruuru** [comment]
Has been fixed in elk, will be part of the next release.
