### ISSUE TITLE
Support for instances during layout

### ISSUE THREAD

**Issue by matthewatabet** [kieler/elkjs#79]
Hello!

I have some very large diagrams where the subgraphs often repeat themselves. Here's a scaled down example:

<img width="790" alt="Screen Shot 2020-06-04 at 6 51 03 PM" src="https://user-images.githubusercontent.com/6320630/83818111-7fef9600-a694-11ea-9fc9-504bebea947e.png">

It's pretty clear that the four subgraphs are all the same. For larger diagrams, it seems we could save a lot of time by not redoing this layout work.

Does elk offer any options for instancing or reusing layouts within a single diagram? I can imagine ways to do this in Javascript by laying out portions of the graph and then copying the positioning as needed. But, I wanted to see if this was supported directly in the library first.

Thanks a bunch!

**Comment by uruuru** [comment]
It's not something we have considered so far. Could you maybe transfer this issue to the ELK repo? It would have to be discussed and implemented there. To be honest, I don't think it's something that will be realized any time soon (if at all). 

Having said that, you can probably 
 1) pass one of the four symmetric hierarchical nodes to the layout algorithm, 
 2) apply the computed dimensions to the others,
 3) call layout on the root node (omitted the "internal", maybe the option `elk.noLayout` can be used), and
 4) transfer the layouts of the inner nodes to ally symmetrical cases (can be step 2 or 3 as well).

**Comment by uruuru** [comment]
I'll close this as I don't see this being tackled in the near future. Feel free to reopen if anything comes up.
