### ISSUE TITLE
Scaling nodes horizontally to include labels

### ISSUE THREAD

**Issue by matthewatabet** [kieler/elkjs#81]
Hi there,

The application I'm building requires multiple labels on each port to display not only the port name but also extra data useful during simulations which are generated from the graph.

I've found a recipe that allows the nodes to scale vertically to enclose all ports and labels, regardless of how many labels each port might have (sweet!).

The problem now is I can't seem to find how to make this happen horizontally.

[Here's a test in the elkjs json viewer.](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAOQF4DmKSk6ABYBbdvHaEiAUyRTo7HGzDsqfdABkCAIyl5GAOiqEAxlOFT66McoCSAOQDKNgCIBRBbg70U0KZp16hiZmFlbiAGoA+gBCFAAqcRQAsh4QAL6KYMaCkHjQsvTwANqeYMBQcIj0AIzYYADuMELwAMwADFhgglKQ3ILorW1gGaXlMPAI9ABMdY3QzWDtnd29-YPDmRCsShUT9C3YpRCSZJQ0dEwsR2zs3r7+ugZGBKbmltbs9k5uYFGJAApgAASkQAwq47HFXAAlVI7DiqJAabSPIIvELvcRfFzuTY7W4+KQOSAALyk+mMDEY6CQBEglkYHzsFDckXUAEFoq51A4wP8KNC4rz+YK2ZzubykvYbEkAKpJSJOABauOuXkJxLJ+hQ5ypHzcADF2bL1HFIlK7DL5YqbCqwKDkv9ZVDIv92c5nPYAOLsa4jeGEALMMAleFbdBSAAeA0QADcZER8AxuGA7lJ8Ci8Ag0tcALp4iCI9DB0Nh7Zh3aIAiHCsQOYLACsBZ2Kz6MabarYgcexU7SnLtYgEejE27WebFdbazA1SmfbY-sHZXnSmHMYQY5rS4gU5j1TaK+G89zncX8IH8PGiEjW4r9cE8A7g93j4nXczJcPF9ra9HmdvS4vjOc7bmetbfhWv6IJub7wkB+6HmBFYQWGUEbsmYBFhmAQAc+PRtvACGgbBbAofCaEwYeO74dORFLkhZZUWAFH-iRSjwQeoHHqeealDmED5rgcjcFIn79pWCBSLUnSMGQSCmCWVS1GA+bMQQSAicWxRVDMKkbKMElSDMMlyQp2mTMpqnoOpmmKZMBx6fxKkgGkQA)

Which looks like this:
<img width="582" alt="Screen Shot 2020-06-16 at 4 27 56 PM" src="https://user-images.githubusercontent.com/6320630/84824698-5caadc00-afee-11ea-98a8-11853f83dbb7.png">

As you can see, the node in the lower right is scaled correctly vertically. But, the text of the labels still dangles off the right.

Thanks!

**Comment by matthewatabet** [comment]
Ah, one possible solution here is to define a `width` for each label. Does that sound about right?

That seems pretty straightforward. If that's the best practice, I can use that. Thanks!

**Comment by uruuru** [comment]
It's the correct - and only - solution. elkjs itself doesn't know anything about the font size and family that shall be used. Hence, the size (width and height) hast to be pre-computed (under consideration of the rendering you're using) and passed to it.

**Comment by matthewatabet** [comment]
Works for me! Thanks
