### ISSUE TITLE
Question on using web worker in bundled version

### ISSUE THREAD

**Issue by JenLyndle** [kieler/elkjs#82]
Thank you for this wonderful library! I have a newbie question though: In my Ember app, am facing issues specifying the url to the elk worker using the workerUrl. specifying the node modules path will work with my dev environment but not in the production build obviously. I could extract the worker into my assets and try building from there but I wanted to check if there are alternatives to that.
I tried using the bundled version. When using the bundled version and using the ELK() object without a workerUrl param passed, is the web worker still used by default? If not, what is the option to include it?

**Comment by uruuru** [comment]
There's no way to use a webworker with the bundled version.

I'm not familiar with Ember and what the idomatic way for such frameworks is. But my feeling would be to copy the worker into your assets during build and then use that path for `workerUrl`.

**Comment by JenLyndle** [comment]
Thanks a lot for your response!
