### ISSUE TITLE
Children in hierarchical nodes are not within the parents boundaries, location-wise

### ISSUE THREAD

**Issue by MawiraIke** [kieler/elkjs#88]
I am trying to pass my JSON to the ```elk-js/layout``` [function](https://github.com/kieler/elkjs#nodejs) and get the resulting graph but there is an overlap in the generated graph.
My Json ```root``` has 3 ```children``` in which two are [hierarchical nodes](https://www.eclipse.org/elk/documentation/tooldevelopers/graphdatastructure.html) each with its own ```children```. The third one is a simple node. The Json is attached after the next paragraph. 

I would like the generated graph to have the three children with the simple node sandwiched between the other two horizontally and with edges connecting the children of either hierarchical nodes and the simple node. The children in the hierarchical nodes should be contained within it, location-wise as in the image below.
In the generated graph however, the ```x``` and ```y``` positions of every child node except the simple node overlap each other at ```(0,0)``` and 2 rows horizontally and vertically from there. The parent nodes however are at the right place together with the edges that are supposed to connect their children, (Looking like the children are invisible, -but they are not, and they are overlapping at the ```(0,0)``` position.) Basically, the child nodes are not contained within the parent node. Funny enough the code works in the [online live editor](https://rtsys.informatik.uni-kiel.de/elklive/json.html) and generates the graph below which is what i expect, even in the generated graph in my code. What could i be missing? I suspect maybe there is an option that can fix this? The used options are,

``` json
 {"elk.algorithm":                 "layered",
  "elk.hierarchyHandling":         "INCLUDE_CHILDREN",
  "spacing.nodeNodeBetweenLayers": 150.0}
```

The expected graph should look like this,

[![expected][1]][1]

My json is, 

```
{
  id: "root",
  layoutOptions: { 'algorithm': 'layered',
                   'hierarchyHandling': 'INCLUDE_CHILDREN',
                   'spacing.nodeNodeBetweenLayers': '100.0' },
  children: [
    {
        id:"analytics1",
        level: "cluster",
        name: "analytics1",
        children: [
            {
                id:"animate1",
                level: "leaf",
                height: 30,
                width: 30,
                parent: 1,
                labels: [{"text":"a"}]
            },
            {
                id:"animate2",
                level: "leaf",
                height: 30,
                width: 30,
                parent: 1,
                labels: [{"text":"b"}]
            },
            {
                id:"animate3",
                level: "leaf",
                height: 30,
                width: 30,
                parent: 1,
                labels: [{"text":"c"}]
            }
        ]
    },
    {
        id:"analytics2",
        level: "cluster",
        name: "analytics2",
        children: [
            {
                id:"animate6",
                level: "leaf",
                height: 30,
                width: 30,
                parent: 1,
                labels: [{"text":"f"}]
            },
            {
                id:"animate8",
                level: "leaf",
                height: 30,
                width: 30,
                parent: 1,
                "labels": [{"text":"h"}]
            }
        ]
    },
    {id: "n1", width: 30, height: 30, labels: [{text:"d"}]}
  ],
  edges: [
    {id: "e1", sources: ["animate2"], targets: ["n1"]},
    {id: "e2", sources: ["animate3"], targets: ["n1"]},
    {id: "e3", sources: ["animate1"], targets: ["n1"]},
    {id: "e4", sources: ["n1"], targets: ["animate8"]},
    {id: "e5", sources: ["n1"], targets: ["animate6"]},
  ]
}
```

Previously issue #87

  [1]: https://i.stack.imgur.com/r19yf.png

**Comment by uruuru** [comment]
Can you share the resulting json you get? With the x and y coordinates?

**Comment by MawiraIke** [comment]
Okay sure, on it. :+1:

**Comment by MawiraIke** [comment]
The Json i used is,
```
{"id": Root, 
  :edges #{
	{"id": G__537, "sources": [ma], "targets": [de]} 
  	{"id": G__538, "sources": [ot], "targets": [de]} 
  	{"id": G__539, "sources": [pr], "targets": [de]} 
  	{"id": G__540, "sources": [cs], "targets": [de]} 
 	{"id": G__541, "sources": [de], "targets": [tc]} 
  	{"id": G__542, "sources": [de], "targets": [other]}}, 
  "children": (
    {"id": 1, "name": inp, "children": (
	{"id": ma, "width": 52, "height": 52} 
  	{"id": ot, "width": 52, "height": 52} 
  	{"id": pr, "width": 52, "height": 52} 
  	{"id": cs, "width": 52, "height": 52})} 
    {"id": 2, "children": (
	{:id tc, :width 52, :height 52, "type": asset} 
	{"id": other, "width": 52, "height": 52})} 
    {"id": de, "width": 52, "height": 52}), 
  "layoutOptions": {elk.algorithm layered, 
  elk.hierarchyHandling INCLUDE_CHILDREN, 
  spacing.nodeNodeBetweenLayers 150, 
  layered.mergeEdges true, 
  spacing.nodeNode 15.0}}
```

And the resulting JSON was, (sorry about the formatting, it's still valid in my program)
```
{:y 0, 
  :children [
    {:y 12, 
    :children [
      {:id ma, :width 52, :height 52, :$H 710, :x 12, :y 12} 
      {:id ot, :width 52, :height 52, :$H 713, :x 12, :y 84} 
      {:id pr, :width 52, :height 52 :$H 716, :x 12, :y 156} 
      {:id cs, :width 52, :height 52, :$H 719, :x 12, :y 228}], 
     :$H 707, :width 76, :id 1, :x 12, :height 292} 
    {:y 12, :children [
      {:id tc, :width 52, :height 52, :$H 725, :x 13, :y 12} 
      {:id other, :width 52, :height 52, :$H 728, :x 13, :y 84}],
    :$H 722, :width 77, :id 2, :x 450, :height 148} 
    {:id de, :width 52, :height 52, :$H 731, :x 243, :y 24}], 
  :$H 705, :width 539, 
  :layoutOptions {:elk.algorithm layered, :elk.hierarchyHandling INCLUDE_CHILDREN, :spacing.nodeNodeBetweenLayers 150, :layered.mergeEdges true, :spacing.nodeNode 15.0}, 
  :id Root, :x 0, 
  :edges [
    {:id G__537, :sources [ma], :targets [de], :sections [{:id G__537_s0, :startPoint {:x 76, :y 50}, :endPoint {:x 243, :y 50}, :incomingShape ma, :outgoingShape de}]} 
    {:id G__538, :sources [ot], :targets [de], :sections [{:id G__538_s0, :startPoint {:x 76, :y 122}, :endPoint {:x 243, :y 50}, :bendPoints [{:x 103, :y 122} {:x 103, :y 50}], :incomingShape ot, :outgoingShape de}], :junctionPoints [{:x 103, :y 122} {:x 103, :y 50}]} 
    {:id G__539, :sources [pr], :targets [de], :sections [{:id G__539_s0, :startPoint {:x 76, :y 194}, :endPoint {:x 243, :y 50}, :bendPoints [{:x 103, :y 194} {:x 103, :y 50}], :incomingShape pr, :outgoingShape de}], :junctionPoints [{:x 103, :y 194}]}
    {:id G__540, :sources [cs], :targets [de], :sections [{:id G__540_s0, :startPoint {:x 76, :y 266}, :endPoint {:x 243, :y 50}, :bendPoints [{:x 103, :y 266} {:x 103, :y 50}], :incomingShape cs, :outgoingShape de}]} 
    {:id G__541, :sources [de], :targets [tc], :sections [{:id G__541_s0, :startPoint {:x 295, :y 50}, :endPoint {:x 463, :y 50}, :incomingShape de, :outgoingShape tc}]} 
    {:id G__542, :sources [de], :targets [other], :sections [{:id G__542_s0, :startPoint {:x 295, :y 50}, :endPoint {:x 463, :y 122}, :bendPoints [{:x 305, :y 50} {:x 305, :y 122}], :incomingShape de, :outgoingShape other}], :junctionPoints [{:x 305, :y 50}]}], 
    :height 316}
```

**Comment by uruuru** [comment]
From a brief look at your output your nodes' positions look fine. Is it possible that there's an issue with the way extract the x and y coordinates?

**Comment by MawiraIke** [comment]
Thanks for checking it. But the positions are off. For example look at the following two elements,
A child of the first root child (root->1st->1st)```(id: ma)```,
```
 {:id ma, :width 52, :height 52, :$H 710, :x 12, :y 12} 
```
And 2, the first child in the second root child (root->2nd->1st)```(id: tc)```
```
{:id tc, :width 52, :height 52, :$H 725, :x 13, :y 12}
```
These two are placed at the same position. Even though ```x``` is offset by 1, the item width is still 52.
Also, the current model is quite rigid and might fail to render well in some cases. i.e without the manual  ```:spacing.nodeNodeBetweenLayers 150``` layout option, the first hierarchical root child (root->1st)```(id: 1)``` overlaps with the third simple root child(```id: de```) which is in the middle and even ```(id: 2)``` sometimes since its too big. That is its size is way bigger than the size of its children combined and hence it extends to other parts of the graph.

**Comment by uruuru** [comment]
Are you considering that the positions are relative to the parent nodes? See [here for an illustration.](https://www.eclipse.org/elk/documentation/tooldevelopers/graphdatastructure/coordinatesystem.html).

**Comment by MawiraIke** [comment]
Yeah, for instance the three main children ```1```, ```2```, ```de``` are laid out okay with the manual spacing. I would expect that their children are relative to the parents position and would have coordinates within the main parent. But instead, all the coordinates of the children overlap around ```(0,0)```

For example notice that the children of the two hierarchical nodes overlap around the top left corner (marked nodes that overlap)

children of node ```1```
```
{:id ma, :width 52, :height 52, :$H 710, 
                                                            :x 12, :y 12}  <-- overlap 1
{:id ot, :width 52, :height 52, :$H 713, 
                                                            :x 12, :y 84}  <<-- overlap 2
{:id pr, :width 52, :height 52 :$H 716, :x 12, :y 156} 
{:id cs, :width 52, :height 52, :$H 719, :x 12, :y 228}
```

children of node ```2```
```
{:id tc, :width 52, :height 52, :$H 725, 
                                                                :x 13, :y 12} <-- overlap 1
{:id other, :width 52, :height 52, :$H 728, 
                                                                :x 13, :y 84} <<-- overlap 2
```

while node ```2``` coordinates are located at the right place ```x: 450 :y12```
```
{:y 12, :children [
  {:id tc, :width 52, :height 52, :$H 725, :x 13, :y 12} 
  {:id other, :width 52, :height 52, :$H 728, :x 13, :y 84}],
    :$H 722, :width 77, :id 2, :x 450, :height 148}
```

I would expect that its children being relative to its position would be around ``` x : (450 <-> 527), y:(12 <-> 160) ```  but the ```x``` is largely off, ``` x: 13, y:12 ``` and ``` x:13, y:84 ```. ```y``` coordinate looks fine.

**Comment by uruuru** [comment]
I presume whatever you use for rendering uses a common coordinate system for all positions. 

Node `1` has `x: 12`, its child node `ma` has `x: 12`, hence in a _common_ coordinate system node `ma` should be placed at `x: 12+12 = 24`. 

Node `2` has `x: 450`, its child node `tc` has `x: 13`, hence its common position is `x: 450 + 13 = 463`. 

Consequently, `ma` and `tc` shouldn't overlap it you correctly add the parent nodes's positions to the children. 

Hope this helps.

**Comment by MawiraIke** [comment]
Thank you for the help again.
Does that mean that the addition should be manual? That is I should do the addition and add e.g ```x: 450 + 13 = 463``` manually? If that is the case then this issue is resolved.
I thought that elk-js automatically does the layout and I am just supposed to display the elements. 
If the case is as you said however, thanks a lot for the help.

**Comment by uruuru** [comment]
Yes, you have. 

It does the layout itself :). Just not in a common global coordinate system as you expected. It depends on the rendering framework what exactly is required, which is why elkjs doesn't convert everything but leaves that to the user.
