### ISSUE TITLE
Multiple small components in the row directly under the big component

### ISSUE THREAD

**Issue by Nic30** [kieler/elkjs#93]
Hello,

is it possible to achieve something like this in layered layout?
![image](https://user-images.githubusercontent.com/5032806/92894800-2deca800-f41b-11ea-8880-c97ae288ee5d.png)

If you look at the place where `CTX` label is there is lots of small nodes in the same virtual column.

I do not know If I am doing something incorrectly but with default settings the components in a single column have virtually the same width.

![image](https://user-images.githubusercontent.com/5032806/92895678-00542e80-f41c-11ea-8106-7f8bf0070c23.png)

This means that only a single small component can fit under the big component which is very ugly.

**Comment by uruuru** [comment]
>This means that only a single small component can fit under the big component which is very ugly.

Unfortunately that's a problem of the underlying approach, which stems from the fact that it originally did consider all nodes to have a uniform size. 

There are some approaches in the literature that distribute wider nodes across multiple layers. For ELK layered, unfortunately, we found these approaches to not be maintainable and removed support with 0.7.0 (see [elk#523](https://github.com/eclipse/elk/issues/523).

You could give _post compaction_(https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-compaction-postcompaction-strategy.html) a try: `layered.compaction.postCompaction.strategy: EDGE_LENGTH`. However, given the complexity of your graphs, I could imagine it being instable at times.

**Comment by Nic30** [comment]
Thanks for fast response.

Do you know about anyone else who requires this functionality in ELK?

If I understand correctly it is a complicated thing and ELK architecture is not ready for it. That means that in near future (0.5y) this feature will not be part of ELK.

Do you know about any library which does have this feature?

**Comment by uruuru** [comment]
> Do you know about anyone else who requires this functionality in ELK?

It comes up regularly. Our shot at solving it to a certain extend is the postCompaction strategy I mentioned above. 

> If I understand correctly it is a complicated thing and ELK architecture is not ready for it. That means that in near future (0.5y) this feature will not be part of ELK.

There's nothing planned in that direction. As a note, I wouldn't say it's solely related to ELK's architecture. I believe the layered approach itself is simply not well-suited for largely varying node dimensions. 

> Do you know about any library which does have this feature?

I believe dot includes something like this.

**Comment by Nic30** [comment]
> postCompaction

Thanks, I will try.

> I believe dot includes something like this.

Can dot really do layered graphs with orthogonal routing?

**Comment by uruuru** [comment]
>Can dot really do layered graphs with orthogonal routing?

dot is the same underlying approach. I believe you are correct in that they don't have orthogonal routing. The port support is limited as well.

**Comment by Nic30** [comment]
OK, thanks for variable informations. It seems that postCompaction does not work for me well, hopefully one day this will be implemented.

Anyway if I you have some potential thesis topic related to this or any other related to elk/elkjs maybe I can find some student to work on it.
(On premise that I can provide at least some level of expertise for a student in that area.)
