### ISSUE TITLE
Node with self-connected edge problem

### ISSUE THREAD

**Issue by andreyjamer** [kieler/elkjs#94]
Since version 0.5.0 edges that start and end on the same node are displayed to close to the node. It makes impossible to add labels for them.
Here is an example:

```
algorithm: layered

node n1
node n2
edge n1 -> n2
edge n2 -> n2

```
Edge ```n2 -> n2``` is drawn around node ```n2``` in 0.4.1
And very close to ```n2``` in 0.5.0+

Link to example: https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQHYQE5qkCMZFVpATEYWIzWgLQB81LbRk259mQA

Is it expected? And is there any parameter in configuration to disable such behavior?

**Comment by uruuru** [comment]
The self-loop placement code has been reworked in between the versions that you mention; the behavior is expected. 

What do you mean by the following?
>  It makes impossible to add labels for them.

You can still add labels to the self-loops, it's just that the segment shared between edge and label is way smaller. 

Afaik there's no option to force the self-loop to wrap around the node again. @le-cds may correct me if I'm wrong.

**Comment by andreyjamer** [comment]
Well, may be not impossible, but useless. If there are several nodes with self-loops, then graph becomes a mess: it's unclear what label relates to the edge. 
Here is an example: https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=KYGw1gdAhiDmD2AnAlgFwBYFsBcACA5CFAJ7CLAAm+AUKJBcuQMarLwB2e+AIgPIDqAORp0IlWMABK8AK6t2sLr0kAVABK8A4r0EBBADI1q7eBWC52ARmOnz7AEy0KEi5dwBaAHwX7uAN5EAEagAESowADOqCEAvk4uDh7eiQFQwSAhyLhQmLgRoABm7iDw8AAOuEGhcUA

As you see ```i am self-loop label``` placed far away from the edge.

BTW in 0.4.1 the label is placed in the very top of the graph, so such labels are useless at all. So in newer versions position of the label calculated better, but the edge itself looks worse.

**Comment by uruuru** [comment]
Regarding your example, there seems to be an issue in sprotty's size estimation. 
In Java itself the result looks as follows:
![image](https://user-images.githubusercontent.com/7552459/94465766-b2cc1580-01c0-11eb-8904-02238fef2633.png)

And when manually setting a proper width for the label (I looked it up in the generated svg), the result looks fine in elk-live as well: 
```
elk.algorithm: 'layered'
elk.direction: 'DOWN'
elk.edgeRouting: 'ORTHOGONAL'

node n1
node n2
edge n1 -> n2 {
    label "test"
}
edge n2 -> n2 {
    label "i am self-loop labe2l" {
        layout [ size: 125, 15 ]
    }
}
```

Regarding the result in 0.4.1: The edge labels of self-loops were plain ignored during that version if I remember correctly. Hence, all of them end up at (0, 0), which happens to be the top left corner.

**Comment by andreyjamer** [comment]
This is not sprotty's issue. This is definitely an elkjs bug. I'm using elkjs to calculate graph and draw it using svg. Result is the same as in example.

Anyway thank you for the explanation. I'll think how to improve labels in my app.

**Comment by uruuru** [comment]
In the following screenshot you can see that as soon as I manually set the width of the label to the width it will be rendered at in the svg, the layout is fine. 
![image](https://user-images.githubusercontent.com/7552459/94470836-80261b00-01c8-11eb-8bdb-02682cb8b5f1.png)

I didn't double-check the width that sprotty estimates when no manual width is set  (I would have to start the server locally) but I would assume it to be larger.

**Comment by andreyjamer** [comment]
Ok, thank you for your help!
