### ISSUE TITLE
Converting from klayjs to elkjs

### ISSUE THREAD

**Issue by Malte-Hansen** [kieler/elkjs#95]
Greetings to everybody!

I am currently working on the [ExplorViz](https://github.com/ExplorViz/explorviz-frontend) project to enhance certain quality characteristics of the frontend code. Surprisingly, the project still uses klayjs (predecessor of elkjs) and an update to elkjs is highly desirable. However, as of now I am not certain how some of the layout options which we currently use have changed their name and to the best of my kowledge there is no documentation which helps to identify the corresponding layout options.
Therefore, I seek help in finding the corresponding layout options for the following properties (if such exist):

- "spacing"
- "borderSpacing"
- "edgeSpacingFactor"
- "de.cau.cs.kieler.minWidth" and "de.cau.cs.kieler.minHeight"

The current implementation for the construction of the graph for which these properties are used can be looked up [here](https://github.com/ExplorViz/explorviz-frontend/blob/dev-1/public/assets/web-workers/layout1.js). For the remaining layout options which we use I am quite confident to have found a matching property using the ELK reference.
Thanks a lot for your advice in advance.

**Comment by uruuru** [comment]
There used to be _legacy ids_ which hinted at the new layout option. They were removed as part of the last release though. 

Regarding node and edge spacings you can have a look at the [spacings example](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=general%2Fspacing%2FnodesEdges). There's no factor option anymore. All options are absolute values. 

Border spacing got replaced by [padding](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-padding.html).

minWidth and minHeight were replaced by [nodeSize.minimum](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-nodesize-minimum.html).

**Comment by Malte-Hansen** [comment]
Thanks a lot, this answers my question.
