### ISSUE TITLE
Non-strict javascript in web-worker

### ISSUE THREAD

**Issue by DPros** [kieler/elkjs#96]
Hello, I'm using the latest 0.7.0 release

here's a stacktrace from non-minified elk-worker (the same is reproduced with the minified one)

```
ReferenceError: _xblockexpression is not defined
    at $transformNode_0 (elk-worker.js:71941)
    at layout_11 (elk-worker.js:73619)
    at Dispatcher.dispatch (elk-worker.js:73562)
    at Dispatcher.saveDispatch (elk-worker.js:73570)
    at elk-worker.js:73587
```

the problem is in the highlighted line, which seems to be non-valid javascript code (the `_xblockexpression` variable has never been defined in the current scope). 
```
function $transformNode_0(this$static, jsonNode, parent_0){
  var node, node_0, elkNode, jsonObj, _optJSONArray, _function;
  node = $register_4(this$static, (node_0 = ($clinit_ElkGraphFactory() , elkNode = new ElkNodeImpl , elkNode) , !!parent_0 && $setParent_2(node_0, parent_0) , node_0), jsonNode);
  $setIdentifier(node, $optString(jsonNode, 'id'));
  $transformProperties(jsonNode, node);
  $transformIndividualSpacings(jsonNode, node);
  $transformShapeLayout(jsonNode, node);
  
  _xblockexpression = null;

  jsonObj = jsonNode;
  _optJSONArray = $optJSONArray(jsonObj, 'ports');
  _function = new JsonImporter$lambda$30$Type(this$static, node);
  $lambda$30(_function.$$outer_0, _function.parent_1, _optJSONArray);
  $transformLabels(this$static, jsonNode, node);
  $transformChildNodes(this$static, jsonNode, node);
  return node;
}
```

Prepending a `var` keyword or removing it altogether solves the issue. 
Is there a chance to fix it?

**Comment by uruuru** [comment]
The code is completely generated by `GWT`, I'll have to take a closer look as to why this is generated. 

Just wondering: In plain javascript the `_xblockexpression ` should simply end up in global scope, shouldn't it? As such I'd assume that you are using some strict mode.

**Comment by DPros** [comment]
Indeed. I'm using it in an angular project and the error is not reproduced with aot compiler. Still, might you be considering to compile in strict mode? as far as I understand, it might somewhat increase the performance

**Comment by uruuru** [comment]
I'll certainly take a look once I find time. Maybe there's a switch for GWT's transpiler.

**Comment by uruuru** [comment]
With the mentioned parameter it's possible to run the worker with `"use strict"`. However, the execution time seems to be roughly 10% slower (for the models in eclipse/elk-models). Hence, I'd not add the option by default. 

Do you know if there are scenarios in which it's impossible to exclude the worker from being executed in a non strict environment?

**Comment by uruuru** [comment]
To conclude, as mentioned above, adding `-Xnamespace PACKAGE` to the gwtc args adds further scopes, avoiding global variables.

I'll not add this option by default though. If there are good reasons to do so, feel free to revive this discussion.

**Comment by JHERR1112** [comment]
Thank you for linking me to this issue.  Seems like this person ran into the same issue I did.  I read over the dialogue and it seems like the **Xnamespace** GWTC parameter needs to be added and set to value of **PACKAGE**.  I am a little confused of where this needs to be done.  I was looking at the elk-worker.js file and saw that you are adding GWT properties via the _setGwtProperty_ function on line 98734.  Is the solution then to modify the elk-worker.js file and add this parameter? Sorry if this questions seems ignorant as I've never worked with GWTC.

**Comment by uruuru** [comment]
It needs to be added here 
https://github.com/kieler/elkjs/blob/dc2baacd174dfb8f8c53b756e6d6f7a10249b451/build.gradle#L268

and/or in line 278 depending on whether you want to use the non-/minified version. 

You have to build everything locally then, i.e. it's not possible to make this adjustment to the deployed files. 

Side note: It would be interesting to understand if this problem originates from using different GWT versions (2.8 vs 2.9), or if it is due to some change in ELKs code base.

**Comment by JHERR1112** [comment]
**Interesting finding**: A teammate of mine with the same elk setup faces no issue when upgrading to v0.7.1.  The only difference is that he's working in an angular project and I am working in a bare bone typescript project. I wonder if Angular's compiler plays a role here.

**Comment by alexei-tilikin** [comment]
Hello @uruuru,
I'm facing this issue too, trying to use v0.7.1 with webpack build with es6.
I saw this PR: https://github.com/kieler/elkjs/pull/137 that seems to resolve the issue.

Is it staged for the next release version (0.8.0)?
The PR is marked for 0.7.2 milestone, but I'm guessing 0.7.2 was never released, right?

**Comment by soerendomroes** [comment]
It was released as 0.7.2-dev. elkjs@next should point to 0.7.3-dev (see [npm](https://www.npmjs.com/package/elkjs))

**Comment by alexei-tilikin** [comment]
`*-dev` means it's not a stable release?
0.7.2-dev still has the same issue.
I'll try 0.7.3-dev

**Comment by soerendomroes** [comment]
I am not really familiar with elkjs version, maybe @uruuru can help.

**Comment by alexei-tilikin** [comment]
0.7.3-dev seems to have the problem fixed. 
But that's the ongoing master version. 
So I'm assuming the next stable release will be 0.8.0
