### ISSUE TITLE
Edge sometimes not routed entirely

### ISSUE THREAD

**Issue by Nic30** [kieler/elkjs#98]
Hello,

I am using elkjs 0.7.0 and the problem probably was not there in previous version.

Problem:

Sometimes the edge is not fully routed, the start/end point is specified correctly and few points in section are also specified correctly. It seems as if last bend point is sometimes missing.

![image](https://user-images.githubusercontent.com/5032806/97852354-eb4a9c00-1cf6-11eb-8191-2636f4c5c679.png)

```javascript
//l.id=="609"
l.sections = [{​​
  bendPoints: [ 
    { x: 3131.7, y: 555.5 },
​​​    { x: 3131.7, y: 34 }
  ],
​​  ​endPoint:  { x: 917.4499999999998, y: 152.5 },
​​  id: "609_s0",
​​  incomingShape: "360",
​​  outgoingShape: "418",
​​  startPoint: { x: 3101.7, y: 555.5 }
​​},]
```

[online example](
https://hwtlib.readthedocs.io/en/latest/_static/schematic_viewer/schematic_viewer.html?schematic=../../_static/hwt_schematics/hwtLib.amba.axis_comp.fifoCopy.AxiSFifoCopy-3.json) (may require 1-5x refresh to trigger the issue, issue happens always on same signal, JSON in URL, but there is nothing special about the net with the issue)

You can get output from elkjs by:
```javascript
d3.selectAll(".link-wrap").filter((d)=> { return d.hwMeta.name == "dataOut_id"}).data()
```

I am using just algorithm specification for elk without any special modifiers.
```javascript
layouter = new ELK({
			algorithms: ['layered'],
		});
```

Do you have any guess about what is causing this issue?

**Comment by uruuru** [comment]
There was something in ELK that this reminds me ok but I can't find the issue right now. 

One question: why do you get a different layout eacht time? The layout itself should be "stable", given the same input graph. Hence I'd assume that your input graph changes in structure between browser refreshs?

**Comment by Nic30** [comment]
> The layout itself should be "stable",

I was thinking that it is not the case whole time. I am not aware of any non deterministic operations during grap processing and an input should be always same, but I will check.

> Can I print the input to the layouter as well?

The input is same and it its URL is in the URL for the "scheme viewer" 
https://hwtlib.readthedocs.io/en/latest/_static/hwt_schematics/hwtLib.amba.axis_comp.fifoCopy.AxiSFifoCopy-3.json

Alternatively 
```javascript
hwSchematic.layouter.graph
```

**Comment by Nic30** [comment]
I checked the input before calling layouter.layout() of elk using
```javascript
JSON.stringify(graph, function(key, val) {
    if (key === 'renderer' || key=== "parent") {
        return;
    }
    return val;
});
```

and the input is really the same:

[j1.zip](https://github.com/kieler/elkjs/files/5477886/j1.zip)

**Comment by Nic30** [comment]
Do you think that it could be somehow related to:
```javascript
                                "org.eclipse.elk.randomSeed": 0,
                                "org.eclipse.elk.layered.mergeEdges": 1
```

**Comment by uruuru** [comment]
`randomSeed: 0` has indeed the effect that each time a _different_ seed is chosen. That explains the non-determinism in the result.

**Comment by Nic30** [comment]
https://www.eclipse.org/elk/reference/options/org-eclipse-elk-randomSeed.html
Well, I should have read the doc.

**Comment by Nic30** [comment]
I fixed the determinism of the layout but still a single net in the middle (`replace_id_val_next`) is not routed entirely. (URL remains the same, json just does not have `org.eclipse.elk.layered.mergeEdges` specified)

**Comment by uruuru** [comment]
Yes, it looks like a bug to me. We'll have to take a closer look. It seems to occur in cases of feedback loops, where edge are routed around the node before connecting to a port. 

If you encounter a smaller example, please let us know.

**Comment by Nic30** [comment]
I am preparing a list of schemes with the bug, the most simple example I found so far is https://hwtlib.readthedocs.io/en/latest/_static/schematic_viewer/schematic_viewer.html?schematic=../../_static/hwt_schematics/hwtLib.amba.axis_comp.splitCopy.AxiSSplitCopy-11.json

**Comment by uruuru** [comment]
Ah, thanks. I guess that'll do. No need to assemble a complete list ;).

**Comment by Nic30** [comment]
I have to say that the issue is very rare and I do see the pattern, the bug usually appears on the edge from west side of component to a port on west side of a different node which is placed more or right. However I have seen around 1K cases like this and it was correct.

**Comment by uruuru** [comment]
A just looked at the input jsons more closely and they sometimes contain edges like below. There are two problems with it: First, there's an array nested in an array while the outer array should already contain the ids. Second, ELK currently cannot handle edges with multiple sources or targets. 

I was of the impression that it should raise an exception if this ever is input but apparently it doesn't. 
```
{
            "sources": [
                [
                    "1",
                    "9"
                ]
            ],
            "targets": [
                [
                    "5",
                    "21"
                ],
                [
                    "6",
                    "24"
                ]
            ],
            "id": "28",
            "hwMeta": {
                "name": "dataIn_valid"
            }
        },
```

**Comment by Nic30** [comment]
Sorry I forgot to mention. The hyper edges are expanded, Eg. the JSON from https://hwtlib.readthedocs.io/en/latest/_static/schematic_viewer/schematic_viewer.html?schematic=../../_static/hwt_schematics/hwtLib.amba.axis_comp.splitCopy.AxiSSplitCopy-11.json will be only 
[j1.zip](https://github.com/kieler/elkjs/files/5483680/j1.zip)

**Comment by uruuru** [comment]
Thanks. The issue may unfortunately be more intricate. At least there's no obvious error to me. I created [elk#726](https://github.com/eclipse/elk/issues/726).

**Comment by Nic30** [comment]
OK, let's close this issue because the issue moved to elk#726.
I try to make some experiments as soon as I find some time. But now, it just does not make any sense to me as well.

**Comment by uruuru** [comment]
I usually keep the issues open for elkjs to track in which release the fix will be included.

**Comment by uruuru** [comment]
Has been fixed in ELK, will be included in the next release.

**Comment by Nic30** [comment]
Hello, today I tested the ELK 0.7.1 I can confirm that the fix works for some examples but not for all.
Also for some examples I am getting this error:

```
Uncaught (in promise) Error: java.lang.IllegalStateException: Invalid hitboxes for scanline constraint calculation.
    Mx elk.bundled.js:76816
    Sx elk.bundled.js:76831
    Kx elk.bundled.js:8072
    Vx elk.bundled.js:3048
    hcb elk.bundled.js:3163
    yCb elk.bundled.js:37765
    xCb elk.bundled.js:30352
    BCb elk.bundled.js:80145
    oBb elk.bundled.js:24734
    qBb elk.bundled.js:10827
    tCb elk.bundled.js:30994
    wcc elk.bundled.js:83978
    VBb elk.bundled.js:24208
    YBb elk.bundled.js:57992
    ZBb elk.bundled.js:35266
    Ddc elk.bundled.js:51760
    Jdc elk.bundled.js:84172
    ERb elk.bundled.js:51230
    CRb elk.bundled.js:32930
    cSb elk.bundled.js:81589
    XZc elk.bundled.js:21845
    $Zc elk.bundled.js:64305
    ZZc elk.bundled.js:29451
    zqd elk.bundled.js:48519
    dispatch elk.bundled.js:64349
    saveDispatch elk.bundled.js:64361
    postMessage elk.bundled.js:64381
    setTimeout handler*j/this.postMessage elk.bundled.js:64380
    postMessage elk.bundled.js:233
    postMessage elk.bundled.js:222
    layout elk.bundled.js:152
    start d3-hwschematic.js:1457
    _draw d3-hwschematic.js:1758
    bindData d3-hwschematic.js:1743
    <anonymous> example.html:115
    promise callback* example.html:111
elk.bundled.js:formatted:76816
```

It seems to me that this is a consequence of the fix as the error happens in examples which ware suffering from this issue with edge routing.

Examples with java.lang.IllegalStateException: Invalid hitboxes for scanline constraint calculation. 
* I2cMasterBitCtrl.json [see in 0.7.0](https://hwtlib.readthedocs.io/en/latest/_static/schematic_viewer/schematic_viewer.html?schematic=../../_static/hwt_schematics/hwtLib.peripheral.i2c.masterBitCntrl.I2cMasterBitCtrl-0.json)
* CuckooHashTable.json [see in 0.7.0](https://hwtlib.readthedocs.io/en/latest/_static/schematic_viewer/schematic_viewer.html?schematic=../../_static/hwt_schematics/hwtLib.mem.cuckooHashTable.CuckooHashTable-4.json)

Examples with broken routing:
* AxiTester.json  [see in 0.7.0](https://hwtlib.readthedocs.io/en/latest/_static/schematic_viewer/schematic_viewer.html?schematic=../../_static/hwt_schematics/hwtLib.amba.axi_comp.tester.AxiTester-6.json)
* AddrDataHs_to_Axi.json  [see in 0.7.0](https://hwtlib.readthedocs.io/en/latest/_static/schematic_viewer/schematic_viewer.html?schematic=../../_static/hwt_schematics/hwtLib.common_nonstd_interfaces.addr_data_hs_to_Axi.AddrDataHs_to_Axi-0.json)

All examples mentioned are available in [d3-hwschematic](https://github.com/Nic30/d3-hwschematic/tree/master/examples/schemes)
You can see them in in 0.7.1 if you update the package.json in that git and follow readme.

It should be simple but of coarse I will help whenever I can.
The issue seems to be related to some special graph property rather than graph size, sadly the examples with an error large.
My question is if you can see the problem or I need to dig deeper. Also I can potentially contribute many test graphs for your CI if you want.

**Comment by uruuru** [comment]
@Nic30 this error:
> Uncaught (in promise) Error: java.lang.IllegalStateException: Invalid hitboxes for scanline constraint calculation.

indicates that you have switched on horizontal compaction. Could you switch that off and check if the layouts are fine in that case? 

I'd like see if the default configuration behaves properly, to decide what kind of issue should be raised.
